### ISSUE TITLE
render_many/4 raising error on .leex templates

### ISSUE THREAD

**Issue by gushonorato** [phoenixframework/phoenix_live_view#1029]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): phoenix 1.5.3 (Hex package) (mix)
* Phoenix LiveView version (mix deps): phoenix_live_view 0.13.3 (Hex package) (mix)
* NodeJS version (node -v): v12.13.0
* NPM version (npm -v): 6.12.0
* Operating system: macOS Mojave 10.14.6
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome 83.0.4103.116 64 bits
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When I try to use `render_many/4` inside a LiveView .leex template 

```elixir
# products_live.html.leex
<%= render_many(@collections, CollectionView, "show.html") %>

# show.hmtl.leex
<h2><%= @collection.name %></h2>
```
I  got the following error:
```
[error] #PID<0.2711.0> running FoodPopsWeb.Endpoint (connection #PID<0.2679.0>, stream id 7) terminated
Server: localhost:4000 (http)
Request: GET /p
** (exit) an exception was raised:
    ** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: %Phoenix.LiveView.Rendered{dynamic: #Function<0.88251762/1 in FoodPopsWeb.CollectionView."show.html"/1>, fingerprint: 243510759860645750182420186495126371753, static: ["<h2>", "</h2>\n"]}
        (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:81: Phoenix.HTML.Safe.List.to_iodata/1
        (phoenix_html 2.14.2) lib/phoenix_html/safe.ex:49: Phoenix.HTML.Safe.List.to_iodata/1
        (food_pops 0.1.0) lib/food_pops_web/live/products_live.html.leex:7: anonymous fn/2 in FoodPopsWeb.ProductsLive.render/1
        (phoenix_live_view 0.13.3) lib/phoenix_live_view/diff.ex:250: Phoenix.LiveView.Diff.traverse/5
        (phoenix_live_view 0.13.3) lib/phoenix_live_view/diff.ex:321: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_dynamic/5
        (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.13.3) lib/phoenix_live_view/diff.ex:250: Phoenix.LiveView.Diff.traverse/5
        (phoenix_live_view 0.13.3) lib/phoenix_live_view/diff.ex:97: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.13.3) lib/phoenix_live_view/static.ex:284: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.13.3) lib/phoenix_live_view/static.ex:144: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.13.3) lib/phoenix_live_view/controller.ex:35: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.5.3) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (food_pops 0.1.0) lib/food_pops_web/endpoint.ex:1: FoodPopsWeb.Endpoint.plug_builder_call/2
        (food_pops 0.1.0) lib/plug/debugger.ex:132: FoodPopsWeb.Endpoint."call (overridable 3)"/2
        (food_pops 0.1.0) lib/food_pops_web/endpoint.ex:1: FoodPopsWeb.Endpoint.call/2
        (phoenix 1.5.3) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /Users/gustavo/OneDrive/Code/food_pops/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /Users/gustavo/OneDrive/Code/food_pops/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /Users/gustavo/OneDrive/Code/food_pops/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

But it works when I change the code to this:
```elixir
# products_live.html.leex
<%= for collection <- @collections do %>
  <%= render(CollectionView, "show.html", collection: collection) %>
<% end %>
```

### Expected behavior

I expect that both `render/3` and `render_many/4` works as the same. Am I missing something?

**Comment by josevalim** [comment]
The reason why render_many does not work is because LiveView wants you to use the comprehension since we can Generally optimize that better. The more “makeup” LV can see, generally the better. :)

**Comment by gushonorato** [comment]
Maybe LV could print a more friendly error. This error message hasn't helped me too much. I've spent some time racking my brain 😅
