### ISSUE TITLE
Tests failing when phx-update is used

### ISSUE THREAD

**Issue by StanBright** [phoenixframework/phoenix_live_view#1155]
Hey mates,

I've been struggling with this one for a few days now and cannot find a working solution. I read everything in this closed issue - https://github.com/phoenixframework/phoenix_live_view/issues/566; however, I still couldn't make it work. Please note that the same code works perfectly in dev/production without any JS or elixir/phoenix errors.

I'm using the latest Elixir (1.10.4), Phoenix (1.5.5) & LiveView (0.14.6). 

Live Template
```
<ul id="matches" class="post-matches" phx-hook="LiveMatchesUpdated" phx-update="prepend">
    <%= for match <- @matches do %>
      <% post = match.post %>
      <li id="post-<%= match.id %>" class="post content">…</li>
    <% end %>
</ul>
```

Message handling function
```Elixir
def handle_info({:match, %Match{} = match}, socket) do
  {:noreply, assign(socket, :matches, [match])}
end
```

This is the test setup:
```Elixir
test "initial mount and receiving a match", %{conn: conn} do
      {:ok, view, html} = live(conn, "/matches")
      assert html =~ "Waiting for keyword matches"

      # https://github.com/phoenixframework/phoenix_live_view/issues/566
      match = %Match{
        id: :os.system_time(),
        keyword: "test",
        post: build(:post, title: "Some title"),
      }
      send(view.pid, {:match, match})
      assert render(view) =~ "Some title"
end
```

And this is the exception when running tests:
```Elixir
         ** (ArgumentError) setting phx-update to "prepend" requires setting an ID on each child. No ID was found on:
  
           
             (phoenix_live_view 0.14.6) lib/phoenix_live_view/test/dom.ex:336: anonymous fn/3 in Phoenix.LiveViewTest.DOM.apply_phx_update_children_id/2
             (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
             (phoenix_live_view 0.14.6) lib/phoenix_live_view/test/dom.ex:334: Phoenix.LiveViewTest.DOM.apply_phx_update_children_id/2
             (phoenix_live_view 0.14.6) lib/phoenix_live_view/test/dom.ex:262: Phoenix.LiveViewTest.DOM.apply_phx_update/3
             (floki 0.28.0) lib/floki/traversal.ex:6: anonymous fn/3 in Floki.Traversal.traverse_and_update/2
```
Notice that "**No ID was found on**:" is followed by blank lines only.

Any idea what is wrong or how I could dig deeper to resolve it?

**Comment by StanBright** [comment]
Thanks for the blazing fast response @josevalim. You are are star!
