### ISSUE TITLE
DOMException, querySelector, not a valid selector

### ISSUE THREAD

**Issue by cjbottaro** [phoenixframework/phoenix_live_view#1301]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.3
* NodeJS version (node -v): v14.15.3
* NPM version (npm -v): 6.14.9
* Operating system: OS X
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Element': '#timed_node[times][0][start_time], [name="timed_node[times][0][start_time]"]' is not a valid selector.
    at Object.discardError (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:1843:24)
    at onBeforeNodeAdded (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:2057:29)
    at eval (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:211:25)
    at T (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:225:12)
    at eval (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:202:211)
    at T (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:225:12)
    at eval (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:202:211)
    at T (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:225:12)
    at eval (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:202:211)
    at T (webpack-internal:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js:225:12)
```

### Description

I'm using LiveView for a form backed by an Ecto.Schema with embeds_many.

Let me know what other info I can provide. Thanks.

**Comment by josevalim** [comment]
We should change the id lookup from #ID to [id=“ID”].

**Comment by TheArrowsmith** [comment]
I'm seeing this same error when using `JS.dispatch` on a form's `phx-change` handler:

```heex
        <.form
          for={@search_form}
          id="search-form"
          phx-change={JS.dispatch("search")}
          phx-debounce
          phx-submit="noop"
          phx-target={@myself}
          phx-hook="SearchForm"
        >
```

When the socket tries to reconnect after a disconnection, I get the "We can't find the internet" flash error, which hangs indefinitely, then I see this in the browser console:

`view.js:1121 Uncaught DOMException: Failed to execute 'querySelector' on 'DocumentFragment': 'form[id="search-form"][phx-change="[["dispatch",{"to":null,"event":"search"}]]"]' is not a valid selector.`

That's coming from this line in `phoenix_live_view/view.js`:

```javascript
let newForm = template.content.querySelector(`form[id="${form.id}"][${phxChange}="${form.getAttribute(phxChange)}"]`)
```

I figure this could be fixed by escaping any `"`s in the attribute:

```javascript
          let changeAttr = form.getAttribute(phxChange).replace(/"/g, '\\"')
          let newForm = template.content.querySelector(`form[id="${form.id}"][${phxChange}="${changeAttr}"]`)
```

But unfortunately I can't figure out how to test this, because I can't figure out how to set up an app so that it loads `phoenix_live_view.js` from my local fork of the `phoenix_live_view` repo... any pointers for how I can do this? And am I onto something by thinking that `"`s should be escaped here?

**Comment by TheArrowsmith** [comment]
Oh wait, I've just seen that `view.js` already has some escaping in place on current `main`. I guess I need to update my LV version (I was running 0.19.4)
