### ISSUE TITLE
Error with multiple live_file_input in one form

### ISSUE THREAD

**Issue by gorghoa** [phoenixframework/phoenix_live_view#1347]
### Environment

* Elixir version (elixir -v): `1.11.2`
* Phoenix version (mix deps): `1.5.8`
* Phoenix LiveView version (mix deps): `0.15.4`
* NodeJS version (node -v): `10`
* NPM version (npm -v): `6`
* Operating system: `Debian buster`
* Browsers you attempted to reproduce this bug on (the more the merrier):  `firefox`, `chrome`
* Does the problem persist after removing "assets/node_modules" and trying again? : `Yes`

### Actual behavior

Given a form with multiple `live_file_input`, when the form is submitted, the `phx-submit` callback is called as soon as the first upload has finished.

Then, when two  `consume_uploaded_entries` are called in the callback, the error `cannot consume uploaded files when entries are still in progress` may be raised if one of the upload is not finished.

Hereafter is the most comprehensible live view module to reproduce this behavior:

Note: I have found that selecting a big file in the first input and a small one in the second is the best option to trigger this behavior. 

```elixir
defmodule MultipleInputsWeb.PageLive do
  use MultipleInputsWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
      socket
      |> allow_upload(:file1, accept: :any)
      |> allow_upload(:file2, accept: :any)
    }
  end

  def render(assigns) do
    ~L"""
    <form phx-change="validate" phx-submit="submit">
        <%= live_file_input @uploads.file1 %>
        <%= live_file_input @uploads.file2 %>

        <%= submit "Save" %>
    </form>
    """
  end

  def handle_event("validate",_,socket), do: {:noreply, socket}

  def handle_event("submit", _, socket) do
    consume_uploaded_entries(socket, :file1, fn _, _ -> :ok1 end)
    consume_uploaded_entries(socket, :file2, fn _, _ -> :ok2 end)

    {:noreply, socket}
  end
end

```

<details>

<summary>
Error logs
</summary>

```
[error] GenServer #PID<0.1813.0> terminating
** (ArgumentError) cannot consume uploaded files when entries are still in progress
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/upload.ex:218: Phoenix.LiveView.Upload.consume_uploaded_entries/3
    (multiple_inputs 0.1.0) lib/multiple_inputs_web/live/page_live.ex:27: MultipleInputsWeb.PageLive.handle_event/3
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:338: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 0.4.2) /home/gorghoa/incub/multiple_inputs/deps/telemetry/src/telemetry.erl:262: :telemetry.span/3
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:203: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "4", payload: %{"event" => "submit", "type" => "form", "value" => ""}, ref: "36", topic: "lv:phx-FmcIMwA6oclwqhQj"}
State: %{components: {%{}, %{}, 1}, join_ref: "4", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{flash: %{}, live_action: :index, uploads: %{__phoenix_refs_to_names__: %{"phx-FmcIM5nioSuseBck" => :file1, "phx-FmcIM5njEGSseBdE" => :file2}, file1: #Phoenix.LiveView.UploadConfig<accept: :any, auto_upload?: false, ...>, file2: #Phoenix.LiveView.UploadConfig<accept: :any, ...>}}, changed: %{}, endpoint: MultipleInputsWeb.Endpoint, id: "phx-FmcIMwA6oclwqhQj", parent_pid: nil, root_pid: #PID<0.1813.0>, router: MultipleInputsWeb.Router, view: MultipleInputsWeb.PageLive, ...>, topic: "lv:phx-FmcIMwA6oclwqhQj", transport_pid: #PID<0.1810.0>, upload_names: %{file1: {"phx-FmcIM5nioSuseBck", nil}, file2: {"phx-FmcIM5njEGSseBdE", nil}}, upload_pids: %{#PID<0.1814.0> => {"phx-FmcIM5nioSuseBck", "1", nil}, #PID<0.1816.0> => {"phx-FmcIM5njEGSseBdE", "0", nil}}}
[error] GenServer #PID<0.1814.0> terminating
** (ArgumentError) cannot consume uploaded files when entries are still in progress
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/upload.ex:218: Phoenix.LiveView.Upload.consume_uploaded_entries/3
    (multiple_inputs 0.1.0) lib/multiple_inputs_web/live/page_live.ex:27: MultipleInputsWeb.PageLive.handle_event/3
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:338: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 0.4.2) /home/gorghoa/incub/multiple_inputs/deps/telemetry/src/telemetry.erl:262: :telemetry.span/3
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:203: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.3524449670.2190475268.173342>, :process, #PID<0.1813.0>, {%ArgumentError{message: "cannot consume uploaded files when entries are still in progress"}, [{Phoenix.LiveView.Upload, :consume_uploaded_entries, 3, [file: 'lib/phoenix_live_view/upload.ex', line: 218]}, {MultipleInputsWeb.PageLive, :handle_event, 3, [file: 'lib/multiple_inputs_web/live/page_live.ex', line: 27]}, {Phoenix.LiveView.Channel, :"-view_handle_event/3-fun-0-", 3, [file: 'lib/phoenix_live_view/channel.ex', line: 338]}, {:telemetry, :span, 3, [file: '/home/gorghoa/incub/multiple_inputs/deps/telemetry/src/telemetry.erl', line: 262]}, {Phoenix.LiveView.Channel, :handle_info, 2, [file: 'lib/phoenix_live_view/channel.ex', line: 203]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 689]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 765]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
State: %Phoenix.Socket{assigns: %{chunk_timeout: 10000, chunk_timer: #Reference<0.3524449670.2190475265.179178>, done?: false, handle: #PID<0.1815.0>, live_view_pid: #PID<0.1813.0>, max_file_size: 3872156, path: "/tmp/plug-1614/live_view_upload-1614268025-544573674044698-3", uploaded_size: 384000}, channel: Phoenix.LiveView.UploadChannel, channel_pid: #PID<0.1814.0>, endpoint: MultipleInputsWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "11", joined: true, private: %{connect_info: %{session: %{"_csrf_token" => "nGQkiwJcXn5zAF3fXpvldb63"}}, log_handle_in: false, log_join: :info}, pubsub_server: MultipleInputs.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lvu:1", transport: :websocket, transport_pid: #PID<0.1810.0>}
[error] GenServer #PID<0.1816.0> terminating
** (ArgumentError) cannot consume uploaded files when entries are still in progress
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/upload.ex:218: Phoenix.LiveView.Upload.consume_uploaded_entries/3
    (multiple_inputs 0.1.0) lib/multiple_inputs_web/live/page_live.ex:27: MultipleInputsWeb.PageLive.handle_event/3
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:338: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 0.4.2) /home/gorghoa/incub/multiple_inputs/deps/telemetry/src/telemetry.erl:262: :telemetry.span/3
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:203: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.3524449670.2190475267.178619>, :process, #PID<0.1813.0>, {%ArgumentError{message: "cannot consume uploaded files when entries are still in progress"}, [{Phoenix.LiveView.Upload, :consume_uploaded_entries, 3, [file: 'lib/phoenix_live_view/upload.ex', line: 218]}, {MultipleInputsWeb.PageLive, :handle_event, 3, [file: 'lib/multiple_inputs_web/live/page_live.ex', line: 27]}, {Phoenix.LiveView.Channel, :"-view_handle_event/3-fun-0-", 3, [file: 'lib/phoenix_live_view/channel.ex', line: 338]}, {:telemetry, :span, 3, [file: '/home/gorghoa/incub/multiple_inputs/deps/telemetry/src/telemetry.erl', line: 262]}, {Phoenix.LiveView.Channel, :handle_info, 2, [file: 'lib/phoenix_live_view/channel.ex', line: 203]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 689]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 765]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
State: %Phoenix.Socket{assigns: %{chunk_timeout: 10000, chunk_timer: nil, done?: true, handle: #PID<0.1817.0>, live_view_pid: #PID<0.1813.0>, max_file_size: 270028, path: "/tmp/plug-1614/live_view_upload-1614268025-536647421783286-3", uploaded_size: 270028}, channel: Phoenix.LiveView.UploadChannel, channel_pid: #PID<0.1816.0>, endpoint: MultipleInputsWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "14", joined: true, private: %{connect_info: %{session: %{"_csrf_token" => "nGQkiwJcXn5zAF3fXpvldb63"}}, log_handle_in: false, log_join: :info}, pubsub_server: MultipleInputs.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lvu:0", transport: :websocket, transport_pid: #PID<0.1810.0>}
[error] GenServer #PID<0.1819.0> terminating
** (stop) exited in: GenServer.call(#PID<0.1813.0>, {:phoenix, :register_entry_upload, %{channel_pid: #PID<0.1819.0>, cid: nil, entry_ref: "1", ref: "phx-FmcIM5nioSuseBck"}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.11.0) lib/gen_server.ex:1027: GenServer.call/3
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/upload_channel.ex:36: Phoenix.LiveView.UploadChannel.join/3
    (phoenix 1.5.8) lib/phoenix/channel/server.ex:376: Phoenix.Channel.Server.channel_join/4
    (phoenix 1.5.8) lib/phoenix/channel/server.ex:298: Phoenix.Channel.Server.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {Phoenix.Channel, %{"token" => "SFMyNTY.g2gDaAJhBHQAAAADZAADY2lkZAADbmlsZAADcGlkWGQADW5vbm9kZUBub2hvc3QAAAcVAAAAAAAAAABkAANyZWZoAm0AAAAUcGh4LUZtY0lNNW5pb1N1c2VCY2ttAAAAATFuBgC8SN_ZdwFiAAFRgA.MJPz4tta2DpDUEqeDVYBcZ00wS41Ew_5DJHzKjrp_2w"}, {#PID<0.1810.0>, #Reference<0.3524449670.2190475265.179215>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.UploadChannel, channel_pid: nil, endpoint: MultipleInputsWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "39", joined: false, private: %{connect_info: %{session: %{"_csrf_token" => "nGQkiwJcXn5zAF3fXpvldb63"}}}, pubsub_server: MultipleInputs.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lvu:1", transport: :websocket, transport_pid: #PID<0.1810.0>}}
State: #Reference<0.3524449670.2190475265.179217>
[error] exited in: GenServer.call(#PID<0.1813.0>, {:phoenix, :register_entry_upload, %{channel_pid: #PID<0.1819.0>, cid: nil, entry_ref: "1", ref: "phx-FmcIM5nioSuseBck"}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
[error] GenServer #PID<0.1820.0> terminating
** (stop) exited in: GenServer.call(#PID<0.1813.0>, {:phoenix, :register_entry_upload, %{channel_pid: #PID<0.1820.0>, cid: nil, entry_ref: "0", ref: "phx-FmcIM5njEGSseBdE"}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.11.0) lib/gen_server.ex:1027: GenServer.call/3
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/upload_channel.ex:36: Phoenix.LiveView.UploadChannel.join/3
    (phoenix 1.5.8) lib/phoenix/channel/server.ex:376: Phoenix.Channel.Server.channel_join/4
    (phoenix 1.5.8) lib/phoenix/channel/server.ex:298: Phoenix.Channel.Server.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {Phoenix.Channel, %{"token" => "SFMyNTY.g2gDaAJhBHQAAAADZAADY2lkZAADbmlsZAADcGlkWGQADW5vbm9kZUBub2hvc3QAAAcVAAAAAAAAAABkAANyZWZoAm0AAAAUcGh4LUZtY0lNNW5qRUdTc2VCZEVtAAAAATBuBgC9SN_ZdwFiAAFRgA.KoqTf3ixNTPmE37bliVpgjosayB0WFXS5RJubxe7Vqo"}, {#PID<0.1810.0>, #Reference<0.3524449670.2190475265.179229>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.UploadChannel, channel_pid: nil, endpoint: MultipleInputsWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "40", joined: false, private: %{connect_info: %{session: %{"_csrf_token" => "nGQkiwJcXn5zAF3fXpvldb63"}}}, pubsub_server: MultipleInputs.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lvu:0", transport: :websocket, transport_pid: #PID<0.1810.0>}}
State: #Reference<0.3524449670.2190475266.178271>
[error] exited in: GenServer.call(#PID<0.1813.0>, {:phoenix, :register_entry_upload, %{channel_pid: #PID<0.1820.0>, cid: nil, entry_ref: "0", ref: "phx-FmcIM5njEGSseBdE"}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
[error] GenServer #PID<0.1818.0> terminating
** (KeyError) key "phx-FmcIM5nioSuseBck" not found in: %{"phx-FmcIN40l-8iPkRnB" => :file1, "phx-FmcIN40mqqSPkRnh" => :file2}
    :erlang.map_get("phx-FmcIM5nioSuseBck", %{"phx-FmcIN40l-8iPkRnB" => :file1, "phx-FmcIN40mqqSPkRnh" => :file2})
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/upload.ex:166: Phoenix.LiveView.Upload.get_upload_by_ref!/2
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/upload.ex:100: Phoenix.LiveView.Upload.update_progress/4
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:139: anonymous fn/4 in Phoenix.LiveView.Channel.handle_info/2
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:995: Phoenix.LiveView.Channel.write_socket/4
    (phoenix_live_view 0.15.4) lib/phoenix_live_view/channel.ex:137: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "progress", join_ref: "38", payload: %{"entry_ref" => "1", "event" => nil, "progress" => 9, "ref" => "phx-FmcIM5nioSuseBck"}, ref: "41", topic: "lv:phx-FmcIMwA6oclwqhQj"}
State: %{components: {%{}, %{}, 1}, join_ref: "38", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{flash: %{}, live_action: :index, uploads: %{__phoenix_refs_to_names__: %{"phx-FmcIN40l-8iPkRnB" => :file1, "phx-FmcIN40mqqSPkRnh" => :file2}, file1: #Phoenix.LiveView.UploadConfig<accept: :any, auto_upload?: false, ...>, file2: #Phoenix.LiveView.UploadConfig<accept: :any, ...>}}, changed: %{}, endpoint: MultipleInputsWeb.Endpoint, id: "phx-FmcIMwA6oclwqhQj", parent_pid: nil, root_pid: #PID<0.1818.0>, router: MultipleInputsWeb.Router, view: MultipleInputsWeb.PageLive, ...>, topic: "lv:phx-FmcIMwA6oclwqhQj", transport_pid: #PID<0.1810.0>, upload_names: %{}, upload_pids: %{}}
```

</details>

### Expected behavior

I would expect that each upload is finished before triggering the submit callback.

### See Also

- This discussion in elixir forum: https://elixirforum.com/t/liveview-uploads-multiple-live-file-input/36070

**Comment by gorghoa** [comment]
Aside note for those arriving here to find a solution: Using the option `auto_upload: true` (https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#allow_upload/3) is probably a viable workaround.

**Comment by mayankgureja** [comment]
Seeing the same issue. `auto_upload: true` is not ideal for us since users can choose to upload larger files.

**Comment by evaldobratti** [comment]
I also faced this problem in a multiform with large and small files

until it gets fixed, I made this little workaround...

```elixir
  def handle_event("save", _params, socket) do
    Process.send(self(), :check_continue)
  end

  def handle_info(:check_continue, socket) do
    case uploaded_entries(socket, :files) do
      {entries, []} ->
        #continue code

      _ ->
        # try again in 200ms
        Process.send_after(self(), :check_continue, 200)
        {:noreply, socket}
    end
  end
```

**Comment by gorghoa** [comment]
thank you @mcrumm  :)
