### ISSUE TITLE
protocol Phoenix.HTML.Safe not implemented for %Plug.Conn{}

### ISSUE THREAD

**Issue by nicklayb** [phoenixframework/phoenix_live_view#1351]
### Environment

* Elixir version (elixir -v): 1.10.3
* Phoenix version (mix deps): 1.5.8
* Phoenix LiveView version (mix deps): 0.15.4
* NodeJS version (node -v): 12.18.2
* NPM version (npm -v): 6.14.5
* Operating system: Ubuntu
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox 85.0.1 (64-bit)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

Using `live_render/3` in a loop in an `eex` view rendered by a normal Phoenix controller raises, the view code:

```elixir
<div>
  <%= for object <- @objects do %>
    <span>
      <%= live_render(@conn, OeilWeb.Object.LiveObject, session: %{"id" => object, "thing" => @thing}) %>
    </span>
  <% end %>
</div>

``` 

The first object of the `@objects` list works, then it raises the following message and no other are rendered

```
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{content: {:safe, [60, "div", [[32, "data-phx-session", 61, 34, "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GbWUxTURiVlhveDF4SE9DZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAgRWxpeGlyLk9laWxXZWIuT2JqZWN0LkxpdmVPYmplY3RkAAZyb3V0ZXJkAANuaWxkAAdzZXNzaW9udAAAAAJtAAAAAmlkbQAAAAVwb3QtMm0AAAAFdGhpbmdtAAAAB3NlbnNvcnNkAAR2aWV3ZAAgRWxpeGlyLk9laWxXZWIuT2JqZWN0LkxpdmVPYmplY3RuBgBGRzXldwFiAAFRgA.TjkCwsllB54ZYfZTh38KWXnIcx08tJdqNVmVG0tiqSw", 34], [32, "data-phx-static", 61, 34, "SFMyNTY.g2gDaAJhBHQAAAADZAAKYXNzaWduX25ld2pkAAVmbGFzaHQAAAAAZAACaWRtAAAAFHBoeC1GbWUxTURiVlhveDF4SE9DbgYARkc15XcBYgABUYA.-eFmS1wy1fNtwSDEjTJn4p2R_uSkDrOdjPNTWQNGWQs", 34], [32, "data-phx-view", 61, 34, "Object.LiveObject", 34], [32, "id", 61, 34, "phx-Fme1MDbVXox1xHOC", 34]], 62, ["", ["<div>\n", ["      <p>Loading</p>\n\n"], "</div>\n"], ""], 60, 47, "div", 62]}, flash: %{}, id: "pot-2", layout: {OeilWeb.Layout.View, "app.html"}, live_action: nil, live_module: OeilWeb.Object.LiveObject, objects: ["pot-2", "pot-1", "pot-0"], thing: "sensors", value: :loading}, before_send: [#Function<0.36096693/1 in Plug.CSRFProtection.call/2>, #Function<2.107009429/1 in Phoenix.Controller.fetch_flash/2>, #Function<0.29283909/1 in Plug.Session.before_send/2>, #Function<0.24098476/1 in Plug.Telemetry.call/2>, #Function<1.18804210/1 in Phoenix.LiveReloader.before_send_inject_reloader/3>], body_params: %{}, cookies: %{"_oeil_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYMWhVWFh6dkFJUEEybFAwWS1JTFdMd1Ey.3tQpZYjUny5LxeJxC-5hwmmMl7XTyHDyTpH1tU8FnNY"}, halted: false, host: "localhost", method: "GET", owner: #PID<0.3334.0>, params: %{"thing" => "sensors"}, path_info: ["things", "sensors"], path_params: %{"thing" => "sensors"}, port: 4000, private: %{OeilWeb.Router => {[], %{}}, :phoenix_action => :index, :phoenix_controller => OeilWeb.Thing.Controller, :phoenix_endpoint => OeilWeb.Endpoint, :phoenix_flash => %{}, :phoenix_format => "html", :phoenix_layout => {OeilWeb.Layout.View, :app}, :phoenix_request_logger => {"request_logger", "request_logger"}, :phoenix_root_layout => {OeilWeb.Layout.View, :root}, :phoenix_router => OeilWeb.Router, :phoenix_template => "template.html", :phoenix_view => Phoenix.LiveView.Static, :plug_session => %{"_csrf_token" => "1hUXXzvAIPA2lP0Y-ILWLwQ2"}, :plug_session_fetch => :done}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %{"_oeil_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYMWhVWFh6dkFJUEEybFAwWS1JTFdMd1Ey.3tQpZYjUny5LxeJxC-5hwmmMl7XTyHDyTpH1tU8FnNY"}, req_headers: [{"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"}, {"accept-encoding", "gzip, deflate"}, {"accept-language", "en-CA,en-US;q=0.7,en;q=0.3"}, {"cache-control", "no-cache"}, {"connection", "keep-alive"}, {"cookie", "_oeil_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYMWhVWFh6dkFJUEEybFAwWS1JTFdMd1Ey.3tQpZYjUny5LxeJxC-5hwmmMl7XTyHDyTpH1tU8FnNY"}, {"host", "localhost:4000"}, {"pragma", "no-cache"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"}], request_path: "/things/sensors", resp_body: nil, resp_cookies: %{}, resp_headers: [{"content-type", "text/html; charset=utf-8"}, {"cache-control", "max-age=0, no-cache, no-store, must-revalidate, post-check=0, pre-check=0"}, {"x-request-id", "Fme1MDbB8Hr_dcQAAHNC"}, {"x-frame-options", "SAMEORIGIN"}, {"x-xss-protection", "1; mode=block"}, {"x-content-type-options", "nosniff"}, {"x-download-options", "noopen"}, {"x-permitted-cross-domain-policies", "none"}, {"cross-origin-window-policy", "deny"}, {"vary", "x-requested-with"}], scheme: :http, script_name: [], secret_key_base: :..., state: :sent, status: 200} of type Plug.Conn (a struct). This protocol is implemented for the following type(s): Phoenix.LiveView.Rendered, Phoenix.LiveComponent.CID, Phoenix.LiveView.Comprehension, Phoenix.LiveView.Component, Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Phoenix.HTML.Form, Time, Tuple
        (phoenix_html 2.14.3) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
        (phoenix_html 2.14.3) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
        (oeil_web 0.1.0) lib/oeil_web/thing/templates/thing.html.eex:4: anonymous fn/3 in OeilWeb.Thing.View."thing.html"/1
        (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (oeil_web 0.1.0) lib/oeil_web/thing/templates/thing.html.eex:2: OeilWeb.Thing.View."thing.html"/1
        (phoenix 1.5.8) lib/phoenix/view.ex:310: Phoenix.View.render_within/3
        (phoenix 1.5.8) lib/phoenix/controller.ex:788: Phoenix.Controller.render_with_layouts/4
        (phoenix 1.5.8) lib/phoenix/controller.ex:776: Phoenix.Controller.render_and_send/4
```
 
### Expected behavior

It shouldn't raise and live_render for all the objects (about 3 elements)

### Things I tested

- Placing sequential calls to live render (outside of the for), same issue.
- `live_render` a live view that just display Hello, worked but also raised
- If I call `Enum.reverse/1` on `@objects`, The last element of the list mounts, it raises and no other are shown.

**Comment by josevalim** [comment]
Looking at the stacktrace, the error comes from the second line of your thing.html template, so I am guessing you are trying to output the connection as part of your template. Please double check or include it in the report.

**Comment by nicklayb** [comment]
This might be the wrong stacktrace coming from one of my test but originally it pointed to the live_render line. The template I included is the thing.html. This is where I am wondering, it looks like the live_render function is returning the conn and it doesn't implement the Safe protocol

**Comment by josevalim** [comment]
So if the stacktrace is inaccurate, please provide a mechanism for us to reproduce the error, such as a sample app, thank you!

**Comment by nicklayb** [comment]
The second line is the `for`, the template I included is `thing.html`.

(I deleted the message after I double verified, the stacktrace is accurate now).

It looks to me like the `live_render` function returns the Plug.Conn, if I wrap the `live_render` line in an `IO.inspect`, I do see the Plug.Conn in my console and I just remove it, it doesn't raise.

**Comment by nicklayb** [comment]
Nevermind, sorry for wasting your time. I used the wrong `live_render/3` function, I used the `Phoenix.LiveView.Controller` one instead of the `Phoenix.LiveView.Helpers` one.

[This documentation](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#content) first add the .Controller and then says you can use it in templates or in controller. But it doesn't specify to use the .Helpers module for usage in a template

**Comment by josevalim** [comment]
> The second line is the for, the template I included is thing.html.

Oh, I see!

> This documentation first add the .Controller and then says you can use it in templates or in controller. But it doesn't specify to use the .Helpers module for usage in a template

Can you please send a PR if you think it can be clearer? Thanks!
