### ISSUE TITLE
(FunctionClauseError) no function clause matching in Phoenix.LiveView.Diff.many_to_iodata/5

### ISSUE THREAD

**Issue by paulo-silva** [phoenixframework/phoenix_live_view#1387]
### Environment
* Elixir version (elixir -v):

```
Erlang/OTP 23 [erts-11.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```

* Phoenix version (mix deps):

```
phoenix 1.5.8 (Hex package) (mix)
locked at 1.5.8 (phoenix) 35ded0a3
```

* Phoenix LiveView version (mix deps):

```
phoenix_live_view 0.15.4 (Hex package) (mix)
locked at 0.15.4 (phoenix_live_view) 35d78f3c
```

* NodeJS version (node -v): `v15.3.0`
* NPM version (npm -v): `7.0.4`
* Operating system: `macOS 10.15.7`
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior
A test using render_hooks since the diff fails with (FunctionClauseError) no function clause matching in Phoenix.LiveView.Diff.many_to_iodata/5

Here's is the stacktrace:
```
(phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:74: Phoenix.LiveView.Diff.many_to_iodata([], ["<svg class=\"w-4 h-4\"><use href=\"/images/icons.svg#hamburger\"></svg>"], [["\n    <span class=\"w-full p-4 text-gray-800 p-4 bg-white rounded-md mr-4 flex items-center\">", "Foobar Market Definition 54978", "</span>\n"], "\n          </p>\n        ", "5ff3e198-ef1d-4664-bfe5-403e1e659b66", "\n          <p class=\"-ml-4 -mt-4 absolute flex justify-center items-center h-full w-full text-center text-gray-500\">\n            "], %{1 => %{0 => %{0 => "<a class=\"text-blue-600 hover:underline\" href=\"/market_templates\">Market Templates</a>", 1 => %{d: [["<svg class=\"mt-0.5 mx-2 h-5 w-5\"><use href=\"/images/icons.svg#chevron-right\"></svg>", "<span>Detail</span>"]], s: ["\n", "\n", "\n"]}, :s => ["\n", "\n", "\n"]}, :s => ["<div class=\"flex flex-row mb-6\">\n", "\n</div>\n"]}, 2 => %{0 => "2", 1 => %{0 => "Markets In Template", 1 => "relative flex flex-col h-full bg-gray-100 dropzone p-4 rounded-md last:mb-0", 2 => "", 3 => "markets_in_template", 4 => %{0 => %{0 => "No markets in template yet, drag and drop available markets here to see them in the template.", :d => [["5ff3e198-ef1d-4664-bfe5-403e1e659b66", %{0 => "Foobar Market Definition 54978", :s => ["\n    <span class=\"w-full p-4 text-gray-800 p-4 bg-white rounded-md mr-4 flex items-center\">", "</span>\n"]}, "<svg class=\"w-4 h-4\"><use href=\"/images/icons.svg#hamburger\"></svg>"]], :s => ["\n          <div draggable=\"true\" id=\"", "\" class=\"flex items-center draggable mb-2\">\n            ", "\n            ", "\n          </div>\n        "]}, :s => ["\n        ", "\n      "]}, :s => ["  <div class=\"w-1/2 mx-3 flex flex-col pb-5\">\n    <span class=\"text-black mb-3 font-medium text-base\">", "</span>\n    <div class=\"", " ", "\" id=\"", "\">\n      ", "\n    </div>\n  </div>\n"]}, 2 => %{0 => "Available Markets", 1 => "relative flex flex-col h-full bg-gray-100 dropzone p-4 rounded-md last:mb-0", 2 => "", 3 => "available_markets", 4 => %{0 => %{0 => "No available markets.", :d => [["5ff3e198-ef1d-4664-bfe5-403e1e659b66", %{0 => "Foobar Market Definition 54978", :s => ["\n    <span class=\"w-full p-4 text-gray-800 p-4 bg-white rounded-md mr-4 flex items-center\">", "</span>\n"]}, "<svg class=\"w-4 h-4\"><use href=\"/images/icons.svg#hamburger\"></svg>"]], :s => ["\n          <p class=\"-ml-4 -mt-4 absolute flex justify-center items-center h-full w-full text-center text-gray-500\">\n            ", "\n          </p>\n        "]}, :s => ["\n        ", "\n      "]}, :s => ["  <div class=\"w-1/2 mx-3 flex flex-col pb-5\">\n    <span class=\"text-black mb-3 font-medium text-base\">", "</span>\n    <div class=\"", " ", "\" id=\"", "\">\n      ", "\n    </div>\n  </div>\n"]}, :s => ["<div class=\"h-full flex bg-gray-50 overflow-y-auto border-t border-gray-200 sm:text-sm px-6 pt-6\" phx-target=\"", "\" phx-hook=\"Drag\" id=\"Drag\" class=\"flex\">\n", "\n", "\n</div>\n"]}}, #Function<13.45708693/2 in Phoenix.LiveViewTest.DOM.render_diff/1>)
            (elixir 1.11.2) lib/enum.ex:1521: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
            (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:70: Phoenix.LiveView.Diff.one_to_iodata/6
            (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:57: Phoenix.LiveView.Diff.to_iodata/3
            (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:70: Phoenix.LiveView.Diff.one_to_iodata/6
            (phoenix_live_view 0.15.4) lib/phoenix_live_view/diff.ex:41: Phoenix.LiveView.Diff.to_iodata/2
            (phoenix_live_view 0.15.4) lib/phoenix_live_view/test/dom.ex:189: Phoenix.LiveViewTest.DOM.render_diff/1
            (phoenix_live_view 0.15.4) lib/phoenix_live_view/test/client_proxy.ex:600: Phoenix.LiveViewTest.ClientProxy.merge_rendered/3
            (phoenix_live_view 0.15.4) lib/phoenix_live_view/test/client_proxy.ex:682: Phoenix.LiveViewTest.ClientProxy.handle_reply/2
            (phoenix_live_view 0.15.4) lib/phoenix_live_view/test/client_proxy.ex:360: Phoenix.LiveViewTest.ClientProxy.handle_info/2
            (stdlib 3.13.2) gen_server.erl:680: :gen_server.try_dispatch/4
            (stdlib 3.13.2) gen_server.erl:756: :gen_server.handle_msg/6
            (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Expected behavior
Test passing.

### Resolution
I'm not sure how to fix it, but I guess we need a new pattern clause for many_to_iodata for when the first element is an empty array.

**Comment by josevalim** [comment]
Sounds like a bug indeed! Can you please provide a small project that reproduces the error? This way we will be able to add a regression to our test suite.

**Comment by paulo-silva** [comment]
Hi @josevalim, thank you for your quick answer! 😄

I've created this app with the hook tests: https://github.com/paulo-silva/drag_n_drop_ex

Although I couldn't simulate this error doing the same actions in the test yet 😞, I'll let you know if I find the reason, please, feel free to close this issue if you consider appropriate

**Comment by paulo-silva** [comment]
Hi @josevalim we got to fix the problem by splitting our render in some leex, we had a global leex that had a loop on it creating some divs based on a provided enum, we get that loop and moved into a new leex function:

(pseudocode)
was:

```elixir
def render(assigns) do
  ~L"""
    <div>
      <%= for %{id: id, name: name} <- items do %>
       <div id="<%= id %>"><%= name %></div>
     <% end %>
    </div>
   """
end
```

fixed version:

```elixir
def render(assigns) do
  ~L"""
    <div><%= build_items(assigns) %></div>
   """
end

def build_items(assigns) do
  ~L"""
    <%= for %{id: id, name: name} <- items do %>
      <div id="<%= id %>"><%= name %></div>
   <% end %>
  """
end
```

**Comment by josevalim** [comment]
Thanks @paulo-silva , that's still a bug on LiveView, so if you can reproduce it, it would be great as we could fix it. :)

**Comment by markolson** [comment]
@josevalim The team I'm on stumbled across this issue today, and I was able to come up with a somewhat minimal reproduction at https://github.com/markolson/lv-issue-1387. 

- [page_live.exs](https://github.com/markolson/lv-issue-1387/blob/main/lib/lv_issue_web/live/page_live.ex) 
- [page_live_test.exs](https://github.com/markolson/lv-issue-1387/blob/main/test/lv_issue_web/live/page_live_test.exs)

If any of the following things are changed, the tests will pass:

- The first `render` has either line removed
- The first `render` has the lines reversed
- The second `render`'s call to `some_helper` is removed
- The second `render`'s call to `some_helper` is placed after the loop
- The second `render`'s loop is removed 
- `some_helper` returns a strings instead of `~L`
