### ISSUE TITLE
Getting an error `unable to start child ***Live under duplicate name for parent nil`

### ISSUE THREAD

**Issue by dorilla** [phoenixframework/phoenix_live_view#158]
### Environment

* Elixir version (elixir -v): 1.7.4
* Phoenix version (mix deps): 1.4.2
* NodeJS version (node -v): 10.8.0
* NPM version (npm -v): 6.2.0
* Operating system: gigalixir-14 -> ubuntu-14

### Actual behavior
I'm seeing this in my production logs. I can't reliably duplicate the behavior nor can I see what effect it has in the app, but it pops up quite a bit in the logs.

```
Last message: {:join, Phoenix.LiveView.Channel}
21:05:53.691 [error] an exception was raised:
    ** (RuntimeError) unable to start child BlackJackWeb.BlackJackLive under duplicate name for parent nil.

A child LiveView #PID<0.3931.0> is already running under the ID phx-WCVvW4nbCqg=. (#PID<0.3931.0>)
To render multiple LiveView children of the same module, a
child_id option must be provided per live_render call. For example:

    <%= live_render @socket, BlackJackWeb.BlackJackLive, child_id: 1 %>
    <%= live_render @socket, BlackJackWeb.BlackJackLive, child_id: 2 %>


        (phoenix_live_view) lib/phoenix_live_view/channel.ex:267: Phoenix.LiveView.Channel.register!/3
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:218: Phoenix.LiveView.Channel.verified_join/6
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I'm calling `live_render` in my main `index.html.eex` file:
```
<%= live_render(@conn, BlackJackWeb.BlackJackLive) %>
```

### Expected behavior

No error

**Comment by josevalim** [comment]
Thanks for the report! This will be fixed when we tackle #144!
