### ISSUE TITLE
LiveView callback is invoked when a hook mounted by `on_mount/1` returns `{:halt, socket}`

### ISSUE THREAD

**Issue by nallwhy** [phoenixframework/phoenix_live_view#1598]
### Environment

* Elixir version (elixir -v): 1.21.1
* Phoenix version (mix deps): 1.5.12
* Phoenix LiveView version (mix deps): 0.16.2
* Operating system: macOS Big Sur
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

https://github.com/nallwhy/my_test

I mounted `MyTestWeb.UserLiveAuth` to `MyTestWeb.PageLive`.
And it feches `:user_id` of `socket.assigns`.

```elixir
defmodule MyTestWeb.PageLive do
  use MyTestWeb, :live_view

  on_mount(MyTestWeb.UserLiveAuth)

  @impl true
  def mount(_params, _session, socket) do
    _user_id = socket.assigns.user_id

    {:ok, assign(socket, query: "", results: %{})}
  end

  ...
end
```

`MyTestWeb.UserLiveAuth` assigns `:user_id` to `socket` when `params` contains `"user_id"`.

```elixir
defmodule MyTestWeb.UserLiveAuth do
  import Phoenix.LiveView

  def mount(params, _session, socket) do
    socket =
      case params do
        %{"user_id" => user_id} ->
          assign_new(socket, :user_id, fn -> user_id end)

        _ ->
          socket
      end

    if socket.assigns[:user_id] do
      {:cont, socket}
    else
      {:halt, redirect(socket, to: "/login")}
    end
  end
end
```

When I access to `http://localhost:4000/?user_id=1`, it works.
When I access to `http://localhost:4000/`, it throws an error.

```
[error] #PID<0.459.0> running MyTestWeb.Endpoint (connection #PID<0.458.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (KeyError) key :user_id not found in: %{__changed__: %{}, flash: %{}, live_action: :index}
        (my_test 0.1.0) lib/my_test_web/live/page_live.ex:8: MyTestWeb.PageLive.mount/3
        (phoenix_live_view 0.16.2) lib/phoenix_live_view/utils.ex:300: anonymous fn/4 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/4
        (telemetry 0.4.3) /Users/json/workspace/temp/my_test/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
        (phoenix_live_view 0.16.2) lib/phoenix_live_view/static.ex:260: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.16.2) lib/phoenix_live_view/static.ex:110: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.16.2) lib/phoenix_live_view/controller.ex:35: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.5.12) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (my_test 0.1.0) lib/my_test_web/endpoint.ex:1: MyTestWeb.Endpoint.plug_builder_call/2
        (my_test 0.1.0) lib/plug/debugger.ex:136: MyTestWeb.Endpoint."call (overridable 3)"/2
        (my_test 0.1.0) lib/my_test_web/endpoint.ex:1: MyTestWeb.Endpoint.call/2
        (phoenix 1.5.12) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /Users/json/workspace/temp/my_test/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) /Users/json/workspace/temp/my_test/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) /Users/json/workspace/temp/my_test/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Expected behavior

Following the description of `attach_hook(socket, name, stage, fun)`(https://hexdocs.pm/phoenix_live_view/0.16.2/Phoenix.LiveView.html#attach_hook/4),
the LiveView callback will not be invoked when a hook returns `{:halt, socket}`.

As a hook attached by `on_mount/1` is also a hook, `mount/3` of `MyTestWeb.PageLive` shouldn't be called and it redirected to `/login` immediately.

**Comment by mcrumm** [comment]
@nallwhy Great catch! We made sure to validate the redirect redirect requirement on halt, but I left out the, "don't invoke the callback" bit 🙈
