### ISSUE TITLE
LiveViewTest.render_click passes modifier key metadata as strings

### ISSUE THREAD

**Issue by kerryb** [phoenixframework/phoenix_live_view#1613]
### Environment

* Elixir version (elixir -v): 1.12.2
* Phoenix version (mix deps): 1.6.0-rc.0
* Phoenix LiveView version (mix deps): 0.16.3
* Operating system: macOS 11.5.2 (20G95)
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I’ve created a [simple demo project](https://github.com/kerryb/shift_key_issue), but all relevant code is also included below.

I have a live view which responds differently to click events depending on modifier keys:

```elixir
defmodule ShiftKeyIssueWeb.FooLive do
  use Phoenix.LiveView

  def render(assigns) do
    ~H"""
    <a id="foo" phx-click="foo"><%= @label %></a>
    """
  end

  def mount(_params, _session, socket) do
    {:ok, assign(socket, label: "Shift-click me")}
  end

  def handle_event("foo", %{"shiftKey" => true}, socket) do
    {:noreply, assign(socket, label: "Thank you")}
  end
end

```

I Added the appropriate config in `app.js`, as covered in the bindings guide:

```javascript
let liveSocket = new LiveSocket("/live", Socket, {
  params: {_csrf_token: csrfToken},
  metadata: {
    click: (e, el) => {
      return {
        shiftKey: e.shiftKey
      }
    }
  }
})
```

This works as expected in the browser; the issue is when trying to test it using `render_click/2`:

```elixir
defmodule ShiftKeyIssueWeb.FooLiveTest do
  use ExUnit.Case
  import Phoenix.ConnTest
  import Phoenix.LiveViewTest
  @endpoint ShiftKeyIssueWeb.Endpoint

  test "shift click" do
    {:ok, view, _html} = build_conn() |> live("/")
    view |> element("#foo") |> render_click(%{"shiftKey" => true})
  end
end
```

```
14:35:53.679 [error] GenServer #PID<0.348.0> terminating
** (FunctionClauseError) no function clause matching in ShiftKeyIssueWeb.FooLive.handle_event/3
    (shift_key_issue 0.1.0) lib/shift_key_issue_web/live/foo_live.ex:14: ShiftKeyIssueWeb.FooLive.handle_event("foo", %{"shiftKey" => "true"}, #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, flash: %{}, label: "Shift-click me", live_action: :index}, endpoint: ShiftKeyIssueWeb.Endpoint, id: "phx-FqLcOUDX7EAAIgBD", parent_pid: nil, root_pid: #PID<0.348.0>, router: ShiftKeyIssueWeb.Router, transport_pid: #PID<0.347.0>, view: ShiftKeyIssueWeb.FooLive, ...>)
    (phoenix_live_view 0.16.3) lib/phoenix_live_view/channel.ex:349: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.0.0) /Users/kerry/dev/shift_key_issue/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
    (phoenix_live_view 0.16.3) lib/phoenix_live_view/channel.ex:206: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: 0, payload: %{"cid" => nil, "event" => "foo", "type" => "click", "value" => %{"shiftKey" => "true"}}, ref: "1", topic: "lv:phx-FqLcOUDX7EAAIgBD"}
14:35:53.722 [error] GenServer #PID<0.346.0> terminating
** (FunctionClauseError) no function clause matching in ShiftKeyIssueWeb.FooLive.handle_event/3
    (shift_key_issue 0.1.0) lib/shift_key_issue_web/live/foo_live.ex:14: ShiftKeyIssueWeb.FooLive.handle_event("foo", %{"shiftKey" => "true"}, #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, flash: %{}, label: "Shift-click me", live_action: :index}, endpoint: ShiftKeyIssueWeb.Endpoint, id: "phx-FqLcOUDX7EAAIgBD", parent_pid: nil, root_pid: #PID<0.348.0>, router: ShiftKeyIssueWeb.Router, transport_pid: #PID<0.347.0>, view: ShiftKeyIssueWeb.FooLive, ...>)
    (phoenix_live_view 0.16.3) lib/phoenix_live_view/channel.ex:349: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.0.0) /Users/kerry/dev/shift_key_issue/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
    (phoenix_live_view 0.16.3) lib/phoenix_live_view/channel.ex:206: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.345.0>, {:function_clause, [{ShiftKeyIssueWeb.FooLive, :handle_event, ["foo", %{"shiftKey" => "true"}, #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, flash: %{}, label: "Shift-click me", live_action: :index}, endpoint: ShiftKeyIssueWeb.Endpoint, id: "phx-FqLcOUDX7EAAIgBD", parent_pid: nil, root_pid: #PID<0.348.0>, router: ShiftKeyIssueWeb.Router, transport_pid: #PID<0.347.0>, view: ShiftKeyIssueWeb.FooLive, ...>], [file: 'lib/shift_key_issue_web/live/foo_live.ex', line: 14]}, {Phoenix.LiveView.Channel, :"-view_handle_event/3-fun-0-", 3, [file: 'lib/phoenix_live_view/channel.ex', line: 349]}, {:telemetry, :span, 3, [file: '/Users/kerry/dev/shift_key_issue/deps/telemetry/src/telemetry.erl', line: 293]}, {Phoenix.LiveView.Channel, :handle_info, 2, [file: 'lib/phoenix_live_view/channel.ex', line: 206]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 771]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}


  1) test shift click (ShiftKeyIssueWeb.FooLiveTest)
     test/shift_key_issue_web/live/foo_live_test.exs:7
     ** (EXIT from #PID<0.345.0>) an exception was raised:
     
          ** (FunctionClauseError) no function clause matching in ShiftKeyIssueWeb.FooLive.handle_event/3
     
          The following arguments were given to ShiftKeyIssueWeb.FooLive.handle_event/3:
          
              # 1
              "foo"
          
              # 2
              %{"shiftKey" => "true"}
          
              # 3
              #Phoenix.LiveView.Socket<assigns: %{__changed__: %{}, flash: %{}, label: "Shift-click me", live_action: :index}, endpoint: ShiftKeyIssueWeb.Endpoint, id: "phx-FqLcOUDX7EAAIgBD", parent_pid: nil, root_pid: #PID<0.348.0>, router: ShiftKeyIssueWeb.Router, transport_pid: #PID<0.347.0>, view: ShiftKeyIssueWeb.FooLive, ...>
          
          Attempted function clauses (showing 1 out of 1):
          
              def handle_event("foo", -%{"shiftKey" => true}-, socket)
          
          stacktrace:
            (shift_key_issue 0.1.0) lib/shift_key_issue_web/live/foo_live.ex:14: ShiftKeyIssueWeb.FooLive.handle_event/3
            (phoenix_live_view 0.16.3) lib/phoenix_live_view/channel.ex:349: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
            (telemetry 1.0.0) /Users/kerry/dev/shift_key_issue/deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
            (phoenix_live_view 0.16.3) lib/phoenix_live_view/channel.ex:206: Phoenix.LiveView.Channel.handle_info/2
            (stdlib 3.15.1) gen_server.erl:695: :gen_server.try_dispatch/4
            (stdlib 3.15.1) gen_server.erl:771: :gen_server.handle_msg/6
            (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
     



Finished in 0.3 seconds (0.00s async, 0.3s sync)
1 test, 1 failure

Randomized with seed 326605
```

Note that `render_click` sends the params as `%{"shiftKey" => "true"}` (string value), whereas an actual click in the browser sends them as `%{"shiftKey" => true}` (boolean value).

### Workaround

This can be solved by converting the values to strings at the javascript level:

```javascript
let liveSocket = new LiveSocket("/live", Socket, {
  params: {_csrf_token: csrfToken},
  metadata: {
    click: (e, el) => {
      return {
        shiftKey: e.shiftKey.toString()
      }
    }
  }
})
```

```elixir
  def handle_event("foo", %{"shiftKey" => "true"}, socket) do
    {:noreply, assign(socket, label: "Thank you")}
  end
```

### Expected behavior

Either modify `render_click/3` to pass values as-is, rather than converting them to strings (unlikely, as this would be a breaking change and the conversion is obviously done for a reason), or clarify in the documentation that the metadata values need to be passed from javascript as strings if you intend to test the event handler with `LiveViewTest.render_click/2`.

**Comment by kerryb** [comment]
Wow, that was quick! Thank you 🙏🏻
