### ISSUE TITLE
`render_upload` tests do not pass with phoenix 1.6.4

### ISSUE THREAD

**Issue by thenrio** [phoenixframework/phoenix_live_view#1794]
### Environment

* Elixir version (elixir -v): 1.12.2
* Phoenix version (mix deps): 1.6.4
* Phoenix LiveView version (mix deps): master, 0.16.4
* Operating system: debian sid

### Actual behavior

```
mix test test/phoenix_live_view/upload/channel_test.exs --max-failures 1

  1) test component with valid token render_upload with unknown entry (Phoenix.LiveView.UploadChannelTest)
     test/phoenix_live_view/upload/channel_test.exs:294
     ** (exit) exited in: GenServer.call(#PID<0.283.0>, {:allowed_ack, "phx-Fr9lWCKIWWzWjgIi", %{chunk_size: 20, max_entries: 3, max_file_size: 8000000}, [%{"content" => "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "name" => "foo.jpeg", "ref" => "579", "size" => 100, "type" => "image/jpeg"}], %{"579" => "SFMyNTY.g2gDaAJhBXQAAAADZAADY2lkYQFkAANwaWRYZAANbm9ub2RlQG5vaG9zdAAAARoAAAAAAAAAAGQAA3JlZmgCbQAAABRwaHgtRnI5bFdDS0lXV3pXamdJaW0AAAADNTc5bgYA6NZepH0BYgABUYA.dBzxBERJ7WHzurGaoBtrpOfZcsnGYnf24LHCdQyLVi8"}}, 5000)
         ** (EXIT) an exception was raised:
             ** (ArgumentError) fetch_test_supervisor!/0 can only be invoked from the test process
                 (phoenix 1.6.4) lib/phoenix/test/channel_test.ex:413: Phoenix.ChannelTest.fetch_test_supervisor!/0
                 (phoenix 1.6.4) lib/phoenix/test/channel_test.ex:388: anonymous fn/4 in Phoenix.ChannelTest.join/4
                 (phoenix 1.6.4) lib/phoenix/channel/server.ex:28: Phoenix.Channel.Server.join/4
                 (phoenix 1.6.4) lib/phoenix/test/channel_test.ex:391: Phoenix.ChannelTest.join/4
                 (phoenix_live_view 0.17.5) lib/phoenix_live_view/test/upload_client.ex:117: Phoenix.LiveViewTest.UploadClient.build_and_join_entry/3
                 (phoenix_live_view 0.17.5) lib/phoenix_live_view/test/upload_client.ex:59: anonymous fn/4 in Phoenix.LiveViewTest.UploadClient.handle_call/3
                 (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
                 (phoenix_live_view 0.17.5) lib/phoenix_live_view/test/upload_client.ex:56: Phoenix.LiveViewTest.UploadClient.handle_call/3
                 (stdlib 3.16.1) gen_server.erl:721: :gen_server.try_handle_call/4
                 (stdlib 3.16.1) gen_server.erl:750: :gen_server.handle_msg/6
                 (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
     code: assert UploadLive.exits_with(lv, avatar, RuntimeError, fn ->
     stacktrace:
       (elixir 1.12.2) lib/gen_server.ex:1024: GenServer.call/3
       (phoenix_live_view 0.17.5) lib/phoenix_live_view/test/live_view_test.ex:1717: Phoenix.LiveViewTest.render_upload/3
       (phoenix_live_view 0.17.5) test/support/live_views/upload_live.ex:62: Phoenix.LiveViewTest.UploadLive.exits_with/4
       test/phoenix_live_view/upload/channel_test.exs:300: (test)

--max-failures reached, aborting test suite

Finished in 1.3 seconds (1.3s async, 0.00s sync)
1 test, 1 failure

Randomized with seed 243205

```

### Expected behavior

```
mix test test/phoenix_live_view/upload/channel_test.exs --max-failures 1
```

should pass.

**Comment by thenrio** [comment]
I used

```
mix deps.update phoenix
```

to update `phoenix` dep.

**Comment by josevalim** [comment]
I pushed a fix but a new Phoenix release will be necessary. I am pushing to Phoenix soon.

**Comment by josevalim** [comment]
We will revert the change in Phoenix so v1.6.5 should go back to work without updating LiveView. But this fix is in place for when eventually release Phoenix v1.7.
