### ISSUE TITLE
For Comprehension with if conditional statements

### ISSUE THREAD

**Issue by qilongxu** [phoenixframework/phoenix_live_view#1994]
Updated liveview from 0.17.5 to 0.17.9, the for comprehension not working properly. 
The following code is working
<pre>
<%= for x <- 100..120 do %>
    <%= for i <- 1..6 do %>
            <%= i + x %>
    <% end %> 
<% end %>
</pre>
However, this one is not working (with if statement):
<pre>
<%= for x <- 100..120 do %>
    <%= for i <- 1..6 do %>
           <%= if i > 2 do %>
              <%= i + x %>
           <% else %>
              <%= i + x %>
           <% end %>
    <% end %> 
<% end %>
</pre>
And console log:
<pre>
Uncaught TypeError: Cannot read properties of undefined (reading '0') rendered.js:149 
    at Rendered.templateStatic (rendered.js:149:14)
    at Rendered.toOutputBuffer (rendered.js:158:20)
    at Rendered.dynamicToBuffer (rendered.js:186:12)
    at Rendered.comprehensionToBuffer (rendered.js:176:14)
    at Rendered.toOutputBuffer (rendered.js:156:41)
    at Rendered.dynamicToBuffer (rendered.js:186:12)
    at Rendered.comprehensionToBuffer (rendered.js:176:14)
    at Rendered.toOutputBuffer (rendered.js:156:41)
    at Rendered.dynamicToBuffer (rendered.js:186:12)
    at Rendered.toOutputBuffer (rendered.js:162:12)

and the js 149:
  templateStatic(part, templates){
    if(typeof (part) === "number") {
      **return templates[part]** (<-line 149)
    } else {
      return part
    }
  }
</pre>
Any idea?  Thanks

**Comment by josevalim** [comment]
Please delete the node_modules folder and install the client from scratch. Sometimes an old package version gets cached by npm.

**Comment by qilongxu** [comment]
Thank you!  After I removed the node_modules folder and changed es2015 to es2017 for esbuild,  it works well...
