### ISSUE TITLE
phx-click does not work on input type="range" on any Mobile browser

### ISSUE THREAD

**Issue by gabrielmancini** [phoenixframework/phoenix_live_view#2048]
### Environment

* Elixir version (elixir -v): Elixir 1.13.3 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): ~> 1.6.4
* Phoenix LiveView version (mix deps): ~> 0.17.5
* Operating system:  4.15.0-180-generic Ubuntu SMP Wed May 18 14:13:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome with device toolbar resposive in iphone se
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
I have a liveview screen with some cards and inside of each card i had some html inputs like input type=button and others, every component work as a expected in a desktop browser but the range component not fire the phx-click event when i change the responsive view in the browser to a mobile. 

here is the component
```
                <input 
                  type="range"
                  phx-click="ao" 
                  phx-value-bind={bind} 
                  phx-value-uuid={asset.uuid} 
                  phx-value-value={value} 
                  value={value} 
                  step="36"
                  min="0" 
                  max="252" 
                  disabled={asset.connected == :false or asset.loading == :true}
                  class="col-span-2 h-2 cursor-pointer"/> 
```

### Expected behavior
the range work in mobile like other components

**Comment by gabrielmancini** [comment]
@chrismccord i dont get it, there is a way to bind a `phx-change` on a input without using a form?

i just changed the click to change, but 
```
<input 
                  type="range"
                  phx-change="ao" 
                  phx-value-bind={bind} 
                  phx-value-uuid={asset.uuid} 
                  phx-value-value={value} 
                  value={value} 
                  step="36"
                  min="0" 
                  max="252" 
                  disabled={asset.connected == :false or asset.loading == :true}
                  class="col-span-2 h-2 cursor-pointer"/>    
```
but the chrome terminal complains about it
```
view.js:748 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at View.targetComponentID (view.js:748:32)
    at View.pushInput (view.js:829:49)
    at js.js:45:20
    at view.js:205:55
    at LiveSocket.owner (live_socket.js:391:15)
    at View.withinTargets (view.js:205:30)
    at Object.exec_push (js.js:40:10)
    at js.js:14:22
    at Array.forEach (<anonymous>)
    at js.js:13:40
```

i ask because i dont have any "virtual" model to interact with the form, if i understand correctly the form needs to have a changeset, but in my case, i create this screen on the fly. and i have no plans to using a form

**Comment by gabrielmancini** [comment]
nevermind, adding a form really solve the problem

for any future reference, and anybody who found this issue just change to something like that
change this
```
                <input 
                  type="range"
                  phx-click="ao" 
                  phx-value-bind={bind} 
                  phx-value-uuid={asset.uuid} 
                  phx-value-value={value} 
                  value={value} 
                  step="36"
                  min="0" 
                  max="252" 
                  disabled={asset.connected == :false or asset.loading == :true}
                  class="col-span-2 h-2 cursor-pointer"/> 
```
to this
```
            <form phx-change="ao">
                  <input type="hidden" name="bind" value={bind} />
                  <input type="hidden" name="uuid" value={asset.uuid} />
                  <input 
                    name="value"
                    type="range"
                    value={value} 
                    step="36"
                    min="0" 
                    max="252" 
                    disabled={asset.connected == :false or asset.loading == :true}
                    class="col-span-2 h-2 cursor-pointer"/> 
            </form>   
```
