### ISSUE TITLE
Nested module causes compile time error in register_component!/4

### ISSUE THREAD

**Issue by LostKobrakai** [phoenixframework/phoenix_live_view#2078]
### Environment

* Elixir version (elixir -v):
* Phoenix version (mix deps): 
* Phoenix LiveView version (mix deps): 
phoenix_live_view 0.18.0-dev (https://github.com/phoenixframework/phoenix_live_view.git) (mix)
  locked at 00e6984
* Operating system:
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

```elixir
defmodule DresserWeb.LayoutView do
  use DresserWeb, :view
  use Phoenix.Component

  defmodule NavItem do
    defstruct [:label, :href, :icon, active: false]

    def new(label, href, icon) do
      %__MODULE__{label: label, href: href, icon: icon}
    end

    def set_active(%__MODULE__{} = item) do
      %__MODULE__{item | active: true}
    end
  end

  …
end
```

This produces a compile time error:

```
== Compilation error in file lib/dresser_web/views/layout_view.ex ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir 1.13.4) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.13.4) lib/enum.ex:143: Enumerable.reduce/3
    (elixir 1.13.4) lib/enum.ex:4144: Enum.reverse/1
    (phoenix_live_view 0.18.0-dev) lib/phoenix_component.ex:1016: Phoenix.Component.pop_attrs/1
    (phoenix_live_view 0.18.0-dev) lib/phoenix_component.ex:880: Phoenix.Component.register_component!/4
    (phoenix_live_view 0.18.0-dev) expanding macro: Phoenix.Component.__pattern__!/2
    lib/dresser_web/views/layout_view.ex:17: DresserWeb.LayoutView.NavItem.set_active/1
```

### Expected behavior

No error.

**Comment by connorlay** [comment]
Thanks for the bug report! I was able to reproduce and fix the issue with https://github.com/phoenixframework/phoenix_live_view/pull/2079
