### ISSUE TITLE
Improve error message when an attribute is invalid

### ISSUE THREAD

**Issue by lkarthee** [phoenixframework/phoenix_live_view#2117]
### Environment

* Elixir version (elixir -v): Elixir 1.13.0 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.6.11
* Phoenix LiveView version (mix deps): 0.17.11
* Operating system: MacOS 12.3
* Browsers you attempted to reproduce this bug on (the more the merrier): NA
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
```elixir
#form_helpers.ex
defmodule AdminWeb.FormHelpers do
  use Phoenix.Component

  def modal_form_layout(assigns) do
    attributes = assigns_to_attributes(assigns, [:title, :class, :id, :changeset]) # slot :input should be included in list
    assigns = assign(assigns, :attributes, attributes)
    ~H"""
    <div class="py-4 px-2 sm:rounded-lg sm:px-10">
      <.form
        let={f}
        for={@changeset}
        id={@id}
        phx-change="validate"
        phx-submit="save"
        class={@class}
        {@attributes}>
        <%# <:input> slot logic to render input components %>
      </.form>
    </div>
    """
  end
end
```
```elixir
## some_form_component.html.heex
<div>
  <.modal_form_layout 
    title={@title} 
    changeset={@changeset} 
    phx_target={@myself} 
    id="some-form">
    <:input>Name</:input>
    <:input>Age</:input>
  </.modal_form_layout>
</div>
```

When a invalid attribute is passed to component, got a cryptic error message (see below):
- it does not contain corresponding {heex_file_name, line_no} from where the error is originating 
- gives a generic error message
- does not give any info about which component is actually causing this error (does not refer to `modal_form_layout` or `some_form_component.html.heex`)

```
** (exit) an exception was raised:
    ** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: %{__slot__: :input, inner_block: #Function<2.4717929/2 in AdminWeb.SomeFormComponent.render/1>}
        (phoenix_html 3.2.0) lib/phoenix_html/safe.ex:81: Phoenix.HTML.Safe.List.to_iodata/1
        (phoenix_html 3.2.0) lib/phoenix_html/safe.ex:49: Phoenix.HTML.Safe.List.to_iodata/1
        (phoenix_html 3.2.0) lib/phoenix_html.ex:255: Phoenix.HTML.build_attrs/1
        (phoenix_html 3.2.0) lib/phoenix_html.ex:225: Phoenix.HTML.build_attrs/1
        (phoenix_html 3.2.0) lib/phoenix_html.ex:228: Phoenix.HTML.build_attrs/1
        (phoenix_html 3.2.0) lib/phoenix_html.ex:255: Phoenix.HTML.build_attrs/1
        (phoenix_html 3.2.0) lib/phoenix_html.ex:208: Phoenix.HTML.attributes_escape/1
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/helpers.ex:1145: anonymous fn/2 in Phoenix.LiveView.Helpers.form/1
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:494: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:494: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:664: Phoenix.LiveView.Diff.render_component/9
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:609: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
        (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
        (stdlib 3.14) maps.erl:233: :maps.fold_1/3
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:582: Phoenix.LiveView.Diff.render_pending_components/6
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/diff.ex:145: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:244: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/static.ex:126: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.17.11) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.6.11) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
        (admin 0.1.0) lib/admin_web/endpoint.ex:1: AdminWeb.Endpoint.plug_builder_call/2
        (admin 0.1.0) lib/plug/debugger.ex:136: AdminWeb.Endpoint."call (overridable 3)"/2
        (admin 0.1.0) lib/admin_web/endpoint.ex:1: AdminWeb.Endpoint.call/2
        (phoenix 1.6.11) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) path_to/admin/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) path_to/admin/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) path_to/admin/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Expected behavior

- Include more Information about component which is causing this error along with file name and line no. 
- More descriptive error like
```(ArgumentError) invalid attribute passed to component <component_name> at <line_no> in file <file_name>``` 
rather than 
```
(ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: %{__slot__: :input, inner_block: #Function<2.4717929/2 in AdminWeb.SomeFormComponent.render/1>}
```

**Comment by josevalim** [comment]
Yeah, so the reason why this happens is because the error is actually coming from the form component. I.e. you pass your assigns to `form`, then `form` raises when emitting HEEx. Furthermore, because each `~H` is rendered lazily, we lose the stacktrace from the first component.

We can address though by passing the stacktrace to components. I will work on something.
