### ISSUE TITLE
Unable to provide both `include` and `default` opts for global attr

### ISSUE THREAD

**Issue by mulias** [phoenixframework/phoenix_live_view#2284]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.6.13
* Phoenix LiveView version (mix deps): 0.18.1
* Operating system: NixOS
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

Tried to compile this code:

```
  attr(:class, :string, default: nil)
  attr(:rest, :global, include: ["disabled"], default: %{type: "button"})
  slot(:inner_block, required: true)

  def styled_button(assigns) do
    ~H"""
    <button class={[@class, "btn", "my-other-classes"]} {@rest}>
      <%= render_slot(@inner_block) %>
    </button>
    """
  end
```

Results in this compiler error:
```
** (FunctionClauseError) no function clause matching in Phoenix.Component.Declarative.validate_attr_default!/6    
    
    The following arguments were given to Phoenix.Component.Declarative.validate_attr_default!/6:
    
        # 1
        nil
    
        # 2
        :rest
    
        # 3
        :global
    
        # 4
        [include: ["disabled"], default: %{type: "button"}]
    
        # 5
        <error line>
    
        # 6
        <my file>
    
    Attempted function clauses (showing 2 out of 2):
    
        defp validate_attr_default!(slot, name, _type, [default: default, values: values], line, file)
        defp validate_attr_default!(slot, name, type, [default: default], line, file)
    
    (phoenix_live_view 0.18.1) lib/phoenix_component/declarative.ex:414: Phoenix.Component.Declarative.validate_attr_default!/6
    (phoenix_live_view 0.18.1) lib/phoenix_component/declarative.ex:349: Phoenix.Component.Declarative.__attr__!/6
    <my file>
    (elixir 1.14.0) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected behavior

I should be able to specify additional global attrs and also set a default map.

**Comment by josevalim** [comment]
It has been fixed in master (maybe even 0.18.2)
