### ISSUE TITLE
Cannot format file through stdin

### ISSUE THREAD

**Issue by Sleepful** [phoenixframework/phoenix_live_view#2296]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 25)
```
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps):
```
      {:phoenix, "~> 1.6.13"},
      {:phoenix_ecto, "~> 4.4"},
      {:phoenix_html, "~> 3.0"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.17.5"},
```
* Operating system: OSX

My formatter.exs file:
```
[
  plugins: [Phoenix.LiveView.HTMLFormatter],
  import_deps: [:ecto, :phoenix],
  inputs: ["*.{ex,exs,heex}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs,heex}"],
  subdirectories: ["priv/*/migrations"]
]
```
### Actual behavior
```
$ cat new.html.heex | mix format --dot-formatter /project/.formatter.exs -
Skipping formatter plugin Phoenix.LiveView.HTMLFormatter because module cannot be found
** (Mix) Unknown dependency :ecto given to :import_deps in the formatter configuration. The dependency is not listed in your mix.exs for environment :dev
```

Mix format works fine if I just do `mix format`

### Expected behavior

Should format the file just like `mix format` does

**Comment by Sleepful** [comment]
running the formatter from the root of the project gives me a different error:

```
mix format failed for stdin
** (SyntaxError) stdin:1:1: syntax error before: '<'
    |
  1 | <h1>New Word</h1>
    | ^
    (elixir 1.13.4) lib/code.ex:737: Code.format_string!/2
    (mix 1.13.4) lib/mix/tasks/format.ex:548: Mix.Tasks.Format.elixir_format/2
    (mix 1.13.4) lib/mix/tasks/format.ex:564: Mix.Tasks.Format.format_file/2
    (elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    ```

looks like it isn't picking up the plugin for HEEX?

**Comment by Sleepful** [comment]
I was missing `--stdin-filename` and I was also missing 1.14.1 version for elixir/mix.

This works:
```
cat .../templates/word/new.html.heex | mix format --dot-formatter ./.formatter.exs --stdin-filename new.html.heex - > outputFilename
```
