### ISSUE TITLE
Error calling EEx.compile_string with function component

### ISSUE THREAD

**Issue by aselder** [phoenixframework/phoenix_live_view#2309]
### Environment

* Elixir version (elixir -v): 1.14.1
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.18.3
* Operating system: OS X Venutra
* Browsers you attempted to reproduce this bug on (the more the merrier):  N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

```
Mix.install([{:phoenix_live_view, "0.18.3"}])
defmodule Test do
  use Phoenix.Component

  def hello(assigns) do
  ~H"""
  Hello
  """
  end
end

EEx.compile_string("<Test.hello />", engine: Phoenix.LiveView.HTMLEngine)
```

gives the following error:

```
** (FunctionClauseError) no function clause matching in :elixir_aliases.expand/2

    The following arguments were given to :elixir_aliases.expand/2:

        # 1
        {:__aliases__, [], [:Test]}

        # 2
        nil

    (elixir 1.14.1) src/elixir_aliases.erl:44: :elixir_aliases.expand/2
    (elixir 1.14.1) src/elixir_aliases.erl:81: :elixir_aliases.expand_or_concat/2
    (elixir 1.14.1) lib/macro.ex:1772: Macro.do_expand_once/2
    (elixir 1.14.1) lib/macro.ex:2084: Macro.expand_until/2
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/html_engine.ex:395: Phoenix.LiveView.HTMLEngine.handle_token/2
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/html_engine.ex:168: Phoenix.LiveView.HTMLEngine.handle_body/1
    iex:6: (file)
```

### Expected behavior
A compiled AST is produced that can be processed with Code.eval_quoted(). 

This script works in LiveView 0.17, but breaks in 0.18

**Comment by josevalim** [comment]
You must pass `caller: __ENV__` as well. I will make sure the error surface earlier.

**Comment by aselder** [comment]
Thanks @josevalim
