### ISSUE TITLE
Undeclared function component attribute without "global" attribute raises exception

### ISSUE THREAD

**Issue by clarkware** [phoenixframework/phoenix_live_view#2320]
### Environment

* Elixir version (elixir -v): 1.14.1
* Phoenix version (mix deps): 1.7.0-rc.0
* Phoenix LiveView version (mix deps): 0.18.3

### Actual behavior

If a function component is declared to require an `inner_block` like so

```
 slot :inner_block, required: true

 def my_component(assigns) do
   ~H"""
     <%= render_slot(@inner_block) %>
   """
 end
```

and then the caller passes an `inner_block` _and_ an undeclared attribute (`message`, for example) like this

```elixir
<.my_component message="hello">
  Inner content
</.my_component>
```

the following compile-time exception is raised:

```
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (ArgumentError) argument error
        (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1091: anonymous fn/5 in Phoenix.Component.Declarative.verify/3
        (stdlib 4.1.1) maps.erl:411: :maps.fold_1/3
        (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1090: Phoenix.Component.Declarative.verify/3
        (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1034: anonymous fn/3 in Phoenix.Component.Declarative.__verify__/2
        (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1031: Phoenix.Component.Declarative.__verify__/2
        (elixir 1.14.1) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
        (elixir 1.14.1) lib/module/parallel_checker.ex:239: Module.ParallelChecker.check_module/2
```

The issue is related to the following comprehension on `lib/phoenix_component/declarative.ex:1091`:

```
for {name, {line, _column, _type_value}} <- attrs,
  not (global_attr && __global__?(caller_module, Atom.to_string(name), global_attr)) do
```

Changing it to explicitly check for `global_attr != nil` fixes the problem:

```
for {name, {line, _column, _type_value}} <- attrs,
  not ((global_attr != nil) && __global__?(caller_module, Atom.to_string(name), global_attr)) do
```

### Expected behavior

With the change noted above, you now get the expected warning:

```
warning: undefined attribute "message" for component LiveViewStudioWeb.CoreComponents.my_component/1
```

Happy to submit a PR if that change seems legit, though I don't quite understand why the `not` guard doesn't work as-is.

**Comment by josevalim** [comment]
A PR is very welcome!

`not` expects a boolean, the expression returns not a boolean, which your `!= nil` addresses. Alternatively, replace `not` by `!`. :)

**Comment by clarkware** [comment]
Ah-ha! Indeed, this works:

```
for {name, {line, _column, _type_value}} <- attrs,
        !(global_attr && __global__?(caller_module, Atom.to_string(name), global_attr)) do
```

I'll whip up a PR.  Thanks!  :-)
