### ISSUE TITLE
Random analyzer error of tailwind with content pseudo class conveniences

### ISSUE THREAD

**Issue by bryannaegele** [phoenixframework/phoenix_live_view#2324]
### Environment

* Elixir version (elixir -v): 1.14.1
* Phoenix version (mix deps): 1.16.11
* Phoenix LiveView version (mix deps): 0.18
* Operating system:
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

I came across a weird parsing error but can't see anything obvious that's causing it. This may be a Surface issue but starting here given the call that is failing is in the LV Engine and with Tailwind being included automatically now in Phoenix, this will probably come up.

Given this set of classes:

`<span class="ml-2 first:ml-0 after:content-[','] last:after:content-none"></span>`

This error is produced.

```
The following arguments were given to Phoenix.LiveView.Engine.analyze_list/5:
    
        # 1
        "&#39;"
    
        # 2
        {:restricted, %{}}
    
        # 3
        %{[:__context__] => true, ....}
    
        # 4
        nil
    
        # 5
        ["ml-2 first:ml-0 after:content-[", []]
    
    Attempted function clauses (showing 2 out of 2):
    
        defp analyze_list([31m[head | tail][0m, [22mvars[0m, [22massigns[0m, [22mcaller[0m, [22macc[0m)
        defp analyze_list([31m[][0m, [22mvars[0m, [22massigns[0m, [22m_caller[0m, [22macc[0m)
    
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:986: Phoenix.LiveView.Engine.analyze_list/5
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:987: Phoenix.LiveView.Engine.analyze_list/5
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:974: Phoenix.LiveView.Engine.analyze/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:987: Phoenix.LiveView.Engine.analyze_list/5
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:957: Phoenix.LiveView.Engine.analyze/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:987: Phoenix.LiveView.Engine.analyze_list/5
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:957: Phoenix.LiveView.Engine.analyze/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:987: Phoenix.LiveView.Engine.analyze_list/5
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:957: Phoenix.LiveView.Engine.analyze/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:974: Phoenix.LiveView.Engine.analyze/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:987: Phoenix.LiveView.Engine.analyze_list/5
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:1028: Phoenix.LiveView.Engine.analyze_with_restricted_vars/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:941: Phoenix.LiveView.Engine.analyze/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:987: Phoenix.LiveView.Engine.analyze_list/5
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:957: Phoenix.LiveView.Engine.analyze/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:987: Phoenix.LiveView.Engine.analyze_list/5
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:957: Phoenix.LiveView.Engine.analyze/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:987: Phoenix.LiveView.Engine.analyze_list/5
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:957: Phoenix.LiveView.Engine.analyze/4
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/engine.ex:974: Phoenix.LiveView.Engine.analyze/4
** (UndefinedFunctionError) function xxxxx.__required_props_names__/0 is undefined (module xxxxxx is not available)
    (xxxxx 0.1.0) xxxxx.__required_props_names__()
    (surface 0.9.1) lib/mix/tasks/compile/surface/validate_components.ex:39: Mix.Tasks.Compile.Surface.ValidateComponents.validate_properties/2
    (surface 0.9.1) lib/mix/tasks/compile/surface/validate_components.ex:19: anonymous fn/3 in Mix.Tasks.Compile.Surface.ValidateComponents.check_components_calls/1
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (surface 0.9.1) lib/mix/tasks/compile/surface/validate_components.ex:18: Mix.Tasks.Compile.Surface.ValidateComponents.check_components_calls/1
    (surface 0.9.1) lib/mix/tasks/compile/surface/validate_components.ex:9: anonymous fn/2 in Mix.Tasks.Compile.Surface.ValidateComponents.validate/1
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (surface 0.9.1) lib/mix/tasks/compile/surface/validate_components.ex:6: Mix.Tasks.Compile.Surface.ValidateComponents.validate/1
    (surface 0.9.1) lib/mix/tasks/compile/surface.ex:61: Mix.Tasks.Compile.Surface.run/1
    (mix 1.14.1) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (phoenix 1.6.15) lib/phoenix/code_reloader/server.ex:249: Phoenix.CodeReloader.Server.mix_compile/2
    (phoenix 1.6.15) lib/phoenix/code_reloader/server.ex:178: Phoenix.CodeReloader.Server.mix_compile/4
    (phoenix 1.6.15) lib/phoenix/code_reloader/server.ex:73: anonymous fn/3 in Phoenix.CodeReloader.Server.handle_call/3
    (phoenix 1.6.15) lib/phoenix/code_reloader/server.ex:286: Phoenix.CodeReloader.Server.proxy_io/1
    (phoenix 1.6.15) lib/phoenix/code_reloader/server.ex:71: Phoenix.CodeReloader.Server.handle_call/3
    (stdlib 4.1) gen_server.erl:1149: :gen_server.try_handle_call/4
    (stdlib 4.1) gen_server.erl:1178: :gen_server.handle_msg/6
    (stdlib 4.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

Templating in the comma in the content, however, does not trigger the error.

`<span class={"ml-2 first:ml-0 after:content-['#{","}'] last:after:content-none"}></span>`

### Expected behavior

Single quotes within a class string should not result in a parsing error.

**Comment by josevalim** [comment]
I cannot reproduce this error. Can you please provide a snippet that reproduces it? If it can be a single file live view app, even better!

**Comment by chrismccord** [comment]
If you have a reproducible error, please let us know. Thanks!
