### ISSUE TITLE
GenServer crashes when rendering a slot inside a :for on a component with `slot` on top but no `attr` on top

### ISSUE THREAD

**Issue by lubien** [phoenixframework/phoenix_live_view#2371]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Elixir 1.14.1 (compiled with Erlang/OTP 23)
```

* Phoenix version (mix deps):
```
* phoenix 1.7.0-rc.0 (Hex package) (mix)
  locked at 1.7.0-rc.0 (phoenix) ed503f6c
  ok
```

* Phoenix LiveView version (mix deps):
```
* phoenix_live_view 0.18.3 (Hex package) (mix)
  locked at 0.18.3 (phoenix_live_view) c8845177
  ok
```

* Operating system: Mac M1
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Say you have a component that receives a list prop and uses slots to render that list like this:

```elixir
~H"""
	<.bugged_component items={[1, 2, 3]}>
	  <:foo :let={x}><%= x %></:foo>
	</.bugged_component>
"""
```

If you declare that component as :

```elixir
def bugged_component(assigns) do
    ~H"""
    <div>
      <%= render_slot(@inner_block) %>
      <div :for={item <- @items}>
        <%= render_slot(@foo, item) %>
      </div>
    </div>
    """
  end
```

It works. But if you add a `slot` bit on top of it:

```elixir
  slot :foo

  def bugged_component(assigns) do
    ~H"""
    <div>
      <%= render_slot(@inner_block) %>
      <div :for={item <- @items}>
        <%= render_slot(@foo, item) %>
      </div>
    </div>
    """
  end
```

It will stop working with a not-so-helpful message

<img width="2005" alt="image" src="https://user-images.githubusercontent.com/9121359/209962740-01b1addd-c382-41cc-a425-2e23847b48cc.png">

```
[error] Process #PID<0.1182.0> raised an exception
** (ArgumentError) argument error
    (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1091: anonymous fn/5 in Phoenix.Component.Declarative.verify/3
    (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
    (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1090: Phoenix.Component.Declarative.verify/3
    (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1034: anonymous fn/3 in Phoenix.Component.Declarative.__verify__/2
    (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1031: Phoenix.Component.Declarative.__verify__/2
    (elixir 1.14.1) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir 1.14.1) lib/module/parallel_checker.ex:239: Module.ParallelChecker.check_module/2
    (elixir 1.14.1) lib/module/parallel_checker.ex:78: anonymous fn/5 in Module.ParallelChecker.spawn/3
[error] #PID<0.1154.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.1153.0>, stream id 1) terminated
Server: localhost:4001 (http)
Request: GET /
** (exit) exited in: GenServer.call(Phoenix.CodeReloader.Server, {:reload!, BugSlotWeb.Endpoint}, :infinity)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1091: anonymous fn/5 in Phoenix.Component.Declarative.verify/3
            (stdlib 3.15.2) maps.erl:410: :maps.fold_1/3
            (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1090: Phoenix.Component.Declarative.verify/3
            (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1034: anonymous fn/3 in Phoenix.Component.Declarative.__verify__/2
            (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
            (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:1031: Phoenix.Component.Declarative.__verify__/2
            (elixir 1.14.1) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir 1.14.1) lib/module/parallel_checker.ex:239: Module.ParallelChecker.check_module/2
            (elixir 1.14.1) lib/module/parallel_checker.ex:78: anonymous fn/5 in Module.ParallelChecker.spawn/3
```

You can make it work by adding an attr (before or after the `slot` doesn't matter) and it could be ANY attr, it doesn't need to be the missing `items` attr.

```elixir
  attr :anything, :string
  slot :foo

  def bugged_component(assigns) do
    ~H"""
    <div>
      <%= render_slot(@inner_block) %>
      <div :for={item <- @items}>
        <%= render_slot(@foo, item) %>
      </div>
    </div>
    """
  end
```

I've reproduced the bug on a repo for y'all, [here's the commit adding the bug](https://github.com/lubien/bug-liveview-slot-crashes-genserver/commit/4d991f87f268558e82d84e2cd8a2a9cd39743702) (the first commit is just default phoenix 1.7rc code)

### Expected behavior

Since the component works without the `slot` I think it should at least not crash a server

**Comment by alexjp** [comment]
Isn't this fixed on master phoenix and master liveview ?

I was getting an error similar to this, but updating to latest git versions seem to have fixed it.

**Comment by chrismccord** [comment]
Please check master and confirm, but I believe this is already addressed. Thanks!

**Comment by lubien** [comment]
Can confirm it's fixed!
