### ISSUE TITLE
key :myself not found in test with `render_component/2` for LiveComponent.

### ISSUE THREAD

**Issue by simonelnahas** [phoenixframework/phoenix_live_view#2382]
### Environment

* Elixir version (elixir -v): 1.14.2
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.18.3
* Operating system: MacOS 12.6

### Actual behavior

Similar to #818

I run this test inside a test:
```elixir
defmodule GIWeb.Components.Organisms.FooTest do
  use GIWeb.ConnCase, async: true
  import Phoenix.LiveViewTest
  alias GIWeb.Components.Organisms.ManagerTable

  describe "Foo component" do
    test "render Foo component" do
      render_component(GIWeb.Components.Organisms.Foo)
    end
  end
end
```
for this component:
```elixir
defmodule GIWeb.Components.Organisms.Foo do
  use GIWeb, :live_component

  def render(assigns) do
    ~H"""
    <div phx-target={@myself} phx-click="Foo">
      <p>Foo</p>
    </div>
    """
  end
end
```

and I get this error:

```elixir
  1) test Foo component render Foo component (GIWeb.Components.Organisms.FooTest)
     test/green_island_web/live/components/organisms/foo_test.exs:7
     ** (KeyError) key :myself not found in: %{__changed__: %{}, flash: %{}, socket: #Phoenix.LiveView.Socket<id: nil, endpoint: GIWeb.Endpoint, view: nil, parent_pid: nil, root_pid: nil, router: nil, assigns: #Phoenix.LiveView.Socket.AssignsNotInSocket<>, transport_pid: nil, ...>}
     code: render_component(GIWeb.Components.Organisms.Foo)
     stacktrace:
       (green_island 0.1.0) lib/green_island_web/live/components/organisms/random.ex:6: anonymous fn/2 in GIWeb.Components.Organisms.Foo.render/1
       (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:387: Phoenix.LiveView.Diff.traverse/7
       (phoenix_live_view 0.18.3) lib/phoenix_live_view/diff.ex:138: Phoenix.LiveView.Diff.render/3
       (phoenix_live_view 0.18.3) lib/phoenix_live_view/test/live_view_test.ex:494: Phoenix.LiveViewTest.rendered_to_diff_string/2
       test/green_island_web/live/components/organisms/foo_test.exs:8: (test)
```

### Expected behavior
I should be able to use `@myself` in a LiveComponent and test it with `render_component/2` https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#module-testing-livecomponents

**Comment by josevalim** [comment]
@myself is only included if you pass an `:id`. But even then, I am not sure if we include one because if you need it, you would likely pass it in to be deterministic.

**Comment by simonelnahas** [comment]
Thanks for the quick response. 
I can confirm it works, when I pass in the id:
```
defmodule GIWeb.Components.Organisms.FooTest do
  use GIWeb.ConnCase, async: true
  import Phoenix.LiveViewTest
  alias GIWeb.Components.Organisms.ManagerTable

  describe "Foo component" do
    test "render Foo component" do
      render_component(GIWeb.Components.Organisms.Foo, id: "foo")
    end
  end
end
```
