### ISSUE TITLE
cancel_upload/3 with existing ref raise an error that ref doesn't exists

### ISSUE THREAD

**Issue by maslowalex** [phoenixframework/phoenix_live_view#2402]
### Environment

* Elixir version `Elixir 1.14.0 (compiled with Erlang/OTP 25)`:
* Phoenix version `phoenix 1.6.15`:
* Phoenix LiveView version `phoenix_live_view 0.18.7`:
* Operating system: macOS BigSur
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave (chromium)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
I got this code, that attempts to call `cancel_upload` to remove the actual upload from socket:
```elixir
  defp handle_remove_image(_, socket) do
    dbg(uploaded_entries(socket, :image))

    cancel_upload(socket, :image, socket.assigns.uploads.image.ref)

    socket
  end
```

Here is the output:
```
[(quiz_arena 0.1.0) lib/quiz_arena_web/live/quiz_live/steps/second.ex:264: QuizArenaWeb.QuizLive.Steps.Second.handle_remove_image/2]
uploaded_entries(socket, :image) #=> {[],
 [
   %Phoenix.LiveView.UploadEntry{
     progress: 0,
     preflighted?: false,
     upload_config: :image,
     upload_ref: "phx-FzremWHAVqebvs5G",
     ref: "0",
     uuid: nil,
     valid?: false,
     done?: false,
     cancelled?: false,
     client_name: "Screenshot 2023-01-13 at 14.54.32.png",
     client_relative_path: "",
     client_size: 23723,
     client_type: "image/png",
     client_last_modified: 1673614475897
   }
 ]}

[error] GenServer #PID<0.8700.0> terminating
** (ArgumentError) no entry in upload ":image" with ref "phx-FzremWHAVqebvs5G"
    (phoenix_live_view 0.18.7) lib/phoenix_live_view/upload.ex:82: Phoenix.LiveView.Upload.cancel_upload/3
    (quiz_arena 0.1.0) lib/quiz_arena_web/live/quiz_live/steps/second.ex:266: QuizArenaWeb.QuizLive.Steps.Second.handle_remove_image/2
    (quiz_arena 0.1.0) lib/quiz_arena_web/live/quiz_live/steps/second.ex:125: QuizArenaWeb.QuizLive.Steps.Second.handle_event/3
    (phoenix_live_view 0.18.7) lib/phoenix_live_view/channel.ex:618: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.2.1) /Users/thunderbook/Work/quiz_arena/quiz_arena/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.18.7) lib/phoenix_live_view/diff.ex:206: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.18.7) lib/phoenix_live_view/channel.ex:541: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-FzremVIC5fbXdBth", event: "event", payload: %{"cid" => 1, "event" => "remove-image", "type" => "hook", "value" => %{}}, ref: "11", join_ref: "4"}
```

You can clearly see, that it says that entry is not exists, while you can also see that exact reference in the `uploaded_entries/2` output.

**Am I doing something wrong here?**
Please let me know, if I can help with additional info, or anything else.

### Expected behavior
I believe it should remove the upload from socket correctly.

**Comment by chrismccord** [comment]
You are passing the upload's ref, where `canel_upload` accepts the upload **entry**. So you either way to render the entry ref on the client and pass it up as a param, or get it from the `upload_entries` call.
The guides have an example here:
https://hexdocs.pm/phoenix_live_view/uploads.html#upload-entries

Thanks!
