### ISSUE TITLE
Formatter crashing with html comments

### ISSUE THREAD

**Issue by joaopsramos** [phoenixframework/phoenix_live_view#2466]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): 1.6.15
* Phoenix LiveView version (mix deps): 0.18.8
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier):  -
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: -

### Actual behavior
When running `mix format`, it crashes after reaching a file with the following content:
```heex
<!--
  <button class="btn">
        <img src={Routes.static_path(@socket, "/images/icons/icon-box.svg") }> <span><%= gettext "Catalog"%></span>
  </button>
-->
```
Removing the `<%= ... %>` tag makes it work
Using the comment tag `<%!-- --%>` it works as expected

The error stacktrace:
```
(phoenix_live_view 0.18.8) lib/phoenix_live_view/html_formatter.ex:419: Phoenix.LiveView.HTMLFormatter.to_tree/4
(phoenix_live_view 0.18.8) lib/phoenix_live_view/html_formatter.ex:233: Phoenix.LiveView.HTMLFormatter.format/2
(mix 1.14.0) lib/mix/tasks/format.ex:573: Mix.Tasks.Format.format_file/2
(elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
(elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
(stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

The complete error is too big, if necessary I can put it here

### Expected behavior
Ignore the entire file or format comments as if they were the new tag

**Comment by feliperenan** [comment]
hi @joaopsramos 

I couldn't reproduce it with the markup you provided. Would you mind sending the whole template or a sample project that reproduces this issue?

**Comment by joaopsramos** [comment]
Hi @feliperenan, my bad, that snippet really wasn't enough

I managed to reproduce now with the code below
```heex
<!--
<button class="btn">
  <img src={Routes.static_path(@socket, "/images/icons/icon-box.svg") }> <span><%= gettext "Catalog"%></span>
</button>
-->

<!--
<button class="btn px-2">
  <img class="mx-0" src={Routes.static_path(@socket, "/images/icons/icon-download.svg") }>
</button>
-->
```

The entire output:
```
** (FunctionClauseError) no function clause matching in Phoenix.LiveView.HTMLFormatter.to_tree/4    
    
    The following arguments were given to Phoenix.LiveView.HTMLFormatter.to_tree/4:
    
        # 1
        []
    
        # 2
        [{:text, "</span>\n</button>\n-->\n\n<!--\n<button class=\"btn px-2\">\n  <img class=\"mx-0\" src={Routes.static_path(@socket, \"/images/icons/icon-download.svg\") }>\n</button>\n-->\n", %{newlines: 0}}, {:eex, "gettext \"Catalog\"", %{column: 80, line: 3, opt: '='}}]
    
        # 3
        [{:comment, "<!--\n<button class=\"btn\">\n  <img src={Routes.static_path(@socket, \"/images/icons/icon-box.svg\") }> <span>", []}]
    
        # 4
        {"<!--\n<button class=\"btn\">\n  <img src={Routes.static_path(@socket, \"/images/icons/icon-box.svg\") }> <span><%= gettext \"Catalog\"%></span>\n</button>\n-->\n\n<!--\n<button class=\"btn px-2\">\n  <img class=\"mx-0\" src={Routes.static_path(@socket, \"/images/icons/icon-download.svg\") }>\n</button>\n-->\n", [{4, 1}, {25, 1}, {135, 1}, {145, 1}, {149, 1}, {150, 1}, {155, 1}, {181, 1}, {272, 1}, {282, 1}, {286, 1}]}
    
    Attempted function clauses (showing 10 out of 17):
    
        defp to_tree([], buffer, [], _source)
        defp to_tree([], _buffer, [{name, _, %{line: line, column: column}, _} | _], _source)
        defp to_tree([{:text, text, %{context: [:comment_start]}} | tokens], buffer, stack, source)
        defp to_tree([{:text, text, %{context: [:comment_end]}} | tokens], buffer, [{:comment, start_text, upper_buffer} | stack], source)
        defp to_tree([{:text, text, %{context: [:comment_start, :comment_end]}} | tokens], buffer, stack, source)
        defp to_tree([{:text, text, _meta} | tokens], buffer, stack, source)
        defp to_tree([{:eex_comment, text, _meta} | tokens], buffer, stack, source)
        defp to_tree([{:tag_open, name, attrs, %{self_close: true}} | tokens], buffer, stack, source)
        defp to_tree([{:tag_open, name, attrs, _meta} | tokens], buffer, stack, source) when name === "area" or name === "base" or name === "br" or name === "col" or name === "hr" or name === "img" or name === "input" or name === "link" or name === "meta" or name === "param" or name === "command" or name === "keygen" or name === "source"
        defp to_tree([{:tag_open, name, attrs, meta} | tokens], buffer, stack, source)
        ...
        (7 clauses not shown)
    
    (phoenix_live_view 0.18.8) lib/phoenix_live_view/html_formatter.ex:419: Phoenix.LiveView.HTMLFormatter.to_tree/4
    (phoenix_live_view 0.18.8) lib/phoenix_live_view/html_formatter.ex:233: Phoenix.LiveView.HTMLFormatter.format/2
    (mix 1.14.0) lib/mix/tasks/format.ex:573: Mix.Tasks.Format.format_file/2
    (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
