### ISSUE TITLE
mix phx.new does not generate valid project in umbrella application

### ISSUE THREAD

**Issue by jnnks** [phoenixframework/phoenix_live_view#2471]
I am using `phx_new 1.7.0-rc.0` to generate two applications, one standalone and another inside an existing umbrella applications `apps` directory.
When generating the liveview project in the umbrella app, I cannot start the server:
```
Erlang/OTP 24 [erts-12.3.2.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
[...]
 
20:00:57.855 [warning] esbuild version is not configured. Please set it in your config files:

    config :esbuild, :version, "0.16.4"

 
20:00:57.857 [warning] tailwind version is not configured. Please set it in your config files:

    config :tailwind, :version, "3.2.4"

 
20:00:57.862 [error] Could not find hackney dependency.

Please add :hackney to your dependencies:

    {:hackney, "~> 1.9"}

Or set your own Swoosh.ApiClient:

    config :swoosh, :api_client, MyAPIClient

 
20:00:57.862 [notice] Application swoosh exited: exited in: Swoosh.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) missing hackney dependency
            (swoosh 1.9.1) lib/swoosh/api_client/hackney.ex:26: Swoosh.ApiClient.Hackney.init/0
            (swoosh 1.9.1) lib/swoosh/api_client.ex:42: Swoosh.ApiClient.init/0
            (swoosh 1.9.1) lib/swoosh/application.ex:7: Swoosh.Application.start/2
            (kernel 8.3.2.3) application_master.erl:293: :application_master.start_it_old/4
 
20:00:57.867 [notice] Application jason exited: :stopped

20:00:57.867 [notice] Application xmerl exited: :stopped
 
20:00:57.868 [notice] Application tailwind exited: :stopped
 
20:00:57.869 [notice] Application esbuild exited: :stopped
 
20:00:57.870 [notice] Application phoenix_live_dashboard exited: :stopped
 
20:00:57.870 [notice] Application telemetry_metrics exited: :stopped
 
20:00:57.870 [notice] Application heroicons exited: :stopped
 
20:00:57.871 [notice] Application phoenix_live_view exited: :stopped
 
20:00:57.872 [notice] Application phoenix_live_reload exited: :stopped
 
20:00:57.872 [notice] Application file_system exited: :stopped
 
20:00:57.872 [notice] Application phoenix_html exited: :stopped
 
20:00:57.873 [notice] Application postgrex exited: :stopped
 
20:00:57.874 [notice] Application ecto_sql exited: :stopped
 
20:00:57.874 [notice] Application db_connection exited: :stopped
 
20:00:57.874 [notice] Application connection exited: :stopped
 
20:00:57.875 [notice] Application phoenix_ecto exited: :stopped
 
20:00:57.876 [notice] Application ecto exited: :stopped
 
20:00:57.876 [notice] Application decimal exited: :stopped
 
20:00:57.877 [notice] Application phoenix exited: :stopped
 
20:00:57.877 [notice] Application castore exited: :stopped

20:00:57.877 [notice] Application websock_adapter exited: :stopped
 
20:00:57.877 [notice] Application websock exited: :stopped
 
20:00:57.877 [notice] Application phoenix_template exited: :stopped
 
20:00:57.878 [notice] Application phoenix_pubsub exited: :stopped
 
20:00:57.878 [notice] Application plug exited: :stopped
 
20:00:57.879 [notice] Application telemetry exited: :stopped
 
20:00:57.880 [notice] Application plug_crypto exited: :stopped
 
20:00:57.880 [notice] Application mime exited: :stopped
 
20:00:57.880 [notice] Application eex exited: :stopped
 
20:00:57.881 [notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application swoosh: exited in: Swoosh.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) missing hackney dependency
            (swoosh 1.9.1) lib/swoosh/api_client/hackney.ex:26: Swoosh.ApiClient.Hackney.init/0
            (swoosh 1.9.1) lib/swoosh/api_client.ex:42: Swoosh.ApiClient.init/0
            (swoosh 1.9.1) lib/swoosh/application.ex:7: Swoosh.Application.start/2
            (kernel 8.3.2.3) application_master.erl:293: :application_master.start_it_old/4
```

Everything works well when not using an umbrella application.

**Comment by josevalim** [comment]
Thanks for the report. Can you please provide the exact steps to reproduce with the latest RC? Like mix new —umbrella and then the steps for the standalone apps.

**Comment by jnnks** [comment]
using `Elixir 1.15.0-dev (0800222) (compiled with Erlang/OTP 25)`
installed with `mix archive.install hex phx_new 1.7.0-rc.3`

____

## Umbrella Application (does not work)
<details>
<summary>mix new umbrella --umbrella</summary>

```
* creating README.md
* creating .formatter.exs
* creating .gitignore
* creating mix.exs
* creating apps
* creating config
* creating config/config.exs

Your umbrella project was created successfully.
Inside your project, you will find an apps/ directory
where you can create and host many apps:

    cd umbrella
    cd apps
    mix new my_app

Commands like "mix compile" and "mix test" when executed
in the umbrella project root will automatically run
for each application in the apps/ directory.
```

</details>

<details>
<summary>cd umbrella/apps/</summary>

</details>

<details>
<summary>umbrella/apps$ mix phx.new test --no-ecto</summary>

```
* creating test/config/config.exs
* creating test/config/dev.exs
* creating test/config/prod.exs
* creating test/config/runtime.exs
* creating test/config/test.exs
* creating test/lib/test/application.ex
* creating test/lib/test.ex
* creating test/lib/test_web/controllers/error_json.ex
* creating test/lib/test_web/endpoint.ex
* creating test/lib/test_web/router.ex
* creating test/lib/test_web/telemetry.ex
* creating test/lib/test_web.ex
* creating test/mix.exs
* creating test/README.md
* creating test/.formatter.exs
* creating test/.gitignore
* creating test/test/support/conn_case.ex
* creating test/test/test_helper.exs
* creating test/test/test_web/controllers/error_json_test.exs
* creating test/lib/test_web/controllers/error_html.ex
* creating test/test/test_web/controllers/error_html_test.exs
* creating test/lib/test_web/components/core_components.ex
* creating test/lib/test_web/controllers/page_controller.ex
* creating test/lib/test_web/controllers/page_html.ex
* creating test/lib/test_web/controllers/page_html/home.html.heex
* creating test/test/test_web/controllers/page_controller_test.exs
* creating test/lib/test_web/components/layouts/root.html.heex
* creating test/lib/test_web/components/layouts/app.html.heex
* creating test/lib/test_web/components/layouts.ex
* creating test/assets/vendor/topbar.js
* creating test/lib/test/mailer.ex
* creating test/lib/test_web/gettext.ex
* creating test/priv/gettext/en/LC_MESSAGES/errors.po
* creating test/priv/gettext/errors.pot
* creating test/assets/css/app.css
* creating test/assets/js/app.js
* creating test/assets/tailwind.config.js
* creating test/priv/static/robots.txt
* creating test/priv/static/favicon.ico

Fetch and install dependencies? [Yn] 
* running mix deps.get
* running mix assets.setup
* running mix deps.compile

We are almost there! The following steps are missing:

    $ cd test

Start your Phoenix app with:

    $ mix phx.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phx.server
```

</details>




<details>
<summary>umbrella/apps$ cd test/</summary>
</details>


<details>
<summary>umbrella/apps/test$ iex -S mix phx.server</summary>

```
Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Compiling 14 files (.ex)
Generated test app

20:46:39.560 [error] `inotify-tools` is needed to run `file_system` for your system, check https://github.com/rvoicilas/inotify-tools/wiki for more information about how to install it. If it's already installed but not be found, appoint executable file with `config.exs` or `FILESYSTEM_FSINOTIFY_EXECUTABLE_FILE` env.

20:46:39.560 [warning] Could not start Phoenix live-reload because we cannot listen to the file system.
You don't need to worry! This is an optional feature used during development to
refresh your browser when you save files and it does not affect production.


20:46:39.585 [warning] esbuild version is not configured. Please set it in your config files:

    config :esbuild, :version, "0.16.4"


20:46:39.590 [warning] tailwind version is not configured. Please set it in your config files:

    config :tailwind, :version, "3.2.4"


20:46:40.316 [error] Could not find hackney dependency.

Please add :hackney to your dependencies:

    {:hackney, "~> 1.9"}

Or set your own Swoosh.ApiClient:

    config :swoosh, :api_client, MyAPIClient


20:46:40.317 [notice] Application swoosh exited: exited in: Swoosh.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) missing hackney dependency
            (swoosh 1.9.1) lib/swoosh/api_client/hackney.ex:26: Swoosh.ApiClient.Hackney.init/0
            (swoosh 1.9.1) lib/swoosh/api_client.ex:42: Swoosh.ApiClient.init/0
            (swoosh 1.9.1) lib/swoosh/application.ex:7: Swoosh.Application.start/2
            (kernel 8.5.3) application_master.erl:293: :application_master.start_it_old/4

20:46:40.323 [notice] Application finch exited: :stopped

20:46:40.323 [notice] Application nimble_options exited: :stopped

20:46:40.324 [notice] Application nimble_pool exited: :stopped

20:46:40.324 [notice] Application mint exited: :stopped

20:46:40.324 [notice] Application hpax exited: :stopped

20:46:40.324 [notice] Application xmerl exited: :stopped

20:46:40.325 [notice] Application tailwind exited: :stopped

20:46:40.325 [notice] Application esbuild exited: :stopped

20:46:40.325 [notice] Application phoenix_live_dashboard exited: :stopped

20:46:40.325 [notice] Application telemetry_metrics exited: :stopped

20:46:40.325 [notice] Application heroicons exited: :stopped

20:46:40.326 [notice] Application phoenix_live_view exited: :stopped

20:46:40.326 [notice] Application phoenix_live_reload exited: :stopped

20:46:40.326 [notice] Application file_system exited: :stopped

20:46:40.327 [notice] Application phoenix exited: :stopped

20:46:40.327 [notice] Application jason exited: :stopped

20:46:40.327 [notice] Application castore exited: :stopped

20:46:40.327 [notice] Application websock_adapter exited: :stopped

20:46:40.328 [notice] Application plug_cowboy exited: :stopped

20:46:40.328 [notice] Application cowboy_telemetry exited: :stopped

20:46:40.328 [notice] Application cowboy exited: :stopped

20:46:40.329 [notice] Application ranch exited: :stopped

20:46:40.329 [notice] Application cowlib exited: :stopped

20:46:40.329 [notice] Application websock exited: :stopped

20:46:40.329 [notice] Application phoenix_template exited: :stopped

20:46:40.329 [notice] Application phoenix_html exited: :stopped

20:46:40.329 [notice] Application phoenix_pubsub exited: :stopped

20:46:40.330 [notice] Application plug exited: :stopped

20:46:40.330 [notice] Application telemetry exited: :stopped

20:46:40.330 [notice] Application plug_crypto exited: :stopped

20:46:40.330 [notice] Application mime exited: :stopped

20:46:40.330 [notice] Application eex exited: :stopped

20:46:40.331 [notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application swoosh: exited in: Swoosh.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (RuntimeError) missing hackney dependency
            (swoosh 1.9.1) lib/swoosh/api_client/hackney.ex:26: Swoosh.ApiClient.Hackney.init/0
            (swoosh 1.9.1) lib/swoosh/api_client.ex:42: Swoosh.ApiClient.init/0
            (swoosh 1.9.1) lib/swoosh/application.ex:7: Swoosh.Application.start/2
            (kernel 8.5.3) application_master.erl:293: :application_master.start_it_old/4
```

</details>

____

# Standalone Application (works)
<details>
<summary>mix phx.new ph_test --no-ecto</summary>

```
* creating ph_test/config/config.exs
* creating ph_test/config/dev.exs
* creating ph_test/config/prod.exs
* creating ph_test/config/runtime.exs
* creating ph_test/config/test.exs
* creating ph_test/lib/ph_test/application.ex
* creating ph_test/lib/ph_test.ex
* creating ph_test/lib/ph_test_web/controllers/error_json.ex
* creating ph_test/lib/ph_test_web/endpoint.ex
* creating ph_test/lib/ph_test_web/router.ex
* creating ph_test/lib/ph_test_web/telemetry.ex
* creating ph_test/lib/ph_test_web.ex
* creating ph_test/mix.exs
* creating ph_test/README.md
* creating ph_test/.formatter.exs
* creating ph_test/.gitignore
* creating ph_test/test/support/conn_case.ex
* creating ph_test/test/test_helper.exs
* creating ph_test/test/ph_test_web/controllers/error_json_test.exs
* creating ph_test/lib/ph_test_web/controllers/error_html.ex
* creating ph_test/test/ph_test_web/controllers/error_html_test.exs
* creating ph_test/lib/ph_test_web/components/core_components.ex
* creating ph_test/lib/ph_test_web/controllers/page_controller.ex
* creating ph_test/lib/ph_test_web/controllers/page_html.ex
* creating ph_test/lib/ph_test_web/controllers/page_html/home.html.heex
* creating ph_test/test/ph_test_web/controllers/page_controller_test.exs
* creating ph_test/lib/ph_test_web/components/layouts/root.html.heex
* creating ph_test/lib/ph_test_web/components/layouts/app.html.heex
* creating ph_test/lib/ph_test_web/components/layouts.ex
* creating ph_test/assets/vendor/topbar.js
* creating ph_test/lib/ph_test/mailer.ex
* creating ph_test/lib/ph_test_web/gettext.ex
* creating ph_test/priv/gettext/en/LC_MESSAGES/errors.po
* creating ph_test/priv/gettext/errors.pot
* creating ph_test/assets/css/app.css
* creating ph_test/assets/js/app.js
* creating ph_test/assets/tailwind.config.js
* creating ph_test/priv/static/robots.txt
* creating ph_test/priv/static/images/phoenix.png
* creating ph_test/priv/static/favicon.ico

Fetch and install dependencies? [Yn] 
* running mix deps.get
* running mix deps.compile

We are almost there! The following steps are missing:

    $ cd ph_test

Start your Phoenix app with:

    $ mix phx.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phx.server
```

</details>

<details>
<summary>cd ph_test/</summary>

</details>


<details>
<summary>ph_test$ iex -S mix phx.server</summary>

```
Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Compiling 14 files (.ex)
Generated ph_test app
[error] `inotify-tools` is needed to run `file_system` for your system, check https://github.com/rvoicilas/inotify-tools/wiki for more information about how to install it. If it's already installed but not be found, appoint executable file with `config.exs` or `FILESYSTEM_FSINOTIFY_EXECUTABLE_FILE` env.
[warning] Could not start Phoenix live-reload because we cannot listen to the file system.
You don't need to worry! This is an optional feature used during development to
refresh your browser when you save files and it does not affect production.

[info] Running PhTestWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)
[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.1.8/tailwindcss-linux-x64
[info] Access PhTestWeb.Endpoint at http://localhost:4000
[debug] Downloading esbuild from https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.14.41.tgz
Interactive Elixir (1.15.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> [watch] build finished, watching for changes...
[watch] build started (change: "js/app.js")
[watch] build finished
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

Rebuilding...
Done in 373ms.
```

</details>

____

`mix phx.new phoenix_umbrella --umbrella` does not work on rc.0 either, but now works with rc.3
