### ISSUE TITLE
no function clause matching error when auto recovering a form with different phx-target

### ISSUE THREAD

**Issue by kelsonire** [phoenixframework/phoenix_live_view#2583]
### Environment

* Elixir version (elixir -v): Elixir 1.14.0
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: macOS Ventura
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome/Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

If the input tag in the form has a phx-target that is different from the event target of the form itself, auto-recover will not work properly and the reconnection process will fail.
An error caused an infinite loop in the LiveView below.

```elixir
defmodule MyAppWeb.PageLive do
  use MyAppWeb, :live_view

  def render(assigns) do
    ~H"""
    <.live_component id="my-form" module={MyForm} />
    """
  end

  def handle_event("change", _, socket) do
    {:noreply, socket}
  end
end

defmodule MyForm do
  use MyAppWeb, :live_component

  def render(assigns) do
    ~H"""
    <form phx-change="change">
      <input phx-keyup="keyup" phx-target={@myself} />
    </form>
    """
  end

  def handle_event("keyup", _, socket) do
    {:noreply, socket}
  end
end
```

I reproduced the disconnect and reconnect with `liveSocket.disconnect(); setTimeout(() => {liveSocket.connect()}, 500);` in Chrome console.

And errors like this.

```
[error] GenServer #PID<0.4508.0> terminating
** (FunctionClauseError) no function clause matching in MyForm.handle_event/3
    (my_app 0.1.0) lib/my_app_web/live/page_live.ex:26: MyForm.handle_event("change", %{"_target" => ["undefined"]}, #Phoenix.LiveView.Socket<id: "phx-F1Td_XjOm7vSV1UG", endpoint: MyAppWeb.Endpoint, view: MyAppWeb.PageLive, parent_pid: nil, root_pid: #PID<0.4508.0>, router: MyAppWeb.Router, assigns: %{__changed__: %{}, flash: %{}, id: "my-form", myself: %Phoenix.LiveComponent.CID{cid: 1}}, transport_pid: #PID<0.4499.0>, ...>)
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:630: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.2.1) /*******/my_app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:207: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.18.18) lib/phoenix_live_view/channel.ex:553: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 4.1) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.1) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F1Td_XjOm7vSV1UG", event: "event", payload: %{"cid" => 1, "event" => "change", "type" => "form", "uploads" => %{}, "value" => "_target=undefined"}, ref: "20", join_ref: "19"}
State: %{components: {%{1 => {MyForm, "my-form", %{__changed__: %{}, flash: %{}, id: "my-form", myself: %Phoenix.LiveComponent.CID{cid: 1}}, %{__changed__: %{}, lifecycle: %Phoenix.LiveView.Lifecycle{handle_event: [], handle_info: [], handle_params: [], mount: [], after_render: []}, root_view: MyAppWeb.PageLive}, {58191565141039537020645304486230609780, %{}}}}, %{MyForm => %{"my-form" => 1}}, 2}, join_ref: "19", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<id: "phx-F1Td_XjOm7vSV1UG", endpoint: MyAppWeb.Endpoint, view: MyAppWeb.PageLive, parent_pid: nil, root_pid: #PID<0.4508.0>, router: MyAppWeb.Router, assigns: %{__changed__: %{}, flash: %{}, live_action: nil}, transport_pid: #PID<0.4499.0>, ...>, topic: "lv:phx-F1Td_XjOm7vSV1UG", upload_names: %{}, upload_pids: %{}}
```

### Expected behavior

No errors

**Comment by chrismccord** [comment]
This should be fixed on main. Thanks!
