### ISSUE TITLE
live_img_preview throws Phoenix.HTML.Safe exception

### ISSUE THREAD

**Issue by MullPointer** [phoenixframework/phoenix_live_view#2608]
### Environment

* Elixir version (elixir -v): 1.14.3 
* Phoenix version (mix deps): 1.7.2 
* Phoenix LiveView version (mix deps): current main branch, c1449b410cb0c6ff08dc10844fb800a46807032e
* Operating system: Linux Mint 21.1 Vera
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 112.0.1 

### Actual behavior

I set up a basic file upload page for images, almost exactly following the [example in the docs](https://hexdocs.pm/phoenix_live_view/uploads.html). When an image file is selected with the live_file_input, a Phoenix.HTML.Safe exception is thrown by the live_img_preview and no image shown.

[Single page demonstration app](https://gist.github.com/MullPointer/ec68c7840386b7d6c7ec055059023ff2)

Exception:
```
[error] GenServer #PID<0.502.0> terminating
** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %{} of type Map. This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Phoenix.HTML.Form, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Time, Tuple, URI
    (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
    (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
    (phoenix_html 3.3.1) lib/phoenix_html.ex:265: Phoenix.HTML.build_attrs/1
    (phoenix_html 3.3.1) lib/phoenix_html.ex:250: Phoenix.HTML.build_attrs/1
    (phoenix_html 3.3.1) lib/phoenix_html.ex:218: Phoenix.HTML.attributes_escape/1
    (phoenix_live_view 0.18.18) lib/phoenix_component.ex:2737: anonymous fn/2 in Phoenix.Component."live_img_preview (overridable 1)"/1
    /Phoenix Contribution/form_test/phoenix_live_view.exs:73: Example.HomeLive.render/1
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F1ngOJOKlV6XlgUF", event: "event", payload: %{"event" => "validate", "type" => "form", "uploads" => %{"phx-F1ngbf9W3rs_uQAH" => [%{"last_modified" => 1219112422578, "name" => "Apophysis-080819-206 1.jpg", "path" => "avatar", "ref" => "1", "relative_path" => "", "size" => 123473, "type" => "image/jpeg"}]}, "value" => "_target=avatar"}, ref: "22", join_ref: "20"}
State: %{components: {%{}, %{}, 1}, join_ref: "20", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<id: "phx-F1ngOJOKlV6XlgUF", endpoint: Example.Endpoint, view: Example.HomeLive, parent_pid: nil, root_pid: #PID<0.502.0>, router: Example.Router, assigns: %{__changed__: %{}, flash: %{}, live_action: :index, uploaded_files: [], uploads: %{__phoenix_refs_to_names__: %{"phx-F1ngbf9W3rs_uQAH" => :avatar}, avatar: #Phoenix.LiveView.UploadConfig<name: :avatar, max_entries: 1, max_file_size: 8000000, entries: [], accept: ".jpg,.jpeg", ref: "phx-F1ngbf9W3rs_uQAH", errors: [], auto_upload?: false, progress_event: nil, ...>}}, transport_pid: #PID<0.500.0>, ...>, topic: "lv:phx-F1ngOJOKlV6XlgUF", upload_names: %{}, upload_pids: %{}}

```

### Expected behavior
The selected image should be shown and no exception thrown.

### My investigation of cause
This behaviour does not occur on the last release of Phoenix LiveView 0.19. It appears to have begun with commit: 19b7784dfef956a2daff1b4e6e264d98325ca440
The HTML rendering of @rest in live_img_preview is throwing an exception because a value like [id: "phx-preview-2", rest: %{}] is assigned to rest. I think the use of attr. macro introduced in 19b7784dfef956a2daff1b4e6e264d98325ca440 is now storing additional attributes in a rest assign already so the code in the live_img_preview function to do the same is unnecessary and producing an invalid value.

**Comment by MullPointer** [comment]
I have submitted a pull request #2609 that seems to fix this issue.

**Comment by MullPointer** [comment]
Closing issue as my pull request #2609 has been merged.
