### ISSUE TITLE
assert_patched to route raises but patch succeeded correctly

### ISSUE THREAD

**Issue by agundy** [phoenixframework/phoenix_live_view#2652]
### Environment

* Elixir version (elixir -v): 1.14.5
* Phoenix version (mix deps): 1.7.2
* Phoenix LiveView version (mix deps): 0.18.18
* Operating system: ubuntu-latest Github Actions Docker image
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

In our app we have animated JS modals and they trigger server server side callbacks that track the page state in the params correctly but are flakey when being tested.

Here's an overview of the server side action and then the test assertion patch which flakes in CI.

Live View event handler:

```elixir
  @impl true
  def handle_info("additional-item", socket) do
    {:noreply,
     socket
     |> reload_record()
     |> push_event(socket, "js-exec", %{to: "#modal-create-item, attr: "data-hide-modal"})
     |> push_patch_modal("additional-item")}
  end
```

The test that checks this action looks like:

```elixir
      element(view, "button", "Next step") |> render_click()

      assert_patched(view, "/page/#{pickup.id}?modal=additonal-item")
```

The un-intuitive flaking test result:
```
    ** (ArgumentError) expected MyAppWeb.PageLive.Show to patch to "/page/5?modal=additional-item", but got a patch to "/page/5?modal=additional-item"
     code: assert_patched(view, "/page/#{page.id}?modal=additional-item")
     stacktrace:
       (phoenix_live_view 0.18.18) lib/phoenix_live_view/test/live_view_test.ex:1315: Phoenix.LiveViewTest.assert_navigation/4
       (phoenix_live_view 0.18.18) lib/phoenix_live_view/test/live_view_test.ex:1214: Phoenix.LiveViewTest.assert_patch/3
       test/my_app_web/live/page_show_live_test.exs:77: (test)
```

### Expected behavior

Expect this assertion to pass correctly. It seems like the assertion is maybe waiting for a message that already went by
https://github.com/phoenixframework/phoenix_live_view/blob/v0.18.18/lib/phoenix_live_view/test/live_view_test.ex#L1298 Maybe there's a race condition in here. 

The navigation looks like it already completed successfully but the receive block never gets a new message. Should the assert navigation do the check a little differently?

**Comment by chrismccord** [comment]
this is indeed a race. You want `assert_patch` which will await the patch for a period of time. This is the same kind of thing as `assert_receive` vs `assert_received`. You usually want the latter.

**Comment by agundy** [comment]
@chrismccord maybe there's room to improve the error messaging here because it's not really clear why it failed when the message makes it sound like it succeeded.

**Comment by josevalim** [comment]
@agundy good call, done!
