### ISSUE TITLE
no uploads have been allowed on component running inside LiveView named  ...

### ISSUE THREAD

**Issue by noozo** [phoenixframework/phoenix_live_view#2708]
### Environment

* Elixir version (elixir -v): 1.14.3
* Phoenix version (mix deps): 1.7.6
* Phoenix LiveView version (mix deps): 0.19.2
* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier): Opera/Chrome/Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When passing @uploads from the LV to a component, and then into another component (using a different prop name @uploads_map, since @uploads is now reserved), uploads do not work.

Error is: 
```
[error] GenServer #PID<0.12299.0> terminating
** (ArgumentError) no uploads have been allowed on component running inside LiveView named PassionFruitWeb.Live.Specialist.Profile.ProfileDetails
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/upload.ex:191: Phoenix.LiveView.Upload.get_upload_by_ref!/2
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:1216: anonymous fn/3 in Phoenix.LiveView.Channel.maybe_update_uploads/2
    (stdlib 4.2) maps.erl:411: :maps.fold_1/3
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:555: anonymous fn/5 in Phoenix.LiveView.Channel.component_handle_event/6
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/diff.ex:204: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:553: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 4.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.2) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

### Expected behavior

Expected uploads to work.

### Relevant code

Surface view edit_avatar has:

```
@impl true
  def mount(%{"id" => id} = _params, _session, socket) do
    if connected?(socket) do
      user = Accounts.get_user!(id)

      {:ok,
       socket
       |> assign(:user, user)
       |> allow_upload(:avatar,
         client_key: user.id,
         accept: ~w(.png .jpg .jpeg),
         max_entries: 1,
         max_file_size: 1_000_000,
         external: &PassionFruit.Aws.S3Client.presign_upload/2
       )}
    else
      {:ok, socket}
    end
  end

  @impl true
  def render(assigns) do
    ~F"""
    <Tabs active="Avatar" user={@user} unsaved?={false}>
      <FileUpload.S3Uploader
        id="user-avatar"
        save_files_fn={&save_files/2}
        delete_file_fn={&delete_file/2}
        files={if @user.avatar, do: [@user.avatar], else: []}
        uploads_map={@uploads}
        upload_name={:avatar}
        s3_bucket={PassionFruit.Aws.S3Client.bucket(:users)}
        s3_root={"#{@user.id}/avatars"}
        :if={@user.id}
      />
    </Tabs>
    """
  end
```

Then S3Uploader surface component has uploads_map prop:

```
prop uploads_map, :map, required: true
```

and passes it in to Upload surface component

```
<FileUpload.Components.Upload
            id={"upload-#{@id}"}
            uploads_map={@uploads_map}
            upload_name={@upload_name}
            cancel_upload_event={@cancel_upload_event}
            files={@files}
            class={@class}
          />
```

Upload component has prop

```
prop uploads_map, :map, required: true
```

and uses ```it for normal live uploads functions calls

```
@impl true
  def render(assigns) do
    ~F"""
    <div
      id={@id}
      class={"mb-2 p-8 text-center items-center border-dashed border-4 #{@class} flex flex-col gap-2"}
      phx-drop-target={@uploads_map[@upload_name].ref}
    >
      <div>{text(@uploads_map[@upload_name])}</div>
      <div><Phosphoricons.Surface.Icon name="cloud_arrow_up" type="duotone" class="h-16 w-16" /></div>

      <div>
        {#for entry <- @uploads_map[@upload_name].entries}
          {#if slot_assigned?(:default)}
            <#slot />
          {#else}
            <.default_upload_component
              entry={entry}
              cancel_upload_event={@cancel_upload_event}
              errors={@uploads_map[@upload_name].errors}
            />
          {/if}
        {/for}
      </div>

      <div class="form-control">
        <.live_file_input
          upload={@uploads_map[@upload_name]}
          class={tw_merge("file-input file-input-bordered file-input-accent w-full max-w-xs", @class)}
        />
      </div>

      <div class="text-2xs text-yellow-grey-900" id={"file-input-help-#{@id}"}>{upload_help(@uploads_map[@upload_name])}</div>

      <button
        class="btn btn-primary w-44"
        type="submit"
        :if={show_upload_button?(@uploads_map[@upload_name], @files) &&
          !@uploads_map[@upload_name].auto_upload? &&
          Enum.any?(@uploads_map[@upload_name].entries) &&
          !Enum.any?(@uploads_map[@upload_name].errors)}
      >
        Upload
      </button>
    </div>
    """
  end
```

**Comment by chrismccord** [comment]
From the stacktrace, the LiveComponent is receiving an event for handling the uploads, but the LiveView is the one that calls allow_upload. You need to either do the allow_upload inside the component that receives the upload events, or handle those uploads event sin the LiveView. If you can distill this down to a reproducible example that uses only LV I can say more, but that appears to be what is happening. Thanks!

**Comment by noozo** [comment]
oh, i thought LV's were the only ones that could allow_upload. Will give that a try then.

**Comment by noozo** [comment]
After setting the allow_upload on my internal component it does upload, but something is still wrong, as i get this error and the UI doesn't update properly. if i refresh the page the file is there (so it uploaded to S3 and stored reference locally, as expected).

```
(KeyError) key "phx-F2q3Xh0gquaU8A1k" not found in: %{"phx-F2q3YLYm_YvXsg3E" => :avatar}
    :erlang.map_get("phx-F2q3Xh0gquaU8A1k", %{"phx-F2q3YLYm_YvXsg3E" => :avatar})
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/upload.ex:192: Phoenix.LiveView.Upload.get_upload_by_ref!/2
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:1216: anonymous fn/3 in Phoenix.LiveView.Channel.maybe_update_uploads/2
    (stdlib 4.2) maps.erl:411: :maps.fold_1/3
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:555: anonymous fn/5 in Phoenix.LiveView.Channel.component_handle_event/6
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/diff.ex:204: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.19.2) lib/phoenix_live_view/channel.ex:553: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 4.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.2) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    ```

**Comment by noozo** [comment]
could it be because i'm rendering progress and live_img_preview in yet another component inside that one?

**Comment by chrismccord** [comment]
I will need to see an example that reproduces this in LiveView. The error implies a LC is still trying to handle events for an upload that it didn't allow itself
