### ISSUE TITLE
Stream: Bulk-Inserting in `handle_params/3` doesn't use configured `dom_id` function

### ISSUE THREAD

**Issue by Bentheburrito** [phoenixframework/phoenix_live_view#2717]
### Environment

* Elixir version (elixir -v): Elixir 1.14.2
* Phoenix version (mix deps): 1.7.6
* Phoenix LiveView version (mix deps): 0.19.3 (also tested with `main`)
* Operating system: Ubuntu 20.04
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox 114.0.2 (64-bit)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A, I don't have assets/node_modules

### Actual behavior

Hello, I'm trying to `stream/4` a list of 2-element tuples. Since I'm not streaming a struct/map with an `:id` field, I `stream_configure/3` a custom `:dom_id` function in the `mount/3` callback. However, my custom function seems to be ignored when using the bulk-insert feature of `stream/4` in the `handle_params/3` callback. When I navigate to the LiveView (snippet below) in the browser, I get an error telling me to configure the `:dom_id` option, even though I already am. 

[here](https://github.com/Bentheburrito/test_stream_bulk_insert) is a phoenix project that reproduces issue for your cloning convenience. Note that the snippet below (and the linked repo) contain a workaround I found - simply comment out `|> stream(:mystream, tuple_list)` on L26, and uncomment `# send(self(), {:workaround, tuple_list})` on L21. For some reason, the bulk inserting works as expected when the LV sends itself a message with the stream items

```elixir
defmodule TestStreamBulkInsertWeb.StreamBulkInsertLive.Index do
  use TestStreamBulkInsertWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    socket =
      if connected?(socket) do
        stream_configure(socket, :mystream, dom_id: &custom_dom_id/1)
      else
        socket
      end

    {:ok, socket}
  end

  @impl true
  def handle_params(_params, _url, socket) do
    IO.inspect(socket.assigns[:streams][:__configured__], label: "__configured__")

    tuple_list = [{1234, 2345}, {4321, 5432}]
    # send(self(), {:workaround, tuple_list})

    {
      :noreply,
      socket
      |> stream(:mystream, tuple_list)
    }
  end

  @impl true
  def handle_info({:workaround, tuple_list}, socket) do
    {:noreply, stream(socket, :mystream, tuple_list)}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <div :if={assigns[:streams][:mystream]} id="session-list" phx-update="stream">
      <div :for={{dom_id, {one, two}} <- @streams.mystream} id={dom_id}>
        1: <%= one %>, 2: <%= two %>
      </div>
    </div>
    """
  end

  defp custom_dom_id({one, two}) do
    "session-#{one}-#{two}"
  end
end
```

```elixir
[error] #PID<0.886.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.606.0>, stream id 22) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) expected stream :mystream to be a struct or map with :id key, got: {1234, 2345}

If you would like to generate custom DOM id's based on other keys, use the :dom_id option.

        (phoenix_live_view 0.19.3) lib/phoenix_live_view/live_stream.ex:38: Phoenix.LiveView.LiveStream.default_id/2
        (phoenix_live_view 0.19.3) lib/phoenix_live_view/live_stream.ex:23: anonymous fn/4 in Phoenix.LiveView.LiveStream.new/4
        (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.19.3) lib/phoenix_live_view/live_stream.ex:23: Phoenix.LiveView.LiveStream.new/4
        (phoenix_live_view 0.19.3) lib/phoenix_live_view.ex:1804: Phoenix.LiveView.assign_stream/4
        (test_stream_bulk_insert 0.1.0) lib/test_stream_bulk_insert_web/live/stream_bulk_insert_live/index.ex:26: TestStreamBulkInsertWeb.StreamBulkInsertLive.Index.handle_params/3
        (phoenix_live_view 0.19.3) lib/phoenix_live_view/utils.ex:462: anonymous fn/5 in Phoenix.LiveView.Utils.call_handle_params!/5
        (telemetry 1.2.1) /media/storage/Desktop/Coding Stuff/Elixir/Phoenix/test_stream_bulk_insert/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix_live_view 0.19.3) lib/phoenix_live_view/static.ex:279: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.19.3) lib/phoenix_live_view/static.ex:119: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.19.3) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.6) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
        (test_stream_bulk_insert 0.1.0) lib/test_stream_bulk_insert_web/endpoint.ex:1: TestStreamBulkInsertWeb.Endpoint.plug_builder_call/2
        (test_stream_bulk_insert 0.1.0) lib/plug/debugger.ex:136: TestStreamBulkInsertWeb.Endpoint."call (overridable 3)"/2
        (test_stream_bulk_insert 0.1.0) lib/test_stream_bulk_insert_web/endpoint.ex:1: TestStreamBulkInsertWeb.Endpoint.call/2
        (phoenix 1.7.6) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) /media/storage/Desktop/Coding Stuff/Elixir/Phoenix/test_stream_bulk_insert/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /media/storage/Desktop/Coding Stuff/Elixir/Phoenix/test_stream_bulk_insert/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /media/storage/Desktop/Coding Stuff/Elixir/Phoenix/test_stream_bulk_insert/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
 
```

### Expected behavior

I think bulk-inserting with `stream/4` should use the previously configured `:dom_id` function in `handle_params/3`, as it does in `handle_info/2`.

Please let me know if you need any more info!

**Comment by Bentheburrito** [comment]
...Of course, the moment I post this, I find what I'm doing wrong 🙃

Pro tip 1: don't wrap `stream_configure` in `if connected?(socket) ...`
Pro tip 2: read the docs carefully :)
