### ISSUE TITLE
JS.navigate testing issue: no push command found within JS commands

### ISSUE THREAD

**Issue by davydog187** [phoenixframework/phoenix_live_view#2768]
### Environment

* Elixir version (elixir -v): 1.15.2 
* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps): 0.19.5 
* Operating system: MacOS 13.5

### Actual behavior

```elixir
def component(assigns) do
  ~H"""
  <button phx-click={JS.navigate("/somewhere")}>Click Me</button>
  """
 end
 ```
 
 This button correctly navigates the browser to `/somewhere`, but when running tests against this component, such as the following 
 
 ```elixir
assert {:ok, live, _html} = live(conn, ~p"/mypath")

assert live |> element("button") |> render_click()

{path, _flash} = assert_redirect(live)
assert path == ~p"/somewhere"
```

Crashes with the following error

```elixir
16:25:48.176 [error] GenServer #PID<0.482.0> terminating
** (ArgumentError) no push command found within JS commands: [["navigate", %{"href" => "/somewhere", "replace" => false}]]
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/test/client_proxy.ex:1021: Phoenix.LiveViewTest.ClientProxy.maybe_js_event/1
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/test/client_proxy.ex:317: Phoenix.LiveViewTest.ClientProxy.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.474.0>, {%ArgumentError{message: "no push command found within JS commands: [[\"navigate\", %{\"href\" => \"/somewhere", \"replace\" => false}]]"}, [{Phoenix.LiveViewTest.ClientProxy, :maybe_js_event, 1, [file: ~c"lib/phoenix_live_view/test/client_proxy.ex", line: 1021]}, {Phoenix.LiveViewTest.ClientProxy, :handle_info, 2, [file: ~c"lib/phoenix_live_view/test/client_proxy.ex", line: 317]}, {:gen_server, :try_handle_info, 3, [file: ~c"gen_server.erl", line: 1077]}, {:gen_server, :handle_msg, 6, [file: ~c"gen_server.erl", line: 1165]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}}
```
 
### Expected behavior
This should not crash

**Comment by davydog187** [comment]
I'm happy to send a PR if we can confirm that this is not desired

**Comment by josevalim** [comment]
Yeah, i think it should work. If it was <.link navigate={...}> it would work, right?

**Comment by davydog187** [comment]
Yes it would, so this should also work correctly

**Comment by josevalim** [comment]
Agreed

**Comment by odarriba** [comment]
I'm seeing the same error with `JS.patch` too, may it be the same issue?

**Comment by davydog187** [comment]
it is, i'm working on it!

**Comment by emanuelturis** [comment]
Do you need a hand with it? I'd be happy to help.
