### ISSUE TITLE
Async Assigns Error Loading - Docs incorrect or code incorrect?

### ISSUE THREAD

**Issue by John-Elm** [phoenixframework/phoenix_live_view#2794]
### Environment

* Elixir version (elixir -v): 1.15.3
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): GitHub main ([commit 56697d](https://github.com/phoenixframework/phoenix_live_view/commit/56697d304e7a2bba960e71c3ee3c4101af4fb769))
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Using the `.async_result` function component with a `:failed` slot results in an error if I don't pattern match out the `:error` atom from the tuple. See code:

note the `:failed :let={{:error, reason}}`

```elixir
defmodule AsyncAssignWeb.UsersLive do
  use AsyncAssignWeb, :live_view

  alias AsyncAssign.Accounts

  @impl true
  def render(assigns) do
    ~H"""
    <div class="mt-8">If something goes wrong:</div>
    <.async_result :let={user} assign={@failed_to_load}>
      <:loading>Loading admin user...</:loading>
      <:failed :let={{:error, reason}}><%= reason %></:failed>
      <%= if user do %>
        <%= user.email %>
      <% else %>
        No admin user yet!
      <% end %>
    </.async_result>
    """
  end

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
      socket
      |> assign_async(:failed_to_load, fn -> {:error, "Could not find user with email: nonexistent@johnelmlabs.com!"} end)}
  end
end
```

### Expected behavior

The docs say you only need to pattern match out the `reason`. Here's the example given:

```elixir
<.async_result :let={org} assign={@org}>
    <:loading>Loading organization...</:loading>
    <:failed :let={reason}>there was an error loading the organization</:failed>
```

However, if you do this in the code above we get this error:

It seems like my error returning function is getting returned as `{:ok, {:error, "reason"}}` 

Am I holding it wrong? 

Docs say: "The async function must return a `{:ok, assigns}` or `{:error, reason}` tuple"

```elixir
[error] GenServer #PID<0.866.0> terminating
** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for {:error, "Could not find user with email: nonexistent@johnelmlabs.com!"} of type Tuple. This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, NaiveDateTime, Phoenix.HTML.Form, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Time, Tuple, URI
    (phoenix_html 3.3.2) lib/phoenix_html/safe.ex:97: Phoenix.HTML.Safe.Tuple.to_iodata/1
    (async_assign 0.1.0) lib/async_assign_web/live/users_live.ex:12: anonymous fn/3 in AsyncAssignWeb.UsersLive.render/1
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:386: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:538: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.15.3) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:384: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:538: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.15.3) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:361: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:538: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.15.3) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:361: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:136: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:919: Phoenix.LiveView.Channel.render_diff/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:775: Phoenix.LiveView.Channel.handle_changed/4
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:1368: Phoenix.LiveView.Channel.write_socket/4
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:255: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.0.1) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:phoenix, :async_result, {:assign, {#Reference<0.0.110851.92579553.2466578434.28064>, nil, [:failed_to_load], {:ok, {:error, "Could not find user with email: nonexistent@johnelmlabs.com!"}}}}}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F4EeCfailOR_8wWi", endpoint: AsyncAssignWeb.Endpoint, view: AsyncAssignWeb.UsersLive, parent_pid: nil, root_pid: #PID<0.866.0>, router: AsyncAssignWeb.Router, assigns: %{__changed__: %{}, flash: %{}, live_action: :index, failed_to_load: %Phoenix.LiveView.AsyncResult{ok?: false, loading: [:failed_to_load], failed: nil, result: nil}}, transport_pid: #PID<0.855.0>, ...>, components: {%{}, %{}, 1}, topic: "lv:phx-F4EeCfailOR_8wWi", serializer: Phoenix.Socket.V2.JSONSerializer, join_ref: "4", upload_names: %{}, upload_pids: %{}}
Failed to write log message to stdout, trying stderr
[error] GenServer #PID<0.64.0> terminating
** (ArgumentError) argument error
    (stdlib 5.0.1) lists.erl:1815: :lists.split(1, 27)
    (kernel 9.0.1) prim_tty.erl:1113: :prim_tty.insert_buf/4
    (kernel 9.0.1) prim_tty.erl:759: :prim_tty.handle_request/2
    (kernel 9.0.1) user_drv.erl:811: :user_drv.io_request/2
    (kernel 9.0.1) user_drv.erl:834: :user_drv.io_requests/2
    (kernel 9.0.1) user_drv.erl:777: :user_drv.io_request/2
    (kernel 9.0.1) user_drv.erl:897: :user_drv.handle_req/3
    (kernel 9.0.1) user_drv.erl:483: :user_drv.server/3
    (stdlib 5.0.1) gen_statem.erl:1377: :gen_statem.loop_state_callback/11
    (stdlib 5.0.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by John-Elm** [comment]
I’m closing because I think the desired behavior here is to have the function running in the task raise on failure - that way you handle either an exit or a success
