### ISSUE TITLE
Crash :writer_closed? when uploading constraint reached - 0.20.0

### ISSUE THREAD

**Issue by ndrean** [phoenixframework/phoenix_live_view#2825]
### Environment

* Elixir version (elixir -v): 1.15.6
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.20
* Operating system: OSX
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

If I don't reach an upload constraint, it behaves ok (v0.20.0). 

When my number of uploads exceeds `max_entries` in `allow_upload`, I get a crash instead of appending the error(s). 

I returned to 0.19.5 and it behaves ok if I exceed a `max_entries`, meaning I get the expected errors. Same code.

```
[error] GenServer #PID<0.1336.0> terminating
** (KeyError) key :writer_closed? not found in: %{}
    (phoenix_live_view 0.20.0) lib/phoenix_live_view/upload_channel.ex:220: Phoenix.LiveView.UploadChannel.maybe_cancel_writer/1
```

```
Last message: {Phoenix.Channel, %{"token" => "SFMyNTY.g2gDaAJhBXQAAAADdwNwaWRYdw1ub25vZGVAbm9ob3N0AAAFLAAAAAAAAAAAdwNyZWZoAm0AAAAUcGh4LUY0aHN1VjVoRUlJQWdDUWhtAAAAATF3A2NpZHcDbmlsbgYAJCoT0YoBYgABUYA.uCEgx1b6vYeyAZdJrD2jrNs2APFAScDZ8cn-pasndF8"}, {#PID<0.1314.0>, #Reference<0.1954124069.1606418435.96412>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.UploadChannel, channel_pid: nil, endpoint: UpImgWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: "users_sessions:4", joined: false, join_ref: "16", private: %{connect_info: %{session: %{"_csrf_token" => "s7tJZXwBLaBrTXUH-KRbdAqF", "live_socket_id" => "users_sessions:4", "user_id" => 4}, peer_data: %{port: 54486, address: {127, 0, 0, 1}, ssl_cert: nil}, user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"}}, pubsub_server: UpImg.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lvu:1", transport: :websocket, transport_pid: #PID<0.1314.0>}}
State: %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.UploadChannel, channel_pid: #PID<0.1336.0>, endpoint: UpImgWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: "users_sessions:4", joined: false, join_ref: "16", private: %{connect_info: %{session: %{"_csrf_token" => "s7tJZXwBLaBrTXUH-KRbdAqF", "live_socket_id" => "users_sessions:4", "user_id" => 4}, peer_data: %{port: 54486, address: {127, 0, 0, 1}, ssl_cert: nil}, user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"}, log_handle_in: false, log_join: :info}, pubsub_server: UpImg.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lvu:1", transport: :websocket, transport_pid: #PID<0.1314.0>}
```

**Comment by chrismccord** [comment]
Please give main a shot if you're able to recreate this and let me know if all is good. Thanks!

**Comment by ndrean** [comment]
You probably tested as ok, but on my side, I still have a crash when I reach the limit.

```elixir
GenServer #PID<0.938.0> terminating
** (KeyError) key :writer_closed? not found in: %{}
    (phoenix_live_view 0.20.0) lib/phoenix_live_view/upload_channel.ex:220: Phoenix.LiveView.UploadChannel.maybe_cancel_writer/1
    (phoenix_live_view 0.20.0) lib/phoenix_live_view/upload_channel.ex:170: Phoenix.LiveView.UploadChannel.terminate/2
```

So I will review my code when I use `assign_async`.

**Comment by josevalim** [comment]
@ndrean I think your code was not updated for some reason.

**Comment by ndrean** [comment]
I just picked `{:phoenix_live_view, "~> 0.20.0"}` in the mix.
