### ISSUE TITLE
String Key Access in `Phoenix.Component.to_form/1` struct does not work with `Phoenix.HTML.Form.input_changed?/3` 

### ISSUE THREAD

**Issue by kevinschweikert** [phoenixframework/phoenix_live_view#2851]
### Environment

* Elixir version (elixir -v): 1.15.6
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: macOS Ventura 13.5.2 (22G91)
* Browsers you attempted to reproduce this bug on (the more, the merrier): Arc, Safari, Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

```elixir
defmodule MyAppWeb.FormLive do
  use MyAppWeb, :live_view

  def mount(_params, _session, socket) do
    {:ok,
     assign(
       socket,
       :form,
       to_form(%{
         "input_one" => "one",
         "input_two" => "two"
       })
     )}
  end

  def render(assigns) do
    ~H"""
    <.simple_form for={@form} phx-change="change">
      <.input field={@form["input_one"]} />
      <.input field={@form["input_two"]} />
    </.simple_form>
    """
  end

  def handle_event("change", params, socket) do
    new_values = %{
      "input_one" => "",
      "input_two" => "four"
    }

    {:noreply, assign(socket, :form, to_form(new_values))}
  end
end
```

When I change the first input, I get the following error:

```shell
[debug] HANDLE EVENT "change" in MyAppWeb.FormLive
  Parameters: %{"_target" => ["input_one"], "input_one" => "onei", "input_two" => "two"}
[debug] Replied in 420µs
[error] GenServer #PID<0.908.0> terminating
** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.input_changed?/3
    (phoenix_html 3.3.2) lib/phoenix_html/form.ex:197: Phoenix.HTML.Form.input_changed?(%Phoenix.HTML.Form{source: %{"input_one" => "", "input_two" => "four"}, impl: Phoenix.HTML.FormData.Map, id: nil, name: nil, data: %{}, hidden: [], params: %{"input_one" => "", "input_two" => "four"}, errors: [], options: [], index: nil, action: nil}, %Phoenix.HTML.Form{source: %{"input_one" => "one", "input_two" => "two"}, impl: Phoenix.HTML.FormData.Map, id: nil, name: nil, data: %{}, hidden: [], params: %{"input_one" => "one", "input_two" => "two"}, errors: [], options: [], index: nil, action: nil}, "input_one")
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/engine.ex:1234: Phoenix.LiveView.Engine.nested_changed_assign?/4
    (elixir 1.15.6) lib/enum.ex:4190: Enum.predicate_list/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/engine.ex:736: anonymous fn/4 in Phoenix.LiveView.Engine.to_component_static/3
    (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/engine.ex:735: Phoenix.LiveView.Engine.to_component_static/3
    lib/my_app_web/live/form.ex:17: anonymous fn/2 in MyAppWeb.FormLive.render/1
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:363: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:538: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
    (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:361: Phoenix.LiveView.Diff.traverse/7
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/diff.ex:136: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:833: Phoenix.LiveView.Channel.render_diff/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:689: Phoenix.LiveView.Channel.handle_changed/4
    (stdlib 5.1) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F4yAp414RgotIQKG", event: "event", payload: %{"event" => "change", "type" => "form", "uploads" => %{}, "value" => "input_one=onei&input_two=two&_target=input_one"}, ref: "8", join_ref: "4"}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F4yAp414RgotIQKG", endpoint: MyAppWeb.Endpoint, view: MyAppWeb.FormLive, parent_pid: nil, root_pid: #PID<0.908.0>, router: MyAppWeb.Router, assigns: %{form: %Phoenix.HTML.Form{source: %{"input_one" => "one", "input_two" => "two"}, impl: Phoenix.HTML.FormData.Map, id: nil, name: nil, data: %{}, hidden: [], params: %{"input_one" => "one", "input_two" => "two"}, errors: [], options: [], index: nil, action: nil}, __changed__: %{}, flash: %{}, live_action: nil}, transport_pid: #PID<0.899.0>, ...>, components: {%{}, %{}, 1}, topic: "lv:phx-F4yAp414RgotIQKG", serializer: Phoenix.Socket.V2.JSONSerializer, join_ref: "4", upload_names: %{}, upload_pids: %{}}
```

When i change the access to atom keys like:

```heex
<.input field={@form[:input_one]} />
<.input field={@form[:input_two]} />
```

Everything works as expected. The second field changes to the value `"four"`

### Expected behavior

That the access variant is not relevant, and I can also use `@form["key"]`. I could not find an exceptions in the [Form Access Behaviour Docs](https://hexdocs.pm/phoenix_html/3.3.2/Phoenix.HTML.Form.html#module-access-behaviour)

**Comment by josevalim** [comment]
This is fixed in phoenix_html main. I will ship a new version soon. :)

**Comment by josevalim** [comment]
New version out.

**Comment by kevinschweikert** [comment]
Second issue in one day raised in the wrong repo 😄  Thanks @josevalim for your help and kindness! ❤️
