### ISSUE TITLE
Redirecting inside a handle_async function generates no match error

### ISSUE THREAD

**Issue by sezaru** [phoenixframework/phoenix_live_view#2875]
### Environment

* Elixir version (elixir -v): 1.15.7
* Phoenix version (mix deps): 1.7.7
* Phoenix LiveView version (mix deps): 0.20.0
* Operating system: Fedora 39
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox
* Does the problem persist after removing "assets/node_modules" and trying again? Yes

### Actual behavior

Consider the following live view:

```elixir
defmodule CoreWeb.Live.Trash.TestRedirect do
  use CoreWeb, :live_view

  def mount(_, _, socket) do
    socket = start_async(socket, :saving, fn -> some_save!() end)

    {:ok, socket}
  end

  def handle_async(:saving, {:ok, :something}, socket),
      do: {:noreply, push_redirect(socket, to: ~p"/schools")}

  def render(assigns) do
    ~H"""
    <div>redirecting</div>
    """
  end

  defp some_save! do
    Process.sleep(1_000)

    :something
  end
end
```

When `push_redirect` is called, it will correctly redirect to the new page, but it will generate the following error in the terminal:

```elixir
[error] GenServer #PID<0.6447.0> terminating
** (MatchError) no match of right hand side value: {:stop, {:shutdown, {:live_redirect, %{kind: :push, to: "/schools"}}}, %{socket: #Phoenix.LiveView.Socket<id: "phx-F5A7tE9fwsKz9PqB", endpoint: CoreWeb.Endpoint, view: CoreWeb.Live.Trash.TestRedirect, parent_pid: nil, root_pid: #PID<0.6447.0>, router: CoreWeb.Router, assigns: %{__changed__: %{}, flash: %{}, app_title: nil, actor: #Core.Accounts.User<full_name: "Eduardo blibs", organizations: #Ash.NotLoaded<:relationship>, schools: #Ash.NotLoaded<:relationship>, subscription: nil, token: #Ash.NotLoaded<:relationship>, user_schools: [#Core.Accounts.UserSchool<school: #Core.Accounts.School<users: #Ash.NotLoaded<:relationship>, organization: #Ash.NotLoaded<:relationship>, school_users: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "schools">, id: "02uDvgNgvw5b1yGxS7jtO4", name: "my school", uid: "blibs", creation_type: :custom, geography: nil, address: "blibs", city: "Miami", district: "blibs", state: "FL", country: "USA", education_system: :esl, type: :private, b2b?: false, metadata: %{}, inserted_at: ~U[2023-09-03 22:08:22.293281Z], updated_at: ~U[2023-09-03 22:08:22.293281Z], organization_id: "02uDvgNh29kHfKzm5C8deY", aggregates: %{}, calculations: %{}, ...>, user: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "users_schools">, admin?: true, signature: nil, description: nil, metadata: %{}, user_id: "02uDvgMXsKxi5nnACZcqto", school_id: "02uDvgNgvw5b1yGxS7jtO4", aggregates: %{}, calculations: %{}, ...>], user_organizations: [#Core.Accounts.UserOrganization<organization: #Core.Accounts.Organization<users: #Ash.NotLoaded<:relationship>, schools: #Ash.NotLoaded<:relationship>, users_join_assoc: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "organizations">, id: "02uDvgNh29kHfKzm5C8deY", name: "my school", b2b?: false, inserted_at: ~U[2023-09-03 22:08:22.294374Z], updated_at: ~U[2023-09-03 22:08:22.294374Z], aggregates: %{}, calculations: %{}, ...>, user: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "users_organizations">, admin?: true, user_id: "02uDvgMXsKxi5nnACZcqto", organization_id: "02uDvgNh29kHfKzm5C8deY", aggregates: %{}, calculations: %{}, ...>], __meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "02uDvgMXsKxi5nnACZcqto", email: #Ash.CiString<"blibs@blobs.com">, first_name: "Eduardo", surname: "blibs", signature: nil, allow_emails?: false, allow_tips?: true, share_templates_by_default?: true, use_default_signature_for_all_schools?: false, referral_code: "02uDvgN0QxZ12iGvHzOeW0", roles: [:teacher], confirmed_at: ~U[2023-09-03 22:08:22.306403Z], normalized_full_name: "eduardo blibs", inserted_at: ~U[2023-09-03 22:08:21.571615Z], updated_at: ~U[2023-09-03 22:08:22.310620Z], aggregates: %{}, calculations: %{}, ...>, live_action: nil}, transport_pid: #PID<0.6440.0>, ...>, components: {%{}, %{}, 1}, topic: "lv:phx-F5A7tE9fwsKz9PqB", serializer: Phoenix.Socket.V2.JSONSerializer, join_ref: "4", upload_names: %{}, upload_pids: %{}}}
    (phoenix_live_view 0.20.0) lib/phoenix_live_view/channel.ex:1368: Phoenix.LiveView.Channel.write_socket/4
    (phoenix_live_view 0.20.0) lib/phoenix_live_view/channel.ex:255: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.1.1) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.1.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:phoenix, :async_result, {:start, {#Reference<0.0.825219.2328737576.834994177.218637>, nil, :saving, {:ok, :something}}}}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F5A7tE9fwsKz9PqB", endpoint: CoreWeb.Endpoint, view: CoreWeb.Live.Trash.TestRedirect, parent_pid: nil, root_pid: #PID<0.6447.0>, router: CoreWeb.Router, assigns: %{__changed__: %{}, flash: %{}, app_title: nil, actor: #Core.Accounts.User<full_name: "Eduardo blibs", organizations: #Ash.NotLoaded<:relationship>, schools: #Ash.NotLoaded<:relationship>, subscription: nil, token: #Ash.NotLoaded<:relationship>, user_schools: [#Core.Accounts.UserSchool<school: #Core.Accounts.School<users: #Ash.NotLoaded<:relationship>, organization: #Ash.NotLoaded<:relationship>, school_users: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "schools">, id: "02uDvgNgvw5b1yGxS7jtO4", name: "my school", uid: "blibs", creation_type: :custom, geography: nil, address: "blibs", city: "Miami", district: "blibs", state: "FL", country: "USA", education_system: :esl, type: :private, b2b?: false, metadata: %{}, inserted_at: ~U[2023-09-03 22:08:22.293281Z], updated_at: ~U[2023-09-03 22:08:22.293281Z], organization_id: "02uDvgNh29kHfKzm5C8deY", aggregates: %{}, calculations: %{}, ...>, user: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "users_schools">, admin?: true, signature: nil, description: nil, metadata: %{}, user_id: "02uDvgMXsKxi5nnACZcqto", school_id: "02uDvgNgvw5b1yGxS7jtO4", aggregates: %{}, calculations: %{}, ...>], user_organizations: [#Core.Accounts.UserOrganization<organization: #Core.Accounts.Organization<users: #Ash.NotLoaded<:relationship>, schools: #Ash.NotLoaded<:relationship>, users_join_assoc: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "organizations">, id: "02uDvgNh29kHfKzm5C8deY", name: "my school", b2b?: false, inserted_at: ~U[2023-09-03 22:08:22.294374Z], updated_at: ~U[2023-09-03 22:08:22.294374Z], aggregates: %{}, calculations: %{}, ...>, user: #Ash.NotLoaded<:relationship>, __meta__: #Ecto.Schema.Metadata<:loaded, "users_organizations">, admin?: true, user_id: "02uDvgMXsKxi5nnACZcqto", organization_id: "02uDvgNh29kHfKzm5C8deY", aggregates: %{}, calculations: %{}, ...>], __meta__: #Ecto.Schema.Metadata<:loaded, "users">, id: "02uDvgMXsKxi5nnACZcqto", email: #Ash.CiString<"blibs@blobs.com">, first_name: "Eduardo", surname: "blibs", signature: nil, allow_emails?: false, allow_tips?: true, share_templates_by_default?: true, use_default_signature_for_all_schools?: false, referral_code: "02uDvgN0QxZ12iGvHzOeW0", roles: [:teacher], confirmed_at: ~U[2023-09-03 22:08:22.306403Z], normalized_full_name: "eduardo blibs", inserted_at: ~U[2023-09-03 22:08:21.571615Z], updated_at: ~U[2023-09-03 22:08:22.310620Z], aggregates: %{}, calculations: %{}, ...>, live_action: nil}, transport_pid: #PID<0.6440.0>, ...>, components: {%{}, %{}, 1}, topic: "lv:phx-F5A7tE9fwsKz9PqB", serializer: Phoenix.Socket.V2.JSONSerializer, join_ref: "4", upload_names: %{}, upload_pids: %{}}
```

### Expected behavior

redirecting inside a `handle_async` function should not generate errors.

**Comment by louisvisser** [comment]
Same issue here - similar liveview to your example, except I'm attempting to `push_navigate` inside of the `handle_async`

One possible workaround for now, is to let the liveview redirect _after_ the `Phoenix.LiveView.Channel.write_socket` which is failing (by just doing it afterwards inside a separate `handle_info` message):

```elixir
  def handle_async(:my_task, {:ok, result, flash_type, flash_msg}, socket) do
    Process.send(self(), {:redirect, flash_type, flash_message}, [:noconnect])
    
    socket
    |> assign(task_result: %AsyncResult{ok?: true})
    ...
    |> then(&{:noreply, &1})
  end
  
  def handle_info({:redirect, flash_type, flash_message}, socket) do
    socket
    |> push_navigate(to: ~p"/users")
    |> put_flash(flash_type, flash_message)
    |> then(&{:noreply, &1})
  end
```

**Comment by simonelnahas** [comment]
Can confirm that updating to 0.20.3 worked for me. Thanks!
