### ISSUE TITLE
Nested LiveViews receiving `:session` data throw `RuntimeError` when tested

### ISSUE THREAD

**Issue by jmilamwalters** [phoenixframework/phoenix_live_view#289]
### Environment

* Elixir version (elixir -v): `1.8.1`
* Phoenix version (mix deps): `1.4.8`
* NodeJS version (node -v): `12.2.0`
* NPM version (npm -v): `6.9.0`
* Operating system: `macOS Mojave, Version 10.14.6`

### Overview

A `RuntimeError` is thrown when:

- A parent LiveView encompasses a child LiveView;
- The parent passes in `session: assigns` to the child;
- We execute a test, which mounts the parent via `live/2` and invokes a function responsible for re-rendering the DOM (e.g., `render_click/3`).

If only to clarify:

- We suffer the exception only when testing; I have yet to encounter the error while hosting the web-app.
- We do not suffer the exception should we exclude `session: assigns` as an option when calling `live_render/3`, or should we specify a value such as an empty map (e.g., `assigns: %{}`).

### Actual behavior

To demonstrate, I have:

- Forked the repository residing at [phoenixframework/phoenix_live_view;](https://github.com/chrismccord/phoenix_live_view_example)
- Passed in `session: assigns` for the nested LiveView rendered [here;](https://github.com/chrismccord/phoenix_live_view_example/pull/38/files#diff-6293cd704179675d1ec887ecf046311aR17) 
- Composed a [unit test,](https://github.com/chrismccord/phoenix_live_view_example/pull/38/files#diff-528c075ffe073687cca9d22303478ef5R1) which occasions a re-render via `render_click/3`. 

Upon running:

```bash
$CMD mix test
```

The following `RuntimeError` is thrown.

```
14:27:29.450 [error] GenServer #PID<0.397.0> terminating
** (RuntimeError) unable to start child DemoWeb.WeatherLive under duplicate name for parent DemoWeb.ThermostatLive.
A child LiveView #PID<0.398.0> is already running under the ID phx-hdZdBa5wDemoWeb.WeatherLive.

To render multiple LiveView children of the same module, a
child_id option must be provided per live_render call. For example:

    <%= live_render @socket, DemoWeb.WeatherLive, child_id: 1 %>
    <%= live_render @socket, DemoWeb.WeatherLive, child_id: 2 %>

    (phoenix_live_view) lib/phoenix_live_view/channel.ex:509: Phoenix.LiveView.Channel.put_child/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:98: Phoenix.LiveView.Channel.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.399.0>): {:phoenix, :child_mount, #PID<0.399.0>, DemoWeb.WeatherLive, "phx-hdZdBa5wDemoWeb.WeatherLive", []}
14:27:29.453 [error] GenServer #PID<0.399.0> terminating
** (stop) exited in: GenServer.call(#PID<0.397.0>, {:phoenix, :child_mount, #PID<0.399.0>, DemoWeb.WeatherLive, "phx-hdZdBa5wDemoWeb.WeatherLive", []}, 5000)
    ** (EXIT) an exception was raised:
        ** (RuntimeError) unable to start child DemoWeb.WeatherLive under duplicate name for parent DemoWeb.ThermostatLive.
A child LiveView #PID<0.398.0> is already running under the ID phx-hdZdBa5wDemoWeb.WeatherLive.

To render multiple LiveView children of the same module, a
child_id option must be provided per live_render call. For example:

    <%= live_render @socket, DemoWeb.WeatherLive, child_id: 1 %>
    <%= live_render @socket, DemoWeb.WeatherLive, child_id: 2 %>

            (phoenix_live_view) lib/phoenix_live_view/channel.ex:509: Phoenix.LiveView.Channel.put_child/4
            (phoenix_live_view) lib/phoenix_live_view/channel.ex:98: Phoenix.LiveView.Channel.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:499: Phoenix.LiveView.Channel.register_with_parent/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:424: Phoenix.LiveView.Channel.verified_mount/9
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
14:27:29.457 [error] GenServer #PID<0.396.0> terminating
** (RuntimeError) failed to mount view: {{%RuntimeError{message: "unable to start child DemoWeb.WeatherLive under duplicate name for parent DemoWeb.ThermostatLive.\nA child LiveView #PID<0.398.0> is already running under the ID phx-hdZdBa5wDemoWeb.WeatherLive.\n\nTo render multiple LiveView children of the same module, a\nchild_id option must be provided per live_render call. For example:\n\n    <%= live_render @socket, DemoWeb.WeatherLive, child_id: 1 %>\n    <%= live_render @socket, DemoWeb.WeatherLive, child_id: 2 %>\n"}, [{Phoenix.LiveView.Channel, :put_child, 4, [file: 'lib/phoenix_live_view/channel.ex', line: 509]}, {Phoenix.LiveView.Channel, :handle_call, 3, [file: 'lib/phoenix_live_view/channel.ex', line: 98]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}, {GenServer, :call, [#PID<0.397.0>, {:phoenix, :child_mount, #PID<0.399.0>, DemoWeb.WeatherLive, "phx-hdZdBa5wDemoWeb.WeatherLive", []}, 5000]}}
    (phoenix_live_view) lib/phoenix_live_view/test/client_proxy.ex:459: anonymous fn/4 in Phoenix.LiveViewTest.ClientProxy.do_detect_added_or_removed_children/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view) lib/phoenix_live_view/test/client_proxy.ex:437: Phoenix.LiveViewTest.ClientProxy.do_detect_added_or_removed_children/2
    (phoenix_live_view) lib/phoenix_live_view/test/client_proxy.ex:421: Phoenix.LiveViewTest.ClientProxy.detect_added_or_removed_children/2
    (phoenix_live_view) lib/phoenix_live_view/test/client_proxy.ex:184: Phoenix.LiveViewTest.ClientProxy.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Reply{join_ref: 0, payload: %{diff: %{3 => "73", 4 => "<div data-phx-parent-id=\"phx-hdZdBa5w\" data-phx-session=\"SFMyNTY.g3QAAAACZAAEZGF0YXQAAAAFZAACaWRtAAAAH3BoeC1oZFpkQmE1d0RlbW9XZWIuV2VhdGhlckxpdmVkAApwYXJlbnRfcGlkZ2QADW5vbm9kZUBub2hvc3QAAAGNAAAAAABkAAZyb3V0ZXJkABVFbGl4aXIuRGVtb1dlYi5Sb3V0ZXJkAAdzZXNzaW9udAAAAARkAARtb2RlZAAHY29vbGluZ2QABnNvY2tldHQAAAAMZAAKX19zdHJ1Y3RfX2QAHkVsaXhpci5QaG9lbml4LkxpdmVWaWV3LlNvY2tldGQAB2Fzc2lnbnN0AAAAAGQAB2NoYW5nZWR0AAAAAWQAA3ZhbGQABHRydWVkAApjb25uZWN0ZWQ_ZAAEdHJ1ZWQACGVuZHBvaW50ZAAXRWxpeGlyLkRlbW9XZWIuRW5kcG9pbnRkAAxmaW5nZXJwcmludHNoAm4QAKrzanS95drSM_4v70Sm1H50AAAAAGQAAmlkbQAAAAxwaHgtaGRaZEJhNXdkAApwYXJlbnRfcGlkZAADbmlsZAAHcHJpdmF0ZXQAAAAAZAAKcmVkaXJlY3RlZGQAA25pbGQABnJvdXRlcmQAFUVsaXhpci5EZW1vV2ViLlJvdXRlcmQABHZpZXdkAB1FbGl4aXIuRGVtb1dlYi5UaGVybW9zdGF0TGl2ZWQABHRpbWVoAmgDYgAAB-NhCGEBaANhDmEbYR1kAAN2YWxhSWQABHZpZXdkABpFbGl4aXIuRGVtb1dlYi5XZWF0aGVyTGl2ZWQABnNpZ25lZG4GABm53U5sAQ.QVKeWHlK7ZHfBFGQr3UTtzcyZlBJGMF6o3_iwa0cE3o\" data-phx-static=\"\" data-phx-view=\"DemoWeb.WeatherLive\" id=\"phx-hdZdBa5wDemoWeb.WeatherLive\"></div>\n"}}, ref: "1", status: :ok, topic: "phx-TwWLKmtYrlk="}


  1) test clicking + makes the number go up (DemoWeb.ThermostatLiveTest)
     test/thermostat_test.exs:5
     ** (EXIT from #PID<0.394.0>) an exception was raised:
         ** (RuntimeError) failed to mount view: {{%RuntimeError{message: "unable to start child DemoWeb.WeatherLive under duplicate name for parent DemoWeb.ThermostatLive.\nA child LiveView #PID<0.398.0> is already running under the ID phx-hdZdBa5wDemoWeb.WeatherLive.\n\nTo render multiple LiveView children of the same module, a\nchild_id option must be provided per live_render call. For example:\n\n    <%= live_render @socket, DemoWeb.WeatherLive, child_id: 1 %>\n    <%= live_render @socket, DemoWeb.WeatherLive, child_id: 2 %>\n"}, [{Phoenix.LiveView.Channel, :put_child, 4, [file: 'lib/phoenix_live_view/channel.ex', line: 509]}, {Phoenix.LiveView.Channel, :handle_call, 3, [file: 'lib/phoenix_live_view/channel.ex', line: 98]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}, {GenServer, :call, [#PID<0.397.0>, {:phoenix, :child_mount, #PID<0.399.0>, DemoWeb.WeatherLive, "phx-hdZdBa5wDemoWeb.WeatherLive", []}, 5000]}}
             (phoenix_live_view) lib/phoenix_live_view/test/client_proxy.ex:459: anonymous fn/4 in Phoenix.LiveViewTest.ClientProxy.do_detect_added_or_removed_children/2
             (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
             (phoenix_live_view) lib/phoenix_live_view/test/client_proxy.ex:437: Phoenix.LiveViewTest.ClientProxy.do_detect_added_or_removed_children/2
             (phoenix_live_view) lib/phoenix_live_view/test/client_proxy.ex:421: Phoenix.LiveViewTest.ClientProxy.detect_added_or_removed_children/2
             (phoenix_live_view) lib/phoenix_live_view/test/client_proxy.ex:184: Phoenix.LiveViewTest.ClientProxy.handle_info/2
             (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
             (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
             (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

- I have opened a `Draft` PR illustrating the diff [here.](https://github.com/chrismccord/phoenix_live_view_example/pull/38)
- The relevant branch `nested-liveviews-throw-exception-during-tests` may be found [here.](https://github.com/jmilamwalters/phoenix_live_view_example/tree/nested-liveviews-throw-exception-during-tests)

### Expected behavior

I should think that either: 

- The test should not throw an exception; 

Or:

- `live_render/3` should not accept `:session` as a potential option when encompassed by a parent LiveView. Such usage is currently documented [here.](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view.ex#L233)

**Comment by chrismccord** [comment]
You should not be storing all socket assigns in the child session. Note that `assigns` also includes the `socket` itself and all the state. The reason this error is being thrown is the `live_render` call will *always* be reinvoked because our change tracking only knows that `assigns` must necessarily have changed if we are re-rendering. So our change tracking must always re-invoke the `live_render` and thus a child error is thrown because an existing child is already up and running. Children detect their own removal, so there is a race between the browser and test suite on whether on not this gets triggered. You could provide a unique child_id, but the true fix is to not pass all `assigns` to the child session. It's a bad fit for the session and like I covered above, our change tracking makes this a poor fit in general. Also note that our static `render` can indeed perform change tracking if you pass all `assigns`, so if you don't actually need the isolation/concurrency of a separate process, a regular rendered template may also be an option. Closing since this is working as it should. Hope that helps!

**Comment by chrismccord** [comment]
This race condition has been fixed in the test suite, but the above advice still holds true. While it triggered the race, the session should not be used to store the kind of data as above. Thanks!

**Comment by jmilamwalters** [comment]
Thank you so much, @chrismccord. 

Earlier, I was unable to use `@val` when calling `live_render/3` in `DemoWeb.ThermostatLive` without throwing an error, as with:

```elixir
<%= live_render(@socket, DemoWeb.WeatherLive, child_id: 1, session: %{val: @val}) %>
```

In light of your latest commit, however, this test now passes!
