### ISSUE TITLE
live_file_input doesn't work with phx-target for a stateful component with label and target

### ISSUE THREAD

**Issue by spunkedy** [phoenixframework/phoenix_live_view#2894]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.15.4 (compiled with Erlang/OTP 26)
```

* Phoenix version (mix deps):
* Phoenix LiveView version (mix deps):

```
      {:phoenix, "~> 1.7.9"},
      {:phoenix_html, "~> 3.3"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.20.1"},
      {:phoenix_live_dashboard, "~> 0.8.2"},
```
* Operating system:
```
Linux pdesktop 6.4.7-1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.4-8ubuntu1~jammy (2023-07-27) x86_64 x86_64 x86_64 GNU/Linux
```
* Browsers you attempted to reproduce this bug on (the more the merrier): 
Chrome

* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
N/A

### Actual behavior

live view -> live view stateful component with `live_file_input` and `phx-target` sends event to live view instead of the component.

```mermaid
graph TD;
live_view-->live_view_stateful_component-- with phx-target tag -->live_file_input
live_file_input--sends message to-->live_view

```

### Expected behavior

```mermaid
graph TD;
live_view-->live_view_stateful_component-- with phx-target tag -->live_file_input
live_file_input--sends message to-->live_view_stateful_component

```

When sending a message from a stateful component even if there is a `phx-target` it sends it to the parent. 

```
[error] GenServer #PID<0.6992.0> terminating
** (ArgumentError) no uploads have been allowed on LiveView named RokuControllerWeb.GitInteractorLive
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/upload.ex:195: Phoenix.LiveView.Upload.get_upload_by_ref!/2
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:1304: anonymous fn/3 in Phoenix.LiveView.Channel.maybe_update_uploads/2
    (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:243: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F5K9HMC97Z7yWDSh", event: "event", payload: %{"event" => 
```

If I add the allow list to the parent:

```
[error] GenServer #PID<0.492.0> terminating
** (KeyError) key "phx-F5K97fyuZh7IuAMh" not found in: %{"phx-F5K97fl_3jzIuAAD" => :photos}
    :erlang.map_get("phx-F5K97fyuZh7IuAMh", %{"phx-F5K97fl_3jzIuAAD" => :photos})
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/upload.ex:196: Phoenix.LiveView.Upload.get_upload_by_ref!/2
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:1304: anonymous fn/3 in Phoenix.LiveView.Channel.maybe_update_uploads/2
    (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:243: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F5K9HMC97Z7yWDSh", event: "event", payload: %{"event" => "checkout", "type" => "form", "uploads" => %{"phx-F5K97fyuZh7IuAMh" => [%{"last_modified" => 1698592217497, "name" => "chat.png", "path" => "photo", "ref" => "1", "relative_path" => "", "size" => 648964, "type" => "image/png"}]}, "value" => "selected_branch=&_target=photo"}, ref: "29", join_ref: "28"}
State: %{socket: #Phoenix.LiveView.Socket<id: "phx-F5K9HMC97Z7yW

```

```
def render(assigns) do
    ~H"""
    <div phx-target={@myself} class="flex flex-col space-y-4 bg-white rounded p-4">
      <.form phx-target={@myself}>
        <div phx-target={@myself} class="flex-shrink-0 w-full h-64 relative overflow-hidden">
          <div
            phx-target={@myself}
            id={"#{assigns.id}-upload"}
            class="bg-checkerboard p-2 absolute inset-0"
          >
            <img
              phx-target={@myself}
              src={@image_url}
              alt="Preview"
              class="object-contain object-center w-full h-full"
            />
            <div phx-target={@myself} class="">
              <div
                class="absolute inset-0 bg-black bg-opacity-50 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity duration-300"
                phx-drop-target={@uploads.photo.ref}
                phx-target={@myself}
              >
                <div class="">
                  <.live_file_input
                    phx-target={@myself}
                    id={"#{assigns.id}-file-input"}
                    class="hidden"
                    upload={@uploads.photo}
                  />
                  <label
                    for={@uploads.photo.ref}
                    phx-target={@myself}
                    class="bg-blue-500 text-white px-4 py-2 cursor-pointer hover:bg-blue-600 rounded"
                  >
                    Upload File or Drag and Drop
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>
      </.form>
    </div>
    """
  end
```

**Comment by josevalim** [comment]
Can you please provide a minimal app? You can use this as a starting point: https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix_live_view.exs

**Comment by spunkedy** [comment]
> Can you please provide a minimal app? You can use this as a starting point: https://github.com/wojtekmach/mix_install_examples/blob/main/phoenix_live_view.exs

absolutely, will do this later tonight

**Comment by spunkedy** [comment]
Here is the gist https://gist.github.com/spunkedy/5e50acb246411f0df2e8f56e2c410c2f

However, in copying the code over and reducing it. The problem only presents in a nested html `form` element.

So I would say based upon the spec, https://html.spec.whatwg.org/multipage/forms.html#the-form-element it doesn't make sense to support nested forms here. Will close.
