### ISSUE TITLE
render_upload with multiples files crash

### ISSUE THREAD

**Issue by Matsa59** [phoenixframework/phoenix_live_view#2898]
### Environment

* Elixir version (elixir -v): a.1.15.4
* Phoenix version (mix deps): 1.7.9
* Phoenix LiveView version (mix deps): 0.19.5
* Operating system: Pop OS 22
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave (chromium)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

```elixir
    test "upload multiple images", %{view: view} do
      render_submit(view, :open, %{"multi-images" => true, "locale" => "en"})

      # at this point we don't care about the data
      file1 = %{name: "myfile.jpg", content: "a", type: "image/jpg"}
      file2 = %{name: "myfile2.jpg", content: "b",type: "image/jpg"}

      images = file_input(view, "#upload-images-form", :images, [file1, file2])

      # This one works fine
      assert render_upload(images, "myfile.jpg")
      # This one crash 
      assert render_upload(images, "myfile2.jpg")
    end
```

For the LV part:

```elixir
  defp handle_progress(:images, _entry, socket) do
    {completed, in_progress} = uploaded_entries(socket, :images)

    if Enum.all?(in_progress, & &1.cancelled?) do
      images =
        for entry <- completed do
          consume_uploaded_entry(socket, entry, fn %{path: path} ->
            Core.Assets.upload_image(entry.client_name, path)
          end)
        end

        # we don't really care about the rest of the code
    end
    |> then(&{:noreply, &1})
  end

```

<details>
  <summary>Stacktrace</summary>

```
18:20:23.470 [error] GenServer #PID<0.846.0> terminating
** (FunctionClauseError) no function clause matching in Phoenix.LiveView.UploadChannel.handle_info/2
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/upload_channel.ex:122: Phoenix.LiveView.UploadChannel.handle_info({:
EXIT, #PID<0.845.0>, {:shutdown, :closed}}, %Phoenix.Socket{assigns: %{writer: Phoenix.LiveView.UploadTmpFileWriter, max_
file_size: 8571, done?: true, chunk_timeout: 10000, chunk_timer: nil, writer_state: %{file: #PID<0.847.0>, path: "/tmp/pl
ug-1698/live_view_upload-1698704423-926903667376-2"}, writer_closed?: true, uploaded_size: 8571, live_view_pid: #PID<0.84
4.0>}, channel: Phoenix.LiveView.UploadChannel, channel_pid: #PID<0.846.0>, endpoint: ShellWeb.Endpoint, handler: Phoenix
.LiveView.Socket, id: nil, joined: true, join_ref: 2052, private: %{log_handle_in: false, log_join: :info, connect_info: 
%{}}, pubsub_server: CMS.PubSub, ref: nil, serializer: Phoenix.ChannelTest.NoopSerializer, topic: "lvu:123", transport: {
Phoenix.ChannelTest, #PID<0.842.0>}, transport_pid: #PID<0.845.0>})
    (phoenix 1.7.9) lib/phoenix/channel/server.ex:358: Phoenix.Channel.Server.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.845.0>, {:shutdown, :closed}}
18:20:23.482 [error] GenServer #PID<0.844.0> terminating
** (stop) exited in: GenServer.call(#PID<0.846.0>, :consume_done, :infinity)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.UploadChannel.handle_info/2
            (phoenix_live_view 0.19.5) lib/phoenix_live_view/upload_channel.ex:122: Phoenix.LiveView.UploadChannel.handle
_info({:EXIT, #PID<0.845.0>, {:shutdown, :closed}}, %Phoenix.Socket{assigns: %{writer: Phoenix.LiveView.UploadTmpFileWrit
er, max_file_size: 8571, done?: true, chunk_timeout: 10000, chunk_timer: nil, writer_state: %{file: #PID<0.847.0>, path: 
"/tmp/plug-1698/live_view_upload-1698704423-926903667376-2"}, writer_closed?: true, uploaded_size: 8571, live_view_pid: #
PID<0.844.0>}, channel: Phoenix.LiveView.UploadChannel, channel_pid: #PID<0.846.0>, endpoint: ShellWeb.Endpoint, handler:
 Phoenix.LiveView.Socket, id: nil, joined: true, join_ref: 2052, private: %{log_handle_in: false, log_join: :info, connec
t_info: %{}}, pubsub_server: CMS.PubSub, ref: nil, serializer: Phoenix.ChannelTest.NoopSerializer, topic: "lvu:123", tran
sport: {Phoenix.ChannelTest, #PID<0.842.0>}, transport_pid: #PID<0.845.0>})
            (phoenix 1.7.9) lib/phoenix/channel/server.ex:358: Phoenix.Channel.Server.handle_info/2
            (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
            (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
            (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
    (elixir 1.15.4) lib/gen_server.ex:1074: GenServer.call/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/upload_channel.ex:26: Phoenix.LiveView.UploadChannel.consume/3
    (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/upload.ex:260: Phoenix.LiveView.Upload.consume_uploaded_entry/3
    (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (core 0.1.0) lib/core_web/live/assets/image_selector.ex:41: CoreWeb.Assets.ImageSelector.handle_progress/3
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:156: anonymous fn/4 in Phoenix.LiveView.Channel.handle_in
fo/2
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:1278: Phoenix.LiveView.Channel.write_socket/4
    (phoenix_live_view 0.19.5) lib/phoenix_live_view/channel.ex:149: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F5MCrD-41V8TmgXD", event: "progress", payload: %{"entry_ref" => "18
0", "progress" => 100, "ref" => "phx-F5MCrEXtraxAyAcD"}, ref: "4", join_ref: 0}
18:20:23.486 [error] GenServer #PID<0.842.0> terminating
** (stop) exited in: GenServer.call(#PID<0.844.0>, {:phoenix, :ping}, :infinity)
    ** (EXIT) exited in: GenServer.call(#PID<0.846.0>, :consume_done, :infinity)
        ** (EXIT) an exception was raised:
            ** (FunctionClauseError) no function clause matching in Phoenix.LiveView.UploadChannel.handle_info/2
                (phoenix_live_view 0.19.5) lib/phoenix_live_view/upload_channel.ex:122: Phoenix.LiveView.UploadChannel.h
ndle_info({:EXIT, #PID<0.845.0>, {:shutdown, :closed}}, %Phoenix.Socket{assigns: %{writer: Phoenix.LiveView.UploadTmpFil
Writer, max_file_size: 8571, done?: true, chunk_timeout: 10000, chunk_timer: nil, writer_state: %{file: #PID<0.847.0>, p
th: "/tmp/plug-1698/live_view_upload-1698704423-926903667376-2"}, writer_closed?: true, uploaded_size: 8571, live_view_p
d: #PID<0.844.0>}, channel: Phoenix.LiveView.UploadChannel, channel_pid: #PID<0.846.0>, endpoint: ShellWeb.Endpoint, han
ler: Phoenix.LiveView.Socket, id: nil, joined: true, join_ref: 2052, private: %{log_handle_in: false, log_join: :info, c
nnect_info: %{}}, pubsub_server: CMS.PubSub, ref: nil, serializer: Phoenix.ChannelTest.NoopSerializer, topic: "lvu:123",
transport: {Phoenix.ChannelTest, #PID<0.842.0>}, transport_pid: #PID<0.845.0>})
                (phoenix 1.7.9) lib/phoenix/channel/server.ex:358: Phoenix.Channel.Server.handle_info/2
                (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
                (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
                (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.839.0>, {{{:function_clause, [{Phoenix.LiveView.UploadChannel, :handle_info, [{:EXIT, #PID<
.845.0>, {:shutdown, :closed}}, %Phoenix.Socket{assigns: %{writer: Phoenix.LiveView.UploadTmpFileWriter, max_file_size: 
571, done?: true, chunk_timeout: 10000, chunk_timer: nil, writer_state: %{file: #PID<0.847.0>, path: "/tmp/plug-1698/liv
_view_upload-1698704423-926903667376-2"}, writer_closed?: true, uploaded_size: 8571, live_view_pid: #PID<0.844.0>}, chan
el: Phoenix.LiveView.UploadChannel, channel_pid: #PID<0.846.0>, endpoint: ShellWeb.Endpoint, handler: Phoenix.LiveView.S
cket, id: nil, joined: true, join_ref: 2052, private: %{log_handle_in: false, log_join: :info, connect_info: %{}}, pubsu
_server: CMS.PubSub, ref: nil, serializer: Phoenix.ChannelTest.NoopSerializer, topic: "lvu:123", transport: {Phoenix.Cha
nelTest, #PID<0.842.0>}, transport_pid: #PID<0.845.0>}], [file: ~c"lib/phoenix_live_view/upload_channel.ex", line: 122]}
 {Phoenix.Channel.Server, :handle_info, 2, [file: ~c"lib/phoenix/channel/server.ex", line: 358]}, {:gen_server, :try_han
le_info, 3, [file: ~c"gen_server.erl", line: 1077]}, {:gen_server, :handle_msg, 6, [file: ~c"gen_server.erl", line: 1165
}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}, {GenServer, :call, [#PID<0.846.0>, :consume_
one, :infinity]}}, {GenServer, :call, [#PID<0.844.0>, {:phoenix, :ping}, :infinity]}}}
```
</details>

Maybe I do something wrong but it work well for "real / human" tests

**Comment by chrismccord** [comment]
If you can provide a minimal reproduction of this issue, including your LiveView, I would be happy to dig further, but everything is working as expected on [our own tests](https://github.com/phoenixframework/phoenix_live_view/blob/68c3148df05da5c4b66ab935c070563403067405/test/phoenix_live_view/upload/channel_test.exs#L250-L251) which use multiple files. Thanks!
