### ISSUE TITLE
Enumerable Error in Phoenix.LiveViewTest.live/2 call after upgrade

### ISSUE THREAD

**Issue by hattmarris** [phoenixframework/phoenix_live_view#3141]
### Environment

* Elixir version (elixir -v): Elixir 1.16.0 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): phoenix 1.7.11
* Phoenix LiveView version (mix deps): phoenix_live_view 0.20.11
* Operating system: Ubuntu 20.04.6 LTS
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior
 
After our upgrade to `0.20.10` (and still after patch v. `0.20.11`) we noticed 3 tests break that use the `Phoenix.LiveViewTest.live/2` code pathway -- Looking at the diff from `0.20.9` I'm wondering if c712dfedfc29b92c3c215cd3dae7a6abefce9b50 may have introduced this with the call to Enum.reduce/3?

```
     test/app_web/live/org_live_test.exs:16
     ** (EXIT from #PID<0.516.0>) an exception was raised:
         ** (Protocol.UndefinedError) protocol Enumerable not implemented for ~U[2024-01-30 05:00:00Z] of type DateTime (a struct). This protocol is implemented for the following type(s): DBConnection.Pr
epareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Phoen
ix.LiveView.LiveStream, Postgrex.Stream, Range, Stream, Table.Mapper, Table.Zipper
             (elixir 1.16.0) lib/enum.ex:1: Enumerable.impl_for!/1
             (elixir 1.16.0) lib/enum.ex:166: Enumerable.reduce/3
             (elixir 1.16.0) lib/enum.ex:4399: Enum.reduce/3
             (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
             (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
             (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
             (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
             (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
             (phoenix_live_view 0.20.11) lib/phoenix_live_view/test/dom.ex:198: Phoenix.LiveViewTest.DOM.merge_diff/2
             (phoenix_live_view 0.20.11) lib/phoenix_live_view/test/client_proxy.ex:194: Phoenix.LiveViewTest.ClientProxy.mount_view/4
             (phoenix_live_view 0.20.11) lib/phoenix_live_view/test/client_proxy.ex:150: Phoenix.LiveViewTest.ClientProxy.init/1
             (stdlib 5.0.2) gen_server.erl:962: :gen_server.init_it/2
             (stdlib 5.0.2) gen_server.erl:917: :gen_server.init_it/6
             (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

When I comment out the call to `live/2` or rollback our tests pass.

**Comment by hattmarris** [comment]
Thanks for the quick look @SteffenDE :raised_hands: I just checked out your branch `{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "extract_streams_check_struct", override: true}` and can confirm our tests pass with this additional guard in place. 

I wish I had been able to determine where in the view this struct was getting rendered... but it's a rather large view and in some debugging none of our fixture structs had any fields this exact DateTime struct... so I'm still a bit curious as to what we've got going on our end as well :thinking:
