### ISSUE TITLE
live_file_input is (possibly) broken

### ISSUE THREAD

**Issue by mendrik** [phoenixframework/phoenix_live_view#3190]
### Environment

* Elixir version (elixir -v):  Elixir 1.16.1
* Phoenix version (mix deps): {:phoenix, "~> 1.7.11"},
* Phoenix LiveView version (mix deps): {:phoenix_live_view, "~> 0.20.13"},
* Operating system: wsl2 Ubuntu 22.04.4 LTS
* Browsers you attempted to reproduce this bug on (the more the merrier): chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
Getting this error when trying to run my code.
![image](https://github.com/phoenixframework/phoenix_live_view/assets/160805/ce6834f2-41c5-4cae-bbbd-85ff7a009098)

I have a live_component like so

```elixir
defmodule AlbumWeb.PhotosetLive do
  use AlbumWeb, :live_component
  require Logger

  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> assign(:uploaded_files, [])
     |> allow_upload(:photoset, accept: ~w(.jpg .jpeg .png .webp), max_entries: 7)}
  end

  def handle_event("validate", _params, socket) do
    {:noreply, socket}
  end

  def handle_event("save", _params, socket) do
    uploaded_files =
      consume_uploaded_entries(socket, :photoset, fn %{path: path}, _entry ->
        dest = Path.join("priv/static/uploads", Path.basename(path))
        IO.puts(path <> " -> " <> dest)
      end)

    {:noreply, update(socket, :uploaded_files, &(&1 ++ uploaded_files))}
  end

  attr :page, :integer, required: true
  attr :album, Album.Album, required: true

  def render(assigns) do
    ~H"""
        <form id="upload-form" phx-submit="save" phx-change="validate">
          <%= live_file_input(@uploads.photoset) %>
          <button type="submit">Upload</button>
        </form>
    """
  end
end
```

When I remove the line with `live_file_input` it renders fine. Maybe side note, I have multiple of these components used in the same live_view like so
```elixir
<%= for page <- 1..(@pages_per_album - 1) do %>
          <PageComponents.photo_page page={page}>
            <:front>
              <.live_component
                module={AlbumWeb.PhotosetLive}
                id={page * 2}
                page={page * 2}
                album={@album}
              />
            </:front>
            <:back>
              <.live_component
                module={AlbumWeb.PhotosetLive}
                id={page * 2 + 1}
                page={page * 2 + 1}
                album={@album}
              />
            </:back>
          </PageComponents.photo_page>
        <% end %>
```

### Expected behavior

Following the docs with this code: https://hexdocs.pm/phoenix_live_view/uploads.html#allow-uploads

**Comment by chrismccord** [comment]
Live components support `mount/1` and `update/2`. You want your allow_upload to be in mount/1. Note that using elixir's `@imple true` or `@impl Phoenix.LiveComponent` would give you compiler warnings for things like this :) Thanks!

**Comment by mendrik** [comment]
sorry for wasting your time, i did the suggested changes but getting still an error from live_file_unput
```
[error] GenServer #PID<0.5154.0> terminating
** (ArgumentError) assign/3 expects a socket from Phoenix.LiveView/Phoenix.LiveComponent  or an assigns map from Phoenix.Component as first argument, got: %{accept: ".jpg,.jpeg,.png,.webp", __given__: %{accept: ".jpg,.jpeg,.png,.webp"}}You passed an assigns map that does not have the relevant change tracking information. This typically means you are calling a function component by hand instead of using the HEEx template syntax. If you are using HEEx, make sure you are calling a component using:

    <.component attribute={value} />

If you are outside of HEEx and you want to test a component, use Phoenix.LiveViewTest.render_component/2:

    Phoenix.LiveViewTest.render_component(&component/1, attribute: "value")


    (phoenix_live_view 0.20.14) lib/phoenix_component.ex:1256: Phoenix.Component.raise_bad_socket_or_assign!/2
    (phoenix_live_view 0.20.14) lib/phoenix_component.ex:1: Phoenix.Component.live_file_input/1
    (album 0.1.0) lib/album_web/live/photoset_live.ex:34: anonymous fn/2 in AlbumWeb.PhotosetLive.render/1
````

which changes like so:
```elixir
  @impl true
  def update(assigns, socket) do
    {:ok,
     socket
     |> assign(assigns)
     |> assign(:uploaded_files, [])
     |> allow_upload(:photoset, accept: ~w(.jpg .jpeg .png .webp), max_entries: 7)}
  end
  ```

**Comment by chrismccord** [comment]
You need to use live_file_input as a HEEx function component call, rather than calling it directly inside `<%= %>`, so you want `<.live_file_input upload={@uploads.photoset) />`. Check the docs for more examples!

**Comment by mendrik** [comment]
you're the best! thanks a lot, works now. problem was between keyboard and chair after all!
