### ISSUE TITLE
LiveView crashes on a change in a checkboxes collection

### ISSUE THREAD

**Issue by hurty** [phoenixframework/phoenix_live_view#324]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.9
* NodeJS version (node -v): v11.14.0
* NPM version (npm -v): 6.9.0
* Operating system: MacOS 10.14.6

### Actual behavior

The LiveView crashes because the new `_target` metadata cannot be decoded correctly when the input which triggered the change is in a collection of checkboxes having the same `name` attribute (ending with `[]`).

```eex
<form phx-change="update_administrators">
  <%= for member <- @members do %>
    <input type="checkbox" name="admins[]" value="<%= member.id %>" 
      <%= if member.role == :admin do %>checked<% end %> 
    >
  <% end %>
</form>
```

```
[error] GenServer #PID<0.598.0> terminating
** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Channel.gather_keys/2
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:272: Phoenix.LiveView.Channel.gather_keys([], ["admins"])
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:266: Phoenix.LiveView.Channel.decode_merge_target/1
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:78: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "1", payload: %{"event" => "update_administrators", "type" => "form", "value" => "admins%5B%5D=b5155f17-5c12-4db7-8a87-bc8c1941ade6&admins%5B%5D=523bb397-b562-4464-a721-36affb720aab&_target=admins%5B%5D"}, ref: "2", topic: "lv:phx-1bW3sdGB"}
```

### Expected behavior

The `_target` param should work with input collections and the LiveView shouldn't crash.

**Comment by chrismccord** [comment]
Fixed on master. Thanks!

**Comment by gushonorato** [comment]
I'm having similar issue, but with an input with `name="order_item[addons][][name]"`.

```
** (FunctionClauseError) no function clause matching in Phoenix.LiveView.Channel.gather_keys/2
    (phoenix_live_view 0.14.2) lib/phoenix_live_view/channel.ex:403: Phoenix.LiveView.Channel.gather_keys([%{"name" => nil}], ["addons", "order_item"])
    (phoenix_live_view 0.14.2) lib/phoenix_live_view/channel.ex:397: Phoenix.LiveView.Channel.decode_merge_target/1
    (phoenix_live_view 0.14.2) lib/phoenix_live_view/channel.ex:87: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.11.2) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.11.2) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.11.2) proc_lib.erl:259: :proc_lib.wake_up/3
```
