### ISSUE TITLE
Race condition when testing mulitple file upload

### ISSUE THREAD

**Issue by lessless** [phoenixframework/phoenix_live_view#3480]
### Environment

* Elixir version (elixir -v): 1.17.3
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps):  1.0.0-rc.7
* Operating system: macos
* Browsers you attempted to reproduce this bug on (the more the merrier):  n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

### Actual behavior

The second `render_upload` raises an error when I try to test multiple files upload

```elixir
defp handle_progress(:documents, %{done?: true}, socket) do
    case uploaded_entries(socket, :documents) do
      {[_ | _] = _completed, []} ->
        
      consume_uploaded_entries(socket, :documents, fn %{path: path}, entry ->
          :ok = upload_file(entry, path, socket.assigns.current_practice) 
          {:ok, entry}
        end)
        
        {:noreply, start_async(socket, :fetch_documents, fn -> documents_data() end)}

      _in_progress ->
        {:noreply, socket}
    end
  end

  defp handle_progress(:documents, %{done?: false}, socket) do
    {:noreply, socket}
  end
```

```elixir
test "can upload multiple documents", %{conn: conn, practice: practice} do
  {:ok, view, _html} = live(conn, ~p"/upload")
  render_async(view)
  
  documents =
    file_input(view, "#manual-document-upload-form", :documents, [
      %{
        last_modified: 1_594_171_879_000,
        name: "a document.tif",
        content: <<73, 73, 42, 0, 8, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0>>,
        size: 16,
        type: "image/tiff"
      },
      %{
        last_modified: 1_594_171_879_000,
        name: "another document.tif",
        content: <<73, 73, 42, 0, 8, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0>>,
        size: 16,
        type: "image/tiff"
      }
    ])

  render_upload(documents, "a document.tif")
  IO.puts "after first render_upload"
 
  render_upload(documents, "another document.tif")
  IO.puts "after second render_upload"

  view
  |> test_id("view-action-items-checkbox")
  |> render_click()

  assert render_async(view) =~ "successfully uploaded"
end
```

the "after second render_uploa" is never printed the test fails with the error

```elixir


11:31:36.156 [error] GenServer #PID<0.681.0> terminating
** (stop) exited in: GenServer.call(#PID<0.689.0>, :consume_done, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.17.3) lib/gen_server.ex:1128: GenServer.call/3
    (phoenix_live_view 0.20.17) lib/phoenix_live_view/upload_channel.ex:26: Phoenix.LiveView.UploadChannel.consume/3
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.17.3) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (mailroom 0.1.0) lib/mailroom_web/live/list_views/pages/upload_live.ex:186: MailroomWeb.UploadLive.handle_progress/3
    (phoenix_live_view 0.20.17) lib/phoenix_live_view/channel.ex:181: anonymous fn/4 in Phoenix.LiveView.Channel.handle_info/2
    (phoenix_live_view 0.20.17) lib/phoenix_live_view/channel.ex:1422: Phoenix.LiveView.Channel.write_socket/4
    (phoenix_live_view 0.20.17) lib/phoenix_live_view/channel.ex:174: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 6.1.2) gen_server.erl:2345: :gen_server.try_handle_info/3
    (stdlib 6.1.2) gen_server.erl:2433: :gen_server.handle_msg/6
    (stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-GAEOVlW_stZitAlC", event: "progress", payload: %{"entry_ref" => "2819", "progress" => 100, "ref" => "phx-GAEOVmA5Q6Fv-Api"}, ref: "5", join_ref: 0}
11:31:36.168 [error] GenServer #PID<0.679.0> terminating
** (stop) exited in: GenServer.call(#PID<0.681.0>, {:phoenix, :ping}, :infinity)
    ** (EXIT) exited in: GenServer.call(#PID<0.689.0>, :consume_done, :infinity)
        ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
Last message: {:EXIT, #PID<0.643.0>, {{:noproc, {GenServer, :call, [#PID<0.689.0>, :consume_done, :infinity]}}, {GenServer, :call, [#PID<0.681.0>, {:phoenix, :ping}, :infinity]}}}


  1) test can upload multiple documents (MailroomWeb.ListViews.Pages.Dyad.PreparingListPageLiveTest)
     test/mailroom_web/live/list_views/pages/dyad/preparing_list_page_live_test.exs:248
     ** (EXIT from #PID<0.643.0>) exited in: GenServer.call(#PID<0.681.0>, {:phoenix, :ping}, :infinity)
         ** (EXIT) exited in: GenServer.call(#PID<0.689.0>, :consume_done, :infinity)
             ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started

```

### Expected behavior

I can test multiple file upload

**Comment by dersmon** [comment]
I got the same issue when using `file_input/4` with more than one entry.  Slight difference in that I see the "Second upload" message and I use `render_submit/1` on the form:

```elixir
(...)

upload_input =
  file_input(process, "#upload-form", :images, [
    %{
      last_modified: 1_594_171_879_000,
      name: "valid_file_a.jpg",
      content: "dummy file content"
    },
    %{
      last_modified: 1_594_171_879_000,
      name: "valid_file_b.jpg",
      content: "dummy file content"
    }
  ])

render_upload(upload_input, "valid_file_a.jpg")
IO.inspect("First upload")
render_upload(upload_input, "valid_file_b.jpg")
IO.inspect("Second upload")

process
|> form("#upload-form", [])
|> render_submit()

(...)
```

My error message:

```
"First upload"
"Second upload"
14:05:17.694 [error] GenServer #PID<0.408.0> terminating
** (stop) exited in: GenServer.call(#PID<0.419.0>, :consume_start, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.17.2) lib/gen_server.ex:1128: GenServer.call/3
    (phoenix_live_view 1.0.0-rc.6) lib/phoenix_live_view/upload_channel.ex:15: Phoenix.LiveView.UploadChannel.consume/3
    (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (my_app 1.0.0-rc3) lib/my_app_web/live/archive_upload_component.ex:131: MyAppWeb.ArchiveUploadComponent.handle_event/3
    (phoenix_live_view 1.0.0-rc.6) lib/phoenix_live_view/channel.ex:741: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.3.0) </path/to/project/>deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (phoenix_live_view 1.0.0-rc.6) lib/phoenix_live_view/diff.ex:209: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 1.0.0-rc.6) lib/phoenix_live_view/channel.ex:662: Phoenix.LiveView.Channel.component_handle/4
    (stdlib 6.0.1) gen_server.erl:2173: :gen_server.try_handle_info/3
    (stdlib 6.0.1) gen_server.erl:2261: :gen_server.handle_msg/6
    (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-GAM8yUEFIExknAEl", event: "event", payload: %{"cid" => 3, "event" => "submit_selected_images", "type" => "form", "value" => "images="}, ref: "4", join_ref: 0}
14:05:17.764 [error] GenServer #PID<0.406.0> terminating
** (stop) exited in: GenServer.call(#PID<0.419.0>, :consume_start, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
Last message: {:EXIT, #PID<0.403.0>, {:noproc, {GenServer, :call, [#PID<0.419.0>, :consume_start, :infinity]}}}
```

**Comment by chrismccord** [comment]
@lessless can you share your full example. Looks like you're using `auto_upload: true`? I need to dig in deeper, but at first glance, you are auto uploader both files and then calling `consume_uploaded_entries` when you see one is finished, which will consume *all* completed entries. I think what you wanted there was `consume_uploaded_entry`. I think you're consuming and nuking the 2nd one before you try to `render_upload` it in the test.
