### ISSUE TITLE
Formatter removing part of gettext while applying curly braces

### ISSUE THREAD

**Issue by Terbium-135** [phoenixframework/phoenix_live_view#3557]
### Environment

* Elixir version (elixir -v): **Elixir 1.17.3 (compiled with Erlang/OTP 27)**
* Phoenix version (mix deps): **latest commit from main as of 2024-12-06 commit: 5e62a39**
* Phoenix LiveView version (mix deps): **latest commit from main as of 2024-12-06 commit: e8507cc**
* Operating system: **Linux**

### Actual behavior
Given this:
```
<div class="pl-8 opacity-60">
     <%= gettext("Customer data") %> ➜ <%= gettext("Show pending orders") %>:
</div>
```

the interpolation into curly braces gives (removing part of the gettext and placing the braces at the wrong positions/not removing the old code completely):
```
<div class="pl-8 opacity-60">
  {gettext("Customer data")} ➜ <%{ttext("Show pending orders") %}
</div>
```

and the compilation fails with:
```
== Compilation error in file lib/backend_web/live/tabbed_location_edit_live.ex ==
** (SyntaxError) invalid syntax found on lib/backend_web/live/tabbed_location_edit_live.ex:926:111:
     error: unexpected token: "➜" (column 111, code point U+279C)
     │
 926 │ ...                   {gettext("Customer data")} ➜ <%{ttext("Show orders") %}
     │                                                  ^
     │
     └─ lib/backend_web/live/tabbed_location_edit_live.ex:926:111
    (eex 1.17.3) lib/eex/compiler.ex:332: EEx.Compiler.generate_buffer/4
    (phoenix_live_view 1.0.0) expanding macro: Phoenix.Component.sigil_H/2
    (backend 0.45.1) lib/backend_web/live/tabbed_location_edit_live.ex:72: BackendWeb.TabbedLocationEditLive.render/1

```

**Perhaps the reason might be the unicode character ?**

**Comment by krns** [comment]
I think it's a duplicate of #3555

**Comment by josevalim** [comment]
Hi @Terbium-135, unfortunately I cannot reproduce this crash. :( Do you have a simple app that reproduces this? Thank you!

**Comment by Terbium-135** [comment]
Can't reproduce either while I was preparing a demo file...
Guess it was a glitch
Closing for now

**Comment by josevalim** [comment]
If it comes back, let us know!

**Comment by josevalim** [comment]
Is it back? Can you give us an example how to reproduce it? :)
