### ISSUE TITLE
Problem parsing LiveView with embedded XML.

### ISSUE THREAD

**Issue by tomekowal** [phoenixframework/phoenix_live_view#3594]
### Environment

* Elixir version (elixir -v): Elixir 1.16.3 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): 1.7.18
* Phoenix LiveView version (mix deps): 1.0.1
* Operating system: Mac OS 15.1.1
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A it is in `mix test`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A it is during MIX_ENV=test

### Actual behavior

After upgrade to LiveView 1.0.1
In the test code, I am running:
```
        assert {:ok, _view, _html} =
                 live_isolated(conn, ConsumerScanLandingPageLive,
                   session: %{
                     "qr_code" => checkin_code,
                     "charge" => authorization,
                     "locale" => "en_US"
                   }
                 )
```
I get the following error:
```
     apps/acqui_base/test/acqui_base_web/live/callback_api/consumer_scan_landing_page_live_test.exs:19
     ** (EXIT from #PID<0.1088.0>) an exception was raised:
         ** (Protocol.UndefinedError) protocol Enumerable not implemented for "xml" of type BitString. This protocol is implemented for the following type(s): AcquiBase.Service.Processor.ChargeRequest, DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Phoenix.LiveView.LiveStream, Postgrex.Stream, Range, Stream, StreamData, Timex.Interval
             (elixir 1.16.3) lib/enum.ex:1: Enumerable.impl_for!/1
             (elixir 1.16.3) lib/enum.ex:166: Enumerable.reduce/3
             (elixir 1.16.3) lib/enum.ex:1162: Enum.find/3
             (floki 0.37.0) lib/floki.ex:716: anonymous fn/3 in Floki.attribute_values/2
             (elixir 1.16.3) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
             (floki 0.37.0) lib/floki.ex:711: Floki.attribute_values/2
             (phoenix_live_view 1.0.1) lib/phoenix_live_view/test/dom.ex:45: Phoenix.LiveViewTest.DOM.detect_duplicate_ids/2
             (phoenix_live_view 1.0.1) lib/phoenix_live_view/test/dom.ex:40: Phoenix.LiveViewTest.DOM.detect_duplicate_ids/2
             (phoenix_live_view 1.0.1) lib/phoenix_live_view/test/dom.ex:30: Phoenix.LiveViewTest.DOM.parse/1
             (phoenix_live_view 1.0.1) lib/phoenix_live_view/test/client_proxy.ex:90: Phoenix.LiveViewTest.ClientProxy.init/1
             (stdlib 5.2.3) gen_server.erl:980: :gen_server.init_it/2
             (stdlib 5.2.3) gen_server.erl:935: :gen_server.init_it/6
             (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

### Expected behavior

Previously, the code run without issues.

### Attempted debugging

The LiveView in question embeds XML in the following way:

```
<div id="phx-GBMuKaI5JD8WKhYB" data-phx-session="...">
  ...
  <?xml version="1.0" standalone="yes"?>
  ...
</div>
```

The embedded xml creates a node like this in Floki:

```
{:pi, "xml", [{"version", "1.0"}, {"standalone", "yes"}]}
```

Then calling this https://github.com/phoenixframework/phoenix_live_view/blob/main/lib/phoenix_live_view/test/dom.ex#L41 on that node causes an error.

I am not yet sure, if this is a Floki issue (e.g. if that functions should work for `:pi` node) or if it is LiveView issue (e.g. LiveView should handle `:pi` nodes in some different way and not call that function at all).

Please let me know if it is the wrong repo, so I can open the issue in Floki.

**Comment by SteffenDE** [comment]
Thank you for reporting! 🙌🏻

**Comment by tomekowal** [comment]
Wow! That's a lightning fast response! Thank you 🙏
