### ISSUE TITLE
Crash when returning {:stop, socket} from handle_params/3

### ISSUE THREAD

**Issue by lukaszsamson** [phoenixframework/phoenix_live_view#361]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.4.10
* phoenix_live_view version (mix deps): f1ac0a2455bb8064dc2ebbb47bf0d2ebabcf1062
* NodeJS version (node -v): v12.4.0
* NPM version (npm -v): 6.9.0
* Operating system: macos 10.14.6

### Actual behavior

When client is connecting to a live view with params validation and provides invalid prarams resulting in {:stop, socket} resturn
```
def handle_params(%{"my_param" => my_param}, _uri, socket) do
    if valid?(my_param) do
      {:noreply, socket}
    else
      {:stop, socket}
    end
end
```
live view channel crashes with
```
10:47:20.043 [error] GenServer #PID<0.569.0> terminating
** (CaseClauseError) no case clause matching: :noop
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:202: Phoenix.LiveView.Channel.mount_handle_params_result/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:474: Phoenix.LiveView.Channel.verified_mount/10
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
10:47:20.043 [error] an exception was raised:
    ** (CaseClauseError) no case clause matching: :noop
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:202: Phoenix.LiveView.Channel.mount_handle_params_result/4
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:474: Phoenix.LiveView.Channel.verified_mount/10
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

### Expected behavior
No crash and error page rendered.

**Comment by josevalim** [comment]
That's because you cannot just stop, you have to redirect somewhere. We will improve the error message.
