### ISSUE TITLE
MatchError... Last message: {:mount, Phoenix.LiveView.Channel}

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [phoenixframework/phoenix_live_view#428]
### Environment

* image: elixir:1.9.2-alpine
    - apk add --update npm
    - mix deps.get --only prod
    - npm install --prefix ./assets
    - npm run build --prefix ./assets
    - mix phx.digest priv/static
    - mix release

*   {:phoenix, "~> 1.4.10"},
*   {:phoenix_pubsub, "~> 1.1"},
*   {:phoenix_html, "~> 2.11"},
*   {:phoenix_live_view, "~> 0.3.0"},

### Actual behavior

After updating phoenix_live_view to 0.3.0 a remote docker container running a release started reporting errors continuously.
I experience no problems whatsoever when running locally on my development server: `MIX_ENV=dev iex -S mix phx.server`.
It looks like Phoenix is trying to mount a channel continuously and keeps on failing.
While requesting pages in the mean time works fine and also the liveview websocket works fine.

In the below error messages you can see:
```
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
```
Which would indeed fail looking at the source code:
```
  defp verified_mount(verified, params, from, phx_socket) do
    %{
      id: id,
      view: view,
      parent_pid: parent,
      root_pid: root,
      session: session,
      assigned_new: assigned_new
    } = verified
```
Because the incoming "right hand side value" is:
```
%{
  id: "phx-mAf+0t5u",
  view: MyAppWeb.Live.ModuleUsingLiveView,
  parent_pid: nil,
  router: MyAppWeb.Router,
  session: %{"cookies_active" => true, "custom_param" => "309098"},
  assigned_new: [], 
}
```
So there's no `root_pid`, instead there's a `router`.

```
12:59:32.351 [info] Running MyAppWeb.Endpoint with cowboy 2.7.0 at :::8084 (http)
12:59:32.741 [info] CONNECTED TO Phoenix.LiveView.Socket in 228µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{}
  Parameters: %{"vsn" => "2.0.0"}
12:59:32.756 [error] GenServer #PID<0.1727.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
12:59:32.757 [error] an exception was raised:
    ** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
        (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
12:59:34.692 [error] GenServer #PID<0.1728.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
12:59:34.692 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
12:59:36.164 [info] tzdata release in place is from a file last modified Tue, 26 Mar 2019 05:40:14 GMT. Release file on server was last modified Wed, 11 Sep 2019 19:35:17 GMT.
12:59:37.691 [error] GenServer #PID<0.1736.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
12:59:37.691 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
12:59:38.386 [info] Tzdata has updated the release from 2019a to 2019c
12:59:43.691 [error] GenServer #PID<0.1741.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
12:59:43.691 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
12:59:54.691 [error] GenServer #PID<0.1742.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
12:59:54.692 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
13:00:05.693 [error] GenServer #PID<0.1743.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
13:00:05.693 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
13:00:16.691 [error] GenServer #PID<0.1744.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
13:00:16.692 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
13:00:27.693 [error] GenServer #PID<0.1745.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
13:00:27.693 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
13:00:38.692 [error] GenServer #PID<0.1746.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
13:00:38.692 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
13:00:49.691 [error] GenServer #PID<0.1747.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
13:00:49.691 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
13:01:00.691 [error] GenServer #PID<0.1748.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
13:01:00.691 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
13:01:05.381 request_id=Fc9cd_xr6rxyYZgAAADR [info] GET /
13:01:05.446 request_id=Fc9cd_xr6rxyYZgAAADR [info] Sent 200 in 64ms
13:01:05.595 [info] CONNECTED TO Phoenix.LiveView.Socket in 297µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{}
  Parameters: %{"timezone" => "Europe/Amsterdam", "vsn" => "2.0.0"}
13:01:11.258 request_id=Fc9ceVq6dqMc3tEAAADx [info] GET /fetching-this-page-works-fine
13:01:11.263 request_id=Fc9ceVq6dqMc3tEAAADx [info] Sent 307 in 5ms
13:01:11.276 request_id=Fc9ceVvHcbNr9N4AAAER [info] GET /this-page-works-fine-too-in-the-browser
13:01:11.277 request_id=Fc9ceVvHcbNr9N4AAAER [info] Sent 200 in 1ms
13:01:11.348 [info] CONNECTED TO Phoenix.LiveView.Socket in 227µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Connect Info: %{}
  Parameters: %{"timezone" => "Europe/Amsterdam", "vsn" => "2.0.0"}
13:01:11.692 [error] GenServer #PID<0.1764.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
13:01:11.692 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
13:01:22.693 [error] GenServer #PID<0.1765.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
13:01:22.693 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
13:01:33.692 [error] GenServer #PID<0.1767.0> terminating
** (MatchError) no match of right hand side value: %{assigned_new: [], id: "phx-mAf+0t5u", parent_pid: nil, router: MyAppWeb.Router, session: %{"cookies_active" => true, "custom_param" => "309098"}, view: MyAppWeb.Live.ModuleUsingLiveView}
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:442: Phoenix.LiveView.Channel.verified_mount/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:28: Phoenix.LiveView.Channel.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
13:01:33.692 [error] no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
^C
```

### Expected behavior

No errors.

**Comment by i-n-g-m-a-r** [comment]
Phoenix.LiveView.Channel.verified_mount/4  seems to have a fix inside the function.
[On line 491](https://github.com/phoenixframework/phoenix_live_view/blob/f12de2780f08a14a4a9d4a868cbbe0a8a49f1bc5/lib/phoenix_live_view/channel.ex#L491) root_pid falls back to self():
`root_pid: root || self(),`

If that were implemented[on line 470](https://github.com/phoenixframework/phoenix_live_view/blob/f12de2780f08a14a4a9d4a868cbbe0a8a49f1bc5/lib/phoenix_live_view/channel.ex#L470) where now it says:
`root_pid: root`

Then probably this should be solved right?

**Comment by chrismccord** [comment]
We now return an `outdated` message to the client when the session experiences a backwards incompatible change, which forces a reload on the client. Thanks!
