### ISSUE TITLE
argument error rendering live view

### ISSUE THREAD

**Issue by brianmay** [phoenixframework/phoenix_live_view#465]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

* Phoenix version (mix deps): 1.1.2
* NodeJS version (node -v): v11.10.1
* NPM version (npm -v): v11.10.1
* Operating system: Nerves on RPI3.

### Actual behavior

This only happens when:

* Run in ``MIX_ENV=prod`` mode.
* Run on RPI3 using Nerves (this really puzzles me).

I cannot reproduce running on Nerves host mode on Intel Debian Buster computer. Or in dev mode.

```
00:08:13.934 [error] #PID<0.745.0> running RoboticaFaceWeb.Endpoint (connection #PID<0.733.0>, stream id 2) terminated
Server: brian.robotica.pri:80 (http)
Request: GET /remote
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.iolist_to_binary(%{__struct__: Phoenix.LiveView.Comprehension, dynamics: [[["\n<button class=\"btn btn-secondary btn-robotica\" phx-click=\"location\" phx-value-location=\"", "Brian", "\" phx-value-set=\"on\">", "Brian", "</button>\n"]], [["\n<button class=\"btn btn-secondary btn-robotica\" phx-click=\"location\" phx-value-location=\"", "Dining", "\" phx-value-set=\"on\">", "Dining", "</button>\n"]], [["\n<button class=\"btn btn-secondary btn-robotica\" phx-click=\"location\" phx-value-location=\"", "Twins", "\" phx-value-set=\"on\">", "Twins", "</button>\n"]], [["\n<button class=\"btn btn-secondary btn-robotica\" phx-click=\"location\" phx-value-location=\"", "Akira", "\" phx-value-set=\"on\">", "Akira", "</button>\n"]]], static: ["\n", "\n"]})
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:273: Phoenix.LiveView.Diff.traverse/5
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:280: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_dynamic/5
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:213: Phoenix.LiveView.Diff.traverse/5
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:83: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view) lib/phoenix_live_view/static.ex:214: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view) lib/phoenix_live_view/static.ex:100: Phoenix.LiveView.Static.render/3
```

Live view template is:

```
    ~L"""
    <%= for row <- @buttons do %>
    <div>
    <div><%= row.name %></div>
    <%= for button <- row.buttons do %>
    <button class="btn btn-primary btn-robotica" phx-click="activate" phx-value-row="<%= row.name %>" phx-value-button="<%= button.name %>"><%= button.name %></button>
    <% end %>
    </div>
    <% end %>
    """
```

I changed the double quotes for the HTML attributes to single quotes (thinking it would lead to an easier to read error report without quoting of the quotes), but that stops the error from occurring.

```
diff --git a/robotica_face/lib/robotica_face_web/live/local.ex b/robotica_face/lib/robotica_face_web/live/local.ex
index eb1b852..965903c 100644
--- a/robotica_face/lib/robotica_face_web/live/local.ex
+++ b/robotica_face/lib/robotica_face_web/live/local.ex
@@ -8,7 +8,7 @@ defmodule RoboticaFaceWeb.Live.Local do
     <div>
     <div><%= row.name %></div>
     <%= for button <- row.buttons do %>
-    <button class="btn btn-primary btn-robotica" phx-click="activate" phx-value-row="<%= row.name %>" phx-value-button="<%= button.name %>"><%= button.name %></button>
+    <button class='btn btn-primary btn-robotica' phx-click='activate' phx-value-row='<%= row.name %>' phx-value-button='<%= button.name %>'><%= button.name %></button>
     <% end %>
     </div>
     <% end %>
```

This patch solves the problem.

### Expected behavior

No error.

**Comment by brianmay** [comment]
I am not that familiar with `:erlang.iolist_to_binary`, but I would have expected it should receive a list, not a map or a struct?

**Comment by brianmay** [comment]
Hmm. Tonight I can't even reproduce the error anymore. Exactly same code as before...

**Comment by josevalim** [comment]
@brianmay please include your Phoenix LiveView version and a mechanism to reproduce the error. If you can no longer reproduce it, it may have a protocol consolidation error that has been addressed (or a more recent version).

**Comment by brianmay** [comment]
I believed I was on the latest version at the time. Wondering if I was mistaken. As I can't reproduce this, I am going to close for now. Will reopen if I it happens again.
