### ISSUE TITLE
"Cannot convert component" with comprehensions

### ISSUE THREAD

**Issue by hurty** [phoenixframework/phoenix_live_view#505]
### Environment

* Elixir version (elixir -v): Elixir 1.9.1 (compiled with Erlang/OTP 20)
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 0.4.1
* NodeJS version (node -v): v12.12.0
* NPM version (npm -v): 6.11.3
* Operating system: MacOS 10.14.6

### Actual behavior

If we render multiple components through a comprehension, it works fine:

```eex
<%= for message <- @messages do %>
  <%= live_component @socket, ComponentBugWeb.MessageComponent, id: message.id, message: message %>
<% end %>
```

But if we add some conditionals around live_component/3 :

```eex
<%= for message <- @messages do %>
  <%= if message.id do %>
    <%= live_component @socket, ComponentBugWeb.MessageComponent, id: message.id, message: message %>
    <% end %>
<% end %>
 ```

Then we got a `cannot convert component` error:

```
[error] #PID<0.384.0> running ComponentBugWeb.Endpoint (connection #PID<0.376.0>, stream id 3) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) cannot convert component ComponentBugWeb.MessageComponent with id 1 to HTML. A component must always be returned directly as part of a LiveView template
        (phoenix_live_view) lib/phoenix_live_view/engine.ex:20: Phoenix.HTML.Safe.Phoenix.LiveView.Component.to_iodata/1
        (component_bug) lib/component_bug_web/live/messages_live.ex:10: anonymous fn/3 in ComponentBugWeb.MessagesLive.render/1
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        (component_bug) lib/component_bug_web/live/messages_live.ex:8: ComponentBugWeb.MessagesLive.render/1
        (phoenix_live_view) lib/phoenix_live_view/utils.ex:70: Phoenix.LiveView.Utils.to_rendered/2
        (phoenix_live_view) lib/phoenix_live_view/static.ex:213: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view) lib/phoenix_live_view/static.ex:100: Phoenix.LiveView.Static.render/3
        (phoenix_live_view) lib/phoenix_live_view/controller.ex:34: Phoenix.LiveView.Controller.live_render/3
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (component_bug) lib/component_bug_web/endpoint.ex:1: ComponentBugWeb.Endpoint.plug_builder_call/2
        (component_bug) lib/plug/debugger.ex:122: ComponentBugWeb.Endpoint."call (overridable 3)"/2
        (component_bug) lib/component_bug_web/endpoint.ex:1: ComponentBugWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /Users/pierrehurtevent/projects/component_bug/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/pierrehurtevent/projects/component_bug/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy) /Users/pierrehurtevent/projects/component_bug/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

This behaviour seems to occur only inside comprehensions.

I have an example app reproducing the issue : https://github.com/hurty/component_bug

### Expected behavior

The error shouldn't be raised.

I'm not entirely sure if this is a bug, a known limitation or a misunderstanding on my part. I have read the "Limitations" section in the docs but this looks different.

**Comment by AlexR2D2** [comment]
<%= with id <- message.id do %> 
it seems does not work too
