### ISSUE TITLE
Testing stateless nested LiveComponents does not work.

### ISSUE THREAD

**Issue by JonRowe** [phoenixframework/phoenix_live_view#542]
### Environment

* Elixir version (elixir -v): Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): * phoenix 1.4.11 (Hex package) (mix)
* Phoenix LiveView version (mix deps): * phoenix_live_view 0.4.1 (Hex package) (mix)
* NodeJS version (node -v): v10.16.3
* NPM version (npm -v): 6.9.0
* Operating system: MacOS

### Actual behaviour

A stateless component rendered inside another stateless component does not work. e.g.

```
  def render(assigns = %{events: _}) do
    ~L"""
    <section class="event-list">
    <%= for event <- @events do %>
      <%= live_component(@socket, EventPreview, event: event) %>
    <% end %>
    </section>
    """
  end
```

```
  test "it renders a list of events" do
    events = [%Item{event: "An Event"}, %Item{event: "Other Event"}]
    result = render_component(EventList, %{events: events})

    assert result =~ "An event"
    assert result =~ "Other event"
  end

```

Error:

```
 ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %Phoenix.LiveView.Component{assigns: %{event: %Ecto.Schema{}}, component: ChildComponent, id: nil} of type Phoenix.LiveView.Component (a struct). This protocol is implemented for the following type(s): Decimal, Phoenix.LiveView.Comprehension, Phoenix.LiveView.Rendered, Time, Integer, Tuple, List, DateTime, NaiveDateTime, Float, Atom, Phoenix.HTML.Form, BitString, Date
```

Whats weirder is replicating this in a fresh project causes this error:

```
 ** (ArgumentError) cannot convert component DemoWeb.Live.ChildComponent with id nil to HTML. A component must always be returned directly as part of a LiveView template
     code: assert render_component(ParentComponent, %{items: [%{title: "Hi!"}]}) =~ "Hi!"
     stacktrace:
       (phoenix_live_view) lib/phoenix_live_view/engine.ex:20: Phoenix.HTML.Safe.Phoenix.LiveView.Component.to_iodata/1
       (phoenix_live_view) lib/phoenix_live_view/engine.ex:56: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/2
       (phoenix_live_view) lib/phoenix_live_view/engine.ex:52: anonymous fn/3 in Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/1
       (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
       (phoenix_live_view) lib/phoenix_live_view/engine.ex:52: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/1
       (phoenix_live_view) lib/phoenix_live_view/engine.ex:110: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3
       (phoenix_live_view) lib/phoenix_live_view/test/live_view_test.ex:365: Phoenix.LiveViewTest.render_component/2
       test/demo_web/live/component_issue_test.exs:13: (test)
```

Note that `id` is never set on these components, they are stateless.

### Expected behaviour

Tests should pass having rendered the expected text.

### Reproduction

https://github.com/JonRowe/phoenix_live_component_issue

**Comment by JonRowe** [comment]
Thanks @josevalim! I was able to use this fix in my tests :)
