### ISSUE TITLE
`live_link` does not work in `render_component`

### ISSUE THREAD

**Issue by JonRowe** [phoenixframework/phoenix_live_view#544]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 0.4.1
* NodeJS version (node -v): 10.16.3
* NPM version (npm -v): 6.9.0
* Operating system: MacOS

### Actual behaviour

Attempting to render the component:

```elixir
  def render(assigns = %{item: %{name: name, id: id}}) do
    ~L"""
    <section class="preview">
      <h1><%= name %></h1>
      <%= live_link("here", to: Routes.live_path(@socket, Analysis, id)) %>
    </section>
    """
  end
```

Causes:

```shell
  1) test it renders the name (MyApp.UI.Components.PreviewTest)
     apps/ui/test/ui/components/preview_test.exs:7
     ** (UndefinedFunctionError) function nil.path/1 is undefined
     code: assert render_component(Preview, %{item: %Item{name: "My Name", id: "1"}}) =~ "My Name"
     stacktrace:
       nil.path("/item/1/preview")
       (ui) lib/ui/components/preview.ex:10: MyApp.UI.Components.EventPreview.render/1
       (phoenix_live_view) lib/phoenix_live_view/utils.ex:70: Phoenix.LiveView.Utils.to_rendered/2
       (phoenix_live_view) lib/phoenix_live_view/test/live_view_test.ex:363: Phoenix.LiveViewTest.render_component/2
       test/ui/components/preview_test.exs:8: (test)

```

### Expected behaviour

I expect `render_component` to produce HTML to be asserted on

**Comment by JonRowe** [comment]
Thanks (again) @josevalim can confirm this is fixed on master.
