### ISSUE TITLE
live_component within live_patch/live_redirect fails to render

### ISSUE THREAD

**Issue by lnr0626** [phoenixframework/phoenix_live_view#693]
### Environment

* Elixir version (elixir -v): `1.10.2`
* Phoenix version (mix deps):
```
* phoenix 1.4.15 (Hex package) (mix)
  locked at 1.4.15 (phoenix) fd649bf1
```
* Phoenix LiveView version (mix deps):
```
* phoenix_live_view 0.9.0 (Hex package) (mix)
  locked at 0.9.0 (phoenix_live_view) 7b2201db
```
* NodeJS version (node -v): `12.13.0`
* NPM version (npm -v): `6.12.0`
* Operating system: macOS 10.15.3

### Actual behavior

Using a live component within the do block of `live_patch`/`live_redirect` results in the following error message:
```
[error] #PID<0.468.0> running LiveRedirectBugWeb.Endpoint (connection #PID<0.467.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (ArgumentError) cannot convert component LiveRedirectBugWeb.PageComponent with id nil to HTML. A component must always be returned directly as part of a LiveView template
        (phoenix_live_view 0.9.0) lib/phoenix_live_view/engine.ex:20: Phoenix.HTML.Safe.Phoenix.LiveView.Component.to_iodata/1
        (live_redirect_bug 0.1.0) lib/live_redirect_bug_web/live/page_live.ex:7: anonymous fn/2 in LiveRedirectBugWeb.PageLive.render/1
        (phoenix_live_view 0.9.0) lib/phoenix_live_view/diff.ex:221: Phoenix.LiveView.Diff.traverse/5
        (phoenix_live_view 0.9.0) lib/phoenix_live_view/diff.ex:92: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.9.0) lib/phoenix_live_view/static.ex:275: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.9.0) lib/phoenix_live_view/static.ex:137: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.9.0) lib/phoenix_live_view/controller.ex:35: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.4.15) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (live_redirect_bug 0.1.0) lib/live_redirect_bug_web/endpoint.ex:1: LiveRedirectBugWeb.Endpoint.plug_builder_call/2
        (live_redirect_bug 0.1.0) lib/plug/debugger.ex:130: LiveRedirectBugWeb.Endpoint."call (overridable 3)"/2
        (live_redirect_bug 0.1.0) lib/live_redirect_bug_web/endpoint.ex:1: LiveRedirectBugWeb.Endpoint.call/2
        (phoenix 1.4.15) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.7.0) ~/code/live_redirect_bug/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy 2.7.0) ~/code/live_redirect_bug/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy 2.7.0) ~/code/live_redirect_bug/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I originally encountered this error while using surface; however was able to reproduce it using just just straight live view (https://github.com/lnr0626/live-view-redirect-issue). 

### Expected behavior

either live components to work within the do block of `live_patch`/`live_redirect`, or for this to be documented if it's the intended behavior.

**Comment by josevalim** [comment]
This is documented here: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-limitations - it has some examples of how this issue arises in content_tag, form_for and friends.

**Comment by lnr0626** [comment]
Would you be receptive to a PR for a `content_tag` like helper that supported change tracking?

**Comment by josevalim** [comment]
Unfortunately it is not possible. The way LV components work is that we need to "see" them in the template. Once you pass it to a function and that function builds the markup, then we can no longer support it.

**Comment by lnr0626** [comment]
Ah, I think i see the issue. Thanks for the quick responses!
