### ISSUE TITLE
function Phoenix.LiveView.Socket.child_spec/1 is undefined (module Phoenix.LiveView.Socket is not available)

### ISSUE THREAD

**Issue by ruben44bac** [phoenixframework/phoenix_live_view#715]
### Environment

* Elixir version (elixir -v): 1.9.1
* Phoenix version (mix deps): 1.4.11
* Phoenix LiveView version (mix deps): 0.8.0
* NodeJS version (node -v): 10.15
* NPM version (npm -v): 6.10.2
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier):  
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I'm deploying to production my project but I have this error and my docker died immediately, in dev the project work fine. 

```
[info] Application stormbreaker_web exited: StormbreakerWeb.Application.start(:normal, []) returned an error: shutdown: failed to start child: StormbreakerWeb.Endpoint
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Phoenix.LiveView.Socket.child_spec/1 is undefined (module Phoenix.LiveView.Socket is not available)
            Phoenix.LiveView.Socket.child_spec([endpoint: StormbreakerWeb.Endpoint, websocket: [connect_info: [session: [store: :cookie, key: "_stormbreaker_web_key", signing_salt: "4I0bRMaU"]]]])
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
            (phoenix) lib/phoenix/endpoint/supervisor.ex:58: Phoenix.Endpoint.Supervisor.init/1
            (stdlib) supervisor.erl:295: :supervisor.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
{"Kernel pid terminated",application_controller,"{application_start_failure,stormbreaker_web,{{shutdown,{failed_to_start_child,'Elixir.StormbreakerWeb.Endpoint',{undef,[{'Elixir.Phoenix.LiveView.Socket',child_spec,[[{endpoint,'Elixir.StormbreakerWeb.Endpoint'},{websocket,[{connect_info,[{session,[{store,cookie},{key,<<\"_stormbreaker_web_key\">>},{signing_salt,<<\"4I0bRMaU\">>}]}]}]}]],[]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,\"lib/enum.ex\"},{line,1336}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,\"lib/enum.ex\"},{line,1336}]},{'Elixir.Phoenix.Endpoint.Supervisor',init,1,[{file,\"lib/phoenix/endpoint/supervisor.ex\"},{line,58}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,295}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{'Elixir.StormbreakerWeb.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,stormbreaker_web,{{shutdown,{failed_to_start_child,'Elixir.StormbreakerWeb.Endpoint',{undef,[{'Elixir.Phoenix.LiveView.Socket

Crash dump is being written to: erl_crash.dump...done

```
this is my endpoint file:

```
defmodule StormbreakerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :stormbreaker_web

  @session_options [
    store: :cookie,
    key: "_stormbreaker_web_key",
    signing_salt: "4I0bRMaU"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]]

  socket "/socket", StormbreakerWeb.UserSocket,
    websocket: true,
    longpoll: false

  plug Plug.Static,
    at: "/",
    from: :stormbreaker_web,
    gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger


  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug StormbreakerWeb.Router
end

```
my project is in umbrella

**Comment by josevalim** [comment]
Make sure the web app depends on `phoenix_live_view` and if there is any caching in production, such as a `_build` directory, clean it before deploying. If the error continues, then please provide an application with steps to reproduce the error. Thank you.
