### ISSUE TITLE
render_component in a stateful component referencing @myself throws "assign @myself not available in eex template."

### ISSUE THREAD

**Issue by joshuataylor** [phoenixframework/phoenix_live_view#818]
### Environment

* Elixir version (elixir -v): 1.10.2
* Phoenix version (mix deps): 1.5.1
* Phoenix LiveView version (mix deps): 0.12.1
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: Ubuntu 20.04 / N/A
* Browsers you attempted to reproduce this bug on (the more the merrier):  N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

So I'm following along with testing a component at https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#module-testing-components , and trying to do the following:
 ```
render_component(Foobar.WorldView, id: foo.id, foo: foo)
```
However this throws the following error:
```
     ** (ArgumentError) assign @myself not available in eex template.
     
     Please make sure all proper assigns have been set. If this
     is a child template, ensure assigns are given explicitly by
     the parent template as they are not automatically forwarded.
     
     Available assigns: [:changeset, :flash, :socket, :view_module, :view_template]
     code: render_component(Foobar.WorldView, id: c_test.id, test: c_test)
     stacktrace:
       (phoenix_live_view 0.12.1) lib/phoenix_live_view/engine.ex:860: Phoenix.LiveView.Engine.fetch_assign!/2
       (foobar 0.1.0) lib/xxx/xxx/test/xxx.html.leex:2: anonymous fn/2 in Foobar.WorldView."add_variable.html"/1
       (phoenix_live_view 0.12.1) lib/phoenix_live_view/diff.ex:221: Phoenix.LiveView.Diff.traverse/5
       (phoenix_live_view 0.12.1) lib/phoenix_live_view/diff.ex:92: Phoenix.LiveView.Diff.render/3
       (phoenix_live_view 0.12.1) lib/phoenix_live_view/test/live_view_test.ex:401: Phoenix.LiveViewTest.__render_component__/3
```

I think because I use @myself and this is not a stateless component?

https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-targeting-component-events

### Expected behavior

It works.

**Comment by joshuataylor** [comment]
Works, thanks so much!
