### ISSUE TITLE
live_patch results in maps cannot be converted to_param. A struct was expected, got: %{sort_by: "name"}

### ISSUE THREAD

**Issue by joshuataylor** [phoenixframework/phoenix_live_view#846]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3
* Phoenix version (mix deps): 1.5
* Phoenix LiveView version (mix deps): https://github.com/phoenixframework/phoenix_live_view/commit/bc84de6af161da98c718a07bba6888e44fbfa396
* NodeJS version (node -v): N/A
* NPM version (npm -v): N/A
* Operating system: Ubuntu 20.04
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: no

### Actual behavior

Trying to do this:
```
<%= live_patch "Sort by name", to: Routes.live_path(@socket, UserTable, %{sort_by: "name"}) %>
```

Results in:
```
[error] #PID<0.4185.0> running Foobar.Web.Endpoint (connection #PID<0.4145.0>, stream id 10) terminated
Server: localhost:4000 (http)
Request: GET /projects/1/tests
** (exit) an exception was raised:
    ** (ArgumentError) maps cannot be converted to_param. A struct was expected, got: %{sort_by: "name"}
        (phoenix 1.5.1) lib/phoenix/param.ex:77: Phoenix.Param.Map.to_param/1
        (foobar_web 0.1.0) Foobar.Web.Router.Helpers.live_path/4
        lib/foobar_web/templates/project/index.html.leex:22: anonymous fn/3 in Foobar.Web.ProjectView."index.html"/1
        (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        lib/foobar_web/templates/project/index.html.leex:20: anonymous fn/2 in Foobar.Web.ProjectView."index.html"/1
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/diff.ex:221: Phoenix.LiveView.Diff.traverse/5
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/diff.ex:288: anonymous fn/3 in Phoenix.LiveView.Diff.traverse_dynamic/5
        (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/diff.ex:221: Phoenix.LiveView.Diff.traverse/5
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/diff.ex:92: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/static.ex:279: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/static.ex:142: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.12.1) lib/phoenix_live_view/controller.ex:35: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.5.1) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (foobar_web 0.1.0) lib/foobar_web/endpoint.ex:1: Foobar.Web.Endpoint.plug_builder_call/2
        (foobar_web 0.1.0) lib/plug/debugger.ex:132: Foobar.Web.Endpoint."call (overridable 3)"/2
        (foobar_web 0.1.0) lib/foobar_web/endpoint.ex:1: Foobar.Web.Endpoint.call/2
        (phoenix 1.5.1) lib/phoenix/endpoint/cowboy2_handler.ex:64: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.7.0) /home/josh/dev/foobar/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy 2.7.0) /home/josh/dev/foobar/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
```
### Expected behavior

It works? :)

**Comment by josevalim** [comment]
What is the output of `mix phx.routes` and your routes definition? It seems that you have defined a `live` route with a parameter, which means the argument after the LiveView name is the expected parameter.

**Comment by joshuataylor** [comment]
I ended up using the params instead, and that seemed to work.

**Comment by mazz** [comment]
> What is the output of mix phx.routes and your routes definition? It seems that you have defined a live route with a parameter, which means the argument after the LiveView name is the expected parameter.

This wasn't my precise issue, but it helped me find it.
