### ISSUE TITLE
Example helper function in the docs does not compile

### ISSUE THREAD

**Issue by axelson** [phoenixframework/phoenix_live_view#899]
### Environment

* Elixir version (elixir -v): Elixir 1.10.2 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): phoenix 1.5.1
* Phoenix LiveView version (mix deps): phoenix_live_view 0.12.1
* NodeJS version (node -v): v13.12.0
* NPM version (npm -v): 6.14.4
* Operating system: Mac OS X
* Browsers you attempted to reproduce this bug on (the more the merrier): N/A
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

Adding the example helper function from the [docs](https://github.com/phoenixframework/phoenix_live_view/blob/944053b31958b6cf0eb80a6da614fe696cdc2963/lib/phoenix_live_view.ex#L380) causes a compilation error. Here is the code in question:
```
  def title(title, small) do
    ~L"""
    <h3><%= title %><small><%= small %></small></h3>
    """
  end
```

Compiling the above code results in:
```
== Compilation error in file lib/live_app_web/live/page_live.ex ==
** (CompileError) lib/live_app_web/live/page_live.ex:29: expected "assigns" to expand to an existing variable or be part of a match
    (elixir 1.10.3) expanding macro: Kernel.var!/1
    lib/live_app_web/live/page_live.ex:29: LiveAppWeb.PageLive.title/2
    expanding macro: Phoenix.LiveView.Helpers.sigil_L/2
    lib/live_app_web/live/page_live.ex:29: LiveAppWeb.PageLive.title/2
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected behavior

The sample compiles without error, or more specifically the sample should be replaced with an sample that does compile.

From talking to Chris about this on slack I'd propose either:

```
  def title(%{title: _title, small: _small} = assigns) do
    ~L"""
    <h3><%= @title %><small><%= @small %></small></h3>
    """
  end
```
or
```
  def title(title, small) do
    assigns = %{title: title, small: small}
    ~L"""
    <h3><%= @title %><small><%= @small %></small></h3>
    """
  end
```

I'd like to try writing a doc PR that fixes this sample and expands on using functions to break up a larger `render/1` clause, possibly by expanding the ["Compartmentalizing markup and events with render, live_render, and live_component"](https://hexdocs.pm/phoenix_live_view/0.12.1/Phoenix.LiveView.html#module-compartmentalizing-markup-and-events-with-render-live_render-and-live_component) section (but if it fits better somewhere else, I'm happy to adjust).

**Comment by axelson** [comment]
Thanks! That is now much more clear ❤️
