### ISSUE TITLE
Router forward/match in Umbrella project does not work - exception

### ISSUE THREAD

**Issue by SebastianStroniewskiWojtczak** [phoenixframework/phoenix_live_view#921]
### Environment

* Elixir version (elixir -v): Elixir 1.10.3
* Phoenix version (mix deps): phoenix 1.5.3 (Hex package) (mix)
* Phoenix LiveView version (mix deps): phoenix_live_view 0.13.1 (Hex package) (mix)
* NodeJS version (node -v): v13.13.0
* NPM version (npm -v): 6.12.1
* Operating system: FreeBSD 12.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Any
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Not Relevant

### Actual behavior
It does forward but cannot invoke methods
VlCoreWeb reouter.ex:
**** 
 scope "/" do
    forward "/pane", VlCorePanel.Router
    match(:*, "/panel", VlCorePanel.Router, :panel)
  end

****

07:03:16.179 [error] GenServer #PID<0.804.0> terminating
** (ArgumentError) cannot invoke handle_params nor live_redirect/live_patch to "http://localhost:4090/panel" because it isn't defined in VlCorePanel.Router
    (phoenix_live_view 0.13.0) lib/phoenix_live_view/utils.ex:227: Phoenix.LiveView.Utils.live_link_info!/3
    (phoenix_live_view 0.13.0) lib/phoenix_live_view/channel.ex:652: Phoenix.LiveView.Channel.verified_mount/5
    (phoenix_live_view 0.13.0) lib/phoenix_live_view/channel.ex:43: Phoenix.LiveView.Channel.handle_info/2
Last message: {Phoenix.Channel, %{"params" => %{"_csrf_token" => "OzJqNhsoGiAEVyspdiopAyoPDikbB3Usme3xScEuNcaY7BeFPHt_LRBb", "_mounts" => 0, "_track_static" => ["http://localhost:4090/css/app.css", "http://localhost:4090/js/app.js"]}, "session" => "SFMyNTY.g2gDaAJhBHQAAAAHZAACaWRtAAAAFHBoeC1GaExLRWJrVXZaS1BlZ0lEZAAKcGFyZW50X3BpZGQAA25pbGQACHJvb3RfcGlkZAADbmlsZAAJcm9vdF92aWV3ZAAbRWxpeGlyLlZsQ29yZVBhbmVsLlBhZ2VMaXZlZAAGcm91dGVyZAAZRWxpeGlyLlZsQ29yZVBhbmVsLlJvdXRlcmQAB3Nlc3Npb250AAAAAGQABHZpZXdkABtFbGl4aXIuVmxDb3JlUGFuZWwuUGFnZUxpdmVuBgCrYYNUcgFiAAFRgA.L1Eshn8oTTu6dPYHXOBl16L17oZaOX9T26gIYofm-a8", "static" => "SFMyNTY.g2gDaAJhBHQAAAADZAAKYXNzaWduX25ld2pkAAVmbGFzaHQAAAAAZAACaWRtAAAAFHBoeC1GaExLRWJrVXZaS1BlZ0lEbgYAq2GDVHIBYgABUYA.1Ilw2Awh0am4gGDNcKiK9YSXfNKwgF_CbXeO8IWKI38", "url" => "http://localhost:4090/panel"}, {#PID<0.800.0>, #Reference<0.2911100581.2148794369.93754>}, %Phoenix.Socket{assigns: %{}, channel: Phoenix.LiveView.Channel, channel_pid: nil, endpoint: VlCoreWeb.Endpoint, handler: Phoenix.LiveView.Socket, id: nil, join_ref: "4", joined: false, private: %{connect_info: %{session: %{"_csrf_token" => "VWYNHK_UJ4JpAhLEzGzvWU7N"}}}, pubsub_server: VlCoreWeb.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "lv:phx-FhLKEbkUvZKPegID", transport: :websocket, transport_pid: #PID<0.800.0>}}
State: #Reference<0.2911100581.2148794369.93756>
07:03:16.179 [error] an exception was raised:
    ** (ArgumentError) cannot invoke handle_params nor live_redirect/live_patch to "http://localhost:4090/panel" because it isn't defined in VlCorePanel.Router
        (phoenix_live_view 0.13.0) lib/phoenix_live_view/utils.ex:227: Phoenix.LiveView.Utils.live_link_info!/3
        (phoenix_live_view 0.13.0) lib/phoenix_live_view/channel.ex:652: Phoenix.LiveView.Channel.verified_mount/5
        (phoenix_live_view 0.13.0) lib/phoenix_live_view/channel.ex:43: Phoenix.LiveView.Channel.handle_info/2

### Expected behavior
Forward and Match should redirect all to another Live app in Umbrella Web PhoenixLive Apps. Next app should be capable to handle all data and requests also WebSocket which seems to be broken in umbrella.
Current workaround is to implement all routes in VlCoreWeb.Router instead.
****
  scope "/" do
    pipe_through :browser
    live "/panel", VlCorePanel.PageLive, :index
  end
****

**Comment by SebastianStroniewskiWojtczak** [comment]
I've got it working !
